<?php
namespace App\Http\Controllers\Automation;
use App\Http\Controllers\Controller;use App\Models\AutomationTemplate;use App\Services\Automation\AutomationDefinitionService;use App\Services\Automation\AutomationDefinitionValidator;use App\Services\Billing\BillingEntitlementService;use App\Services\Billing\BillingLimitService;use Illuminate\Http\Request;
class AutomationTemplateController extends Controller{
 public function __construct(private BillingEntitlementService $billing){}
 public function index(Request $r){$org=$this->org($r,'automation.view');return AutomationTemplate::where('active',true)->where(fn($q)=>$q->whereNull('organization_id')->orWhere('organization_id',$org->id))->get()->map(fn($t)=>$this->resource($t));}
 public function show(Request $r,string $template){$org=$this->org($r,'automation.view');return $this->resource($this->find($org,$template));}
 public function store(Request $r,AutomationDefinitionValidator $validator,BillingEntitlementService $billing){$org=$this->org($r,'automation.manage');$billing->requireFeature($org,'automation.advanced');$data=$r->validate(['name'=>'required|string|max:255','description'=>'nullable|string|max:2000','category'=>'required|string|max:100','definition'=>'required|array']);$validator->validate($data['definition'],$org);$template=AutomationTemplate::create(['organization_id'=>$org->id,'name'=>$data['name'],'description'=>$data['description']??null,'category'=>$data['category'],'definition'=>$data['definition'],'created_by'=>$r->user()->id]);return response()->json($this->resource($template),201);}
 public function update(Request $r,string $template,AutomationDefinitionValidator $validator,BillingEntitlementService $billing){$org=$this->org($r,'automation.manage');$billing->requireFeature($org,'automation.advanced');$t=$this->findOwned($org,$template);$data=$r->validate(['name'=>'sometimes|required|string|max:255','description'=>'nullable|string|max:2000','category'=>'sometimes|required|string|max:100','definition'=>'sometimes|required|array']);if(isset($data['definition']))$validator->validate($data['definition'],$org);$t->update($data);return $this->resource($t);}
 public function destroy(Request $r,string $template){$org=$this->org($r,'automation.manage');$this->findOwned($org,$template)->delete();return response()->noContent();}
 public function instantiate(Request $r,string $template,AutomationDefinitionService $definitions,AutomationDefinitionValidator $validator,BillingLimitService $limits,BillingEntitlementService $billing){$org=$this->org($r,'automation.create');$billing->requireFeature($org,'automation.basic');$t=$this->find($org,$template);$limits->ensureAutomationAvailable($org);if($validator->requiresAdvanced($t->definition))$billing->requireFeature($org,'automation.advanced');$a=$definitions->create($org,$r->user(),$t->definition);$d=$definitions->definition($a);return response()->json(['id'=>(string)$a->id,'name'=>$a->name,'description'=>$a->description,'status'=>$a->status,'enabled'=>$a->enabled,'version'=>$a->version,'trigger'=>$d['trigger'],'conditions'=>$d['conditions'],'actions'=>$d['actions'],'schedule'=>$d['schedule'],'createdAt'=>$a->created_at->toISOString(),'updatedAt'=>$a->updated_at->toISOString()],201);}
 private function org(Request $r,string $p){abort_unless($r->user()->organization&&$r->user()->hasOrganizationPermission($p),403);$this->billing->requireFeature($r->user()->organization,'automation.basic');return $r->user()->organization;}
 private function find($org,$id){return AutomationTemplate::where(fn($q)=>$q->whereNull('organization_id')->orWhere('organization_id',$org->id))->findOrFail($id);}private function findOwned($org,$id){return AutomationTemplate::where('organization_id',$org->id)->findOrFail($id);}
 private function resource($t):array{$d=$t->definition;return ['id'=>(string)$t->id,'name'=>$t->name,'description'=>$t->description??'','category'=>$t->category,'trigger'=>$d['trigger']??null,'conditions'=>$d['conditions']??null,'actions'=>$d['actions']??[],'definition'=>$d,'createdAt'=>$t->created_at->toISOString()];}
}
