<?php
namespace App\Http\Controllers\Automation;
use App\Http\Controllers\Controller;use App\Models\Automation;use App\Services\Automation\AutomationDefinitionService;use App\Services\Automation\AutomationDefinitionValidator;use App\Services\Automation\AutomationExecutionService;use App\Services\Billing\BillingEntitlementService;use App\Services\Billing\BillingLimitService;use Illuminate\Http\Request;
class AutomationController extends Controller{
 public function __construct(private AutomationDefinitionService $definitions,private AutomationDefinitionValidator $validator,private BillingEntitlementService $billing){}
 public function index(Request $r){$org=$this->access($r,'automation.view');$this->billing->requireFeature($org,'automation.basic');return $org->automations()->with(['triggers','conditions','actions','schedules'])->latest()->get()->map(fn($a)=>$this->resource($a));}
 public function store(Request $r,BillingLimitService $limits){$org=$this->access($r,'automation.create');$this->billing->requireFeature($org,'automation.basic');$limits->ensureAutomationAvailable($org);$data=$this->validator->validate($r->all(),$org);if($this->validator->requiresAdvanced($data))$this->billing->requireFeature($org,'automation.advanced');return response()->json($this->resource($this->definitions->create($org,$r->user(),$data)),201);}
 public function show(Request $r,string $automation){$org=$this->access($r,'automation.view');$this->billing->requireFeature($org,'automation.basic');return $this->resource($this->find($org,$automation));}
 public function update(Request $r,string $automation){$org=$this->access($r,'automation.update');$this->billing->requireFeature($org,'automation.basic');$a=$this->find($org,$automation);$merged=array_replace_recursive($this->definitions->definition($a),$r->all());if($this->validator->requiresAdvanced($merged))$this->billing->requireFeature($org,'automation.advanced');return $this->resource($this->definitions->update($a,$r->user(),$r->all()));}
 public function destroy(Request $r,string $automation){$org=$this->access($r,'automation.delete');$this->billing->requireFeature($org,'automation.basic');$this->find($org,$automation)->delete();return response()->noContent();}
 public function enable(Request $r,string $automation){return $this->toggle($r,$automation,true);}
 public function disable(Request $r,string $automation){return $this->toggle($r,$automation,false);}
 public function execute(Request $r,string $automation,AutomationExecutionService $service){$org=$this->access($r,'automation.execute');$a=$this->find($org,$automation);$data=$r->validate(['data'=>'sometimes|array','correlationId'=>'sometimes|uuid']);return response()->json($this->execution($service->execute($a,'manual',$data['data']??[],$data['correlationId']??null)));}
 public function executions(Request $r,string $automation){$org=$this->access($r,'automation.view');$this->billing->requireFeature($org,'automation.basic');$a=$this->find($org,$automation);return $a->executions()->latest()->paginate(min((int)$r->input('perPage',20),100))->through(fn($e)=>$this->execution($e));}
 public function logs(Request $r,string $automation){$org=$this->access($r,'automation.view');$this->billing->requireFeature($org,'automation.basic');$a=$this->find($org,$automation);return \App\Models\AutomationExecutionLog::whereHas('execution',fn($q)=>$q->where('automation_id',$a->id)->where('organization_id',$org->id))->latest('executed_at')->paginate(50);}
 private function toggle(Request $r,string $id,bool $enabled){$org=$this->access($r,'automation.manage');$this->billing->requireFeature($org,'automation.basic');$a=$this->find($org,$id);if($enabled){$data=$this->definitions->definition($a);$this->validator->validate($data,$org);if($this->validator->requiresAdvanced($data))$this->billing->requireFeature($org,'automation.advanced');}$a->update(['enabled'=>$enabled,'status'=>$enabled?'active':'disabled','updated_by'=>$r->user()->id]);return $this->resource($a->refresh()->load(['triggers','conditions','actions','schedules']));}
 private function access(Request $r,string $permission){abort_unless($r->user()->organization&&$r->user()->hasOrganizationPermission($permission),403);return $r->user()->organization;}
 private function find($org,string $id):Automation{return $org->automations()->with(['triggers','conditions','actions','schedules'])->findOrFail($id);}
 private function resource(Automation $a):array{$d=$this->definitions->definition($a);return ['id'=>(string)$a->id,'name'=>$a->name,'description'=>$a->description,'status'=>$a->status,'enabled'=>$a->enabled,'version'=>$a->version,'trigger'=>$d['trigger'],'conditions'=>$d['conditions'],'actions'=>$d['actions'],'schedule'=>$d['schedule'],'lastExecutedAt'=>$a->last_executed_at?->toISOString(),'createdAt'=>$a->created_at->toISOString(),'updatedAt'=>$a->updated_at->toISOString()];}
 private function execution($e):array{return ['id'=>(string)$e->id,'automationId'=>(string)$e->automation_id,'status'=>$e->status,'triggerType'=>$e->trigger_type,'triggerData'=>$e->trigger_data??[],'startedAt'=>$e->started_at?->toISOString(),'completedAt'=>$e->completed_at?->toISOString(),'error'=>$e->error_message,'result'=>$e->result_summary];}
}
