<?php
namespace App\Http\Controllers\Automation;
use App\Http\Controllers\Controller;use App\Models\AutomationSchedule;use App\Services\Automation\AutomationScheduleService;use Illuminate\Http\Request;
class AutomationScheduleController extends Controller{
 public function __construct(private AutomationScheduleService $schedules){}
 public function index(Request $r){$org=$this->org($r,'automation.view');return AutomationSchedule::whereHas('automation',fn($q)=>$q->where('organization_id',$org->id))->get();}
 public function store(Request $r){$org=$this->org($r,'automation.update');$d=$this->validateSchedule($r,true);$a=$org->automations()->findOrFail($d['automationId']);$configuration=array_diff_key($d,['automationId'=>true,'type'=>true,'enabled'=>true]);$s=$a->schedules()->create(['type'=>$d['type'],'enabled'=>$d['enabled'],'configuration'=>$configuration,'next_run_at'=>$this->schedules->nextRun($d)]);return response()->json($s,201);}
 public function update(Request $r,string $schedule){$org=$this->org($r,'automation.update');$s=$this->find($org,$schedule);$current=['type'=>$s->type,'enabled'=>$s->enabled,...$s->configuration];$d=$this->validateSchedule($r,false,$current);$configuration=array_diff_key($d,['automationId'=>true,'type'=>true,'enabled'=>true]);$s->update(['type'=>$d['type'],'enabled'=>$d['enabled'],'configuration'=>$configuration,'next_run_at'=>$this->schedules->nextRun($d)]);return $s->refresh();}
 public function destroy(Request $r,string $schedule){$org=$this->org($r,'automation.update');AutomationSchedule::whereHas('automation',fn($q)=>$q->where('organization_id',$org->id))->findOrFail($schedule)->delete();return response()->noContent();}
 private function validateSchedule(Request $r,bool $creating,array $current=[]):array{$rules=['automationId'=>($creating?'required':'sometimes').'|integer','type'=>($creating?'required':'sometimes').'|in:once,daily,weekly,interval','time'=>'nullable|date_format:H:i','day'=>'nullable|in:Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday','intervalMinutes'=>'nullable|integer|min:1|max:10080','at'=>'nullable|date|after:now','enabled'=>($creating?'required':'sometimes').'|boolean'];$d=[...$current,...$r->validate($rules)];$required=match($d['type']??null){'once'=>'at','daily'=>'time','weekly'=>'day,time','interval'=>'intervalMinutes',default=>null};if($required)foreach(explode(',',$required) as $field)if(!isset($d[$field]))throw \Illuminate\Validation\ValidationException::withMessages([$field=>"The $field field is required for this schedule type."]);return $d;}
 private function find($org,string $schedule):AutomationSchedule{return AutomationSchedule::whereHas('automation',fn($q)=>$q->where('organization_id',$org->id))->findOrFail($schedule);}
 private function org(Request $r,string $p){abort_unless($r->user()->organization&&$r->user()->hasOrganizationPermission($p),403);return $r->user()->organization;}
}
