<?php

use App\Http\Controllers\Admin\AdminBillingController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Auth\AuthController;
use App\Http\Controllers\Billing\BillingController;
use App\Http\Controllers\Billing\BillingUsageController;
use App\Http\Controllers\Billing\BillingWebhookController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DeviceController;
use App\Http\Controllers\Organization\OrganizationController;
use App\Http\Controllers\Organization\InvitationController;
use App\Http\Controllers\Profile\ProfileController;
use App\Http\Controllers\TelemetryController;
use App\Http\Controllers\AnalyticsController;
use App\Http\Controllers\Automation\AutomationController;
use App\Http\Controllers\Automation\AutomationEventController;
use App\Http\Controllers\Automation\AutomationLogController;
use App\Http\Controllers\Automation\AutomationScheduleController;
use App\Http\Controllers\Automation\AutomationTemplateController;
use Illuminate\Support\Facades\Route;

Route::prefix('auth')->group(function () {
    Route::post('login',[AuthController::class,'login'])->middleware('throttle:5,1');
    Route::post('register',[AuthController::class,'register'])->middleware('throttle:3,1');
});
Route::post('billing/webhook',[BillingWebhookController::class,'handle']);
Route::get('billing/plans',[BillingController::class,'plans']);

Route::middleware(['auth:sanctum','active'])->group(function () {
    Route::post('telemetry',[TelemetryController::class,'store']);
    Route::get('analytics/summary',[AnalyticsController::class,'summary']);
    Route::get('analytics/devices/{device}',[AnalyticsController::class,'device']);
    Route::get('analytics/telemetry/{metric}',[AnalyticsController::class,'telemetry']);
    Route::get('automations',[AutomationController::class,'index']);
    Route::post('automations',[AutomationController::class,'store']);
    Route::get('automations/{automation}',[AutomationController::class,'show']);
    Route::put('automations/{automation}',[AutomationController::class,'update']);
    Route::patch('automations/{automation}',[AutomationController::class,'update']);
    Route::delete('automations/{automation}',[AutomationController::class,'destroy']);
    Route::post('automations/{automation}/enable',[AutomationController::class,'enable']);
    Route::post('automations/{automation}/disable',[AutomationController::class,'disable']);
    Route::post('automations/{automation}/execute',[AutomationController::class,'execute']);
    Route::get('automations/{automation}/executions',[AutomationController::class,'executions']);
    Route::get('automations/{automation}/logs',[AutomationController::class,'logs']);
    Route::get('automation/logs',[AutomationLogController::class,'index']);
    Route::get('automation/logs/{execution}',[AutomationLogController::class,'show']);
    Route::post('automation/events',[AutomationEventController::class,'store']);
    Route::get('automation/events',[AutomationEventController::class,'index']);
    Route::get('automation/schedules',[AutomationScheduleController::class,'index']);
    Route::post('automation/schedules',[AutomationScheduleController::class,'store']);
    Route::put('automation/schedules/{schedule}',[AutomationScheduleController::class,'update']);
    Route::patch('automation/schedules/{schedule}',[AutomationScheduleController::class,'update']);
    Route::delete('automation/schedules/{schedule}',[AutomationScheduleController::class,'destroy']);
    Route::get('automation/templates',[AutomationTemplateController::class,'index']);
    Route::post('automation/templates',[AutomationTemplateController::class,'store']);
    Route::get('automation/templates/{template}',[AutomationTemplateController::class,'show']);
    Route::put('automation/templates/{template}',[AutomationTemplateController::class,'update']);
    Route::delete('automation/templates/{template}',[AutomationTemplateController::class,'destroy']);
    Route::post('automation/templates/{template}/create',[AutomationTemplateController::class,'instantiate']);
    Route::get('auth/me',[AuthController::class,'me']);
    Route::post('auth/logout',[AuthController::class,'logout']);
    Route::get('organization',[OrganizationController::class,'show']);
    Route::post('organization',[OrganizationController::class,'create']);
    Route::put('organization',[OrganizationController::class,'update']);
    Route::get('organization/settings',[OrganizationController::class,'settings']);
    Route::put('organization/settings',[OrganizationController::class,'updateSettings']);
    Route::get('organization/members',[OrganizationController::class,'members']);
    Route::get('organization/invitations',[InvitationController::class,'index']);
    Route::post('organization/invitations',[InvitationController::class,'store']);
    Route::delete('organization/invitations/{invitation}',[InvitationController::class,'destroy']);
    Route::post('invitations/accept',[InvitationController::class,'accept']);
    Route::get('permissions',[OrganizationController::class,'permissions']);
    Route::get('profile',[ProfileController::class,'show']);
    Route::put('profile',[ProfileController::class,'update']);
    Route::put('profile/password',[ProfileController::class,'password']);
    Route::get('profile/notifications',[ProfileController::class,'notifications']);
    Route::put('profile/notifications',[ProfileController::class,'updateNotifications']);
    Route::get('billing/subscription',[BillingController::class,'subscription']);
    Route::get('billing/entitlements',[BillingController::class,'entitlements']);
    Route::get('billing/payments',[BillingController::class,'payments']);
    Route::get('billing/usage',BillingUsageController::class);
    Route::post('billing/subscription/cancel',[BillingController::class,'cancel']);
    Route::post('billing/subscription/resume',[BillingController::class,'resume']);
    Route::post('billing/subscription/free',[BillingController::class,'activateFree']);
    Route::post('billing/checkout',[BillingController::class,'checkout']);
    Route::get('devices',[DeviceController::class,'index']);
    Route::post('devices',[DeviceController::class,'store']);
    Route::post('devices/register',[DeviceController::class,'store']);
    Route::get('devices/{device}',[DeviceController::class,'show']);
    Route::delete('devices/{device}',[DeviceController::class,'destroy']);
    Route::get('dashboards',[DashboardController::class,'index']);
    Route::post('dashboards',[DashboardController::class,'store']);
    Route::get('dashboards/{dashboard}',[DashboardController::class,'show']);
    Route::put('dashboards/{dashboard}',[DashboardController::class,'update']);
    Route::patch('dashboards/{dashboard}',[DashboardController::class,'update']);
    Route::delete('dashboards/{dashboard}',[DashboardController::class,'destroy']);
    Route::post('dashboards/{dashboard}/duplicate',[DashboardController::class,'duplicate']);
    Route::middleware('admin')->prefix('admin/billing')->group(function () {
        Route::get('organizations',[AdminBillingController::class,'organizations']);
        Route::get('stats',[AdminBillingController::class,'stats']);
    });
    Route::middleware('admin')->prefix('admin')->group(function(){
        Route::get('overview',[AdminController::class,'overview']);
        Route::get('organizations',[AdminController::class,'organizations']);
        Route::patch('organizations/{organization}/status',[AdminController::class,'organizationStatus']);
        Route::get('users',[AdminController::class,'users']);
        Route::patch('users/{user}/status',[AdminController::class,'userStatus']);
    });
});
