<?php

use App\Http\Controllers\Admin\AccessRequestController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\AdminCrashReportController;
use App\Http\Controllers\Admin\AdminDeviceCredentialController;
use App\Http\Controllers\Admin\AdminDeviceParameterController;
use App\Http\Controllers\Admin\AdminDeviceSnapshotController;
use App\Http\Controllers\Admin\AdminDeviceTemplateController;
use App\Http\Controllers\Admin\AdminDisabledResourceController;
use App\Http\Controllers\Admin\AdminGlobalDeviceController;
use App\Http\Controllers\Admin\AdminGlobalOperationsController;
use App\Http\Controllers\Admin\AdminLocationController;
use App\Http\Controllers\Admin\AdminMonitoredDeviceController;
use App\Http\Controllers\Admin\AdminOperationalEventController;
use App\Http\Controllers\Admin\AdminProvisioningSessionController;
use App\Http\Controllers\Admin\AdminRecentResourceController;
use App\Http\Controllers\Admin\AdminResourceInventoryController;
use App\Http\Controllers\Admin\AdminResourceViewController;
use App\Http\Controllers\Admin\AdminReviewCenterController;
use App\Http\Controllers\Admin\AutomationPublicationReviewController;
use App\Http\Controllers\Admin\DashboardPublicationReviewController;
use App\Http\Controllers\Admin\DeviceAccessController;
use App\Http\Controllers\Admin\FirmwareReleaseReviewController;
use App\Http\Controllers\Admin\ReportPublicationReviewController;
use App\Http\Controllers\Admin\SystemSettingController;
use App\Http\Controllers\Admin\TemplatePublicationReviewController;
use App\Http\Controllers\Admin\WebhookActivationReviewController;
use App\Http\Controllers\AnalyticsController;
use App\Http\Controllers\Auth\AuthController;
use App\Http\Controllers\Automation\AutomationController;
use App\Http\Controllers\Automation\AutomationEventController;
use App\Http\Controllers\Automation\AutomationLogController;
use App\Http\Controllers\Automation\AutomationScheduleController;
use App\Http\Controllers\Automation\AutomationTemplateController;
use App\Http\Controllers\AutomationPublicationController;
use App\Http\Controllers\CollaborationActivityController;
use App\Http\Controllers\CollaborationOverviewController;
use App\Http\Controllers\CollaborationCommentController;
use App\Http\Controllers\CrashReportController;
use App\Http\Controllers\CrossDomainSearchController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DashboardMapAssetController;
use App\Http\Controllers\DashboardMapProjectionController;
use App\Http\Controllers\DashboardPublicationController;
use App\Http\Controllers\DeviceApi\DeviceCrashReportController;
use App\Http\Controllers\DeviceApi\DeviceFirmwareController;
use App\Http\Controllers\DeviceApi\DeviceTelemetryController;
use App\Http\Controllers\DeviceApi\DeviceEventIngestionController;
use App\Http\Controllers\DeviceController;
use App\Http\Controllers\DeviceMetadataController;
use App\Http\Controllers\DeviceEventController;
use App\Http\Controllers\DeviceEventFeedController;
use App\Http\Controllers\DeviceCredentialController;
use App\Http\Controllers\DeviceDashboardController;
use App\Http\Controllers\DeviceParameterController;
use App\Http\Controllers\DeviceSnapshotController;
use App\Http\Controllers\DeviceTemplateController;
use App\Http\Controllers\FirmwareArtifactController;
use App\Http\Controllers\FirmwareDeploymentController;
use App\Http\Controllers\FirmwareReleaseController;
use App\Http\Controllers\FleetController;
use App\Http\Controllers\HealthController;
use App\Http\Controllers\LocationController;
use App\Http\Controllers\MyWorkController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\NotificationPreferenceController;
use App\Http\Controllers\OperationalEventController;
use App\Http\Controllers\Organization\InvitationController;
use App\Http\Controllers\Organization\OrganizationController;
use App\Http\Controllers\Profile\ProfileController;
use App\Http\Controllers\ProvisioningSessionController;
use App\Http\Controllers\PullUpdateController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\ReportPublicationController;
use App\Http\Controllers\ReportRunController;
use App\Http\Controllers\ResourceAttentionController;
use App\Http\Controllers\ResourceAttributionController;
use App\Http\Controllers\ResourceDraftController;
use App\Http\Controllers\ResourceEditingSessionController;
use App\Http\Controllers\ResourceLifecycleController;
use App\Http\Controllers\ResourceRevisionController;
use App\Http\Controllers\ResourceShareController;
use App\Http\Controllers\RevisionComparisonController;
use App\Http\Controllers\RevisionReminderController;
use App\Http\Controllers\SharedWithMeController;
use App\Http\Controllers\TelemetryController;
use App\Http\Controllers\TemplatePublicationController;
use App\Http\Controllers\TemplatePublicationVersionController;
use App\Http\Controllers\WebhookActivationController;
use App\Http\Controllers\WebhookController;
use App\Http\Controllers\WebhookDeliveryController;
use Illuminate\Support\Facades\Route;

Route::prefix('auth')->group(function () {
    Route::post('login', [AuthController::class, 'login'])->middleware('throttle:login');
});

Route::get('health/readiness', HealthController::class)->middleware('throttle:30,1');

Route::prefix('device')->middleware('throttle:device-api')->group(function () {
    Route::post('telemetry', [DeviceTelemetryController::class, 'store'])->middleware('device.auth:telemetry:write');
    Route::post('events', [DeviceEventIngestionController::class, 'store'])->middleware('device.auth:events:write');
    Route::get('firmware/{target}/download', [DeviceFirmwareController::class, 'download'])->middleware('device.auth:firmware:read');
    Route::post('crash-reports', [DeviceCrashReportController::class, 'store'])->middleware('device.auth:crash:write');
});

Route::middleware(['auth:sanctum', 'active'])->group(function () {
    Route::get('search', CrossDomainSearchController::class);
    Route::get('collaboration-overview', CollaborationOverviewController::class);
    Route::get('shared-with-me', SharedWithMeController::class);
    Route::get('my-work', MyWorkController::class);
    Route::get('collaboration/resources/{type}/{resource}/attribution', [ResourceAttributionController::class, 'show']);
    Route::post('telemetry', [TelemetryController::class, 'store']);
    Route::get('devices/{device}/metadata', [DeviceMetadataController::class, 'index']);
    Route::post('devices/{device}/metadata', [DeviceMetadataController::class, 'store']);
    Route::get('devices/{device}/events', [DeviceEventController::class, 'index']);
    Route::get('device-events', [DeviceEventFeedController::class, 'index']);
    Route::get('analytics/summary', [AnalyticsController::class, 'summary']);
    Route::get('analytics/devices/{device}', [AnalyticsController::class, 'device']);
    Route::get('analytics/telemetry/{metric}', [AnalyticsController::class, 'telemetry']);
    Route::get('automations', [AutomationController::class, 'index']);
    Route::get('automations/published/catalog', [AutomationPublicationController::class, 'catalog']);
    Route::get('automations/published/{automation}', [AutomationPublicationController::class, 'published']);
    Route::post('automations', [AutomationController::class, 'store']);
    Route::get('automations/{automation}', [AutomationController::class, 'show']);
    Route::put('automations/{automation}', [AutomationController::class, 'update']);
    Route::patch('automations/{automation}', [AutomationController::class, 'update']);
    Route::delete('automations/{automation}', [AutomationController::class, 'destroy']);
    Route::post('automations/{automation}/enable', [AutomationController::class, 'enable']);
    Route::post('automations/{automation}/disable', [AutomationController::class, 'disable']);
    Route::post('automations/{automation}/execute', [AutomationController::class, 'execute']);
    Route::get('automations/{automation}/executions', [AutomationController::class, 'executions']);
    Route::get('automations/{automation}/logs', [AutomationController::class, 'logs']);
    Route::get('automations/{automation}/publication', [AutomationPublicationController::class, 'state']);
    Route::post('automations/{automation}/publication-submissions', [AutomationPublicationController::class, 'submit']);
    Route::get('automations/{automation}/review-history', [AutomationPublicationController::class, 'history']);
    Route::get('automation/logs', [AutomationLogController::class, 'index']);
    Route::get('automation/logs/{execution}', [AutomationLogController::class, 'show']);
    Route::post('automation/events', [AutomationEventController::class, 'store']);
    Route::get('automation/events', [AutomationEventController::class, 'index']);
    Route::get('automation/schedules', [AutomationScheduleController::class, 'index']);
    Route::post('automation/schedules', [AutomationScheduleController::class, 'store']);
    Route::put('automation/schedules/{schedule}', [AutomationScheduleController::class, 'update']);
    Route::patch('automation/schedules/{schedule}', [AutomationScheduleController::class, 'update']);
    Route::delete('automation/schedules/{schedule}', [AutomationScheduleController::class, 'destroy']);
    Route::get('automation/templates', [AutomationTemplateController::class, 'index']);
    Route::post('automation/templates', [AutomationTemplateController::class, 'store']);
    Route::get('automation/templates/{template}', [AutomationTemplateController::class, 'show']);
    Route::put('automation/templates/{template}', [AutomationTemplateController::class, 'update']);
    Route::delete('automation/templates/{template}', [AutomationTemplateController::class, 'destroy']);
    Route::post('automation/templates/{template}/create', [AutomationTemplateController::class, 'instantiate']);
    Route::get('auth/me', [AuthController::class, 'me']);
    Route::post('auth/logout', [AuthController::class, 'logout']);
    Route::get('organization', [OrganizationController::class, 'show']);
    Route::post('organization', [OrganizationController::class, 'create']);
    Route::put('organization', [OrganizationController::class, 'update']);
    Route::get('organization/settings', [OrganizationController::class, 'settings']);
    Route::put('organization/settings', [OrganizationController::class, 'updateSettings']);
    Route::get('organization/members', [OrganizationController::class, 'members']);
    Route::get('organization/invitations', [InvitationController::class, 'index']);
    Route::post('organization/invitations', [InvitationController::class, 'store']);
    Route::delete('organization/invitations/{invitation}', [InvitationController::class, 'destroy']);
    Route::post('invitations/accept', [InvitationController::class, 'accept']);
    Route::get('permissions', [OrganizationController::class, 'permissions']);
    Route::get('profile', [ProfileController::class, 'show']);
    Route::put('profile', [ProfileController::class, 'update']);
    Route::put('profile/password', [ProfileController::class, 'password']);
    Route::get('profile/notifications', [NotificationPreferenceController::class, 'show']);
    Route::patch('profile/notifications', [NotificationPreferenceController::class, 'update']);
    Route::delete('profile/notifications', [NotificationPreferenceController::class, 'reset']);
    Route::get('activity', [CollaborationActivityController::class, 'index']);
    Route::get('activity/metadata', [CollaborationActivityController::class, 'metadata']);
    Route::get('collaboration/resources/{type}/{resource}/activity', [CollaborationActivityController::class, 'resource']);
    Route::get('notifications', [NotificationController::class, 'index']);
    Route::get('notifications/recent', [NotificationController::class, 'recent']);
    Route::get('notifications/unread-count', [NotificationController::class, 'unreadCount']);
    Route::post('notifications/read-all', [NotificationController::class, 'markAllRead']);
    Route::post('notifications/{notification}/read', [NotificationController::class, 'markRead']);
    Route::post('notifications/{notification}/unread', [NotificationController::class, 'markUnread']);
    Route::post('notifications/{notification}/dismiss', [NotificationController::class, 'dismiss']);
    Route::post('notifications/{notification}/restore', [NotificationController::class, 'restore']);
    Route::get('shares/candidates', [ResourceShareController::class, 'candidates']);
    Route::get('shares/incoming', [ResourceShareController::class, 'incoming']);
    Route::get('shares/sent', [ResourceShareController::class, 'sent']);
    Route::post('shares', [ResourceShareController::class, 'store']);
    Route::get('shares/{shareRequest}', [ResourceShareController::class, 'show']);
    Route::post('shares/{shareRequest}/accept', [ResourceShareController::class, 'accept']);
    Route::post('shares/{shareRequest}/decline', [ResourceShareController::class, 'decline']);
    Route::post('shares/{shareRequest}/cancel', [ResourceShareController::class, 'cancel']);
    Route::post('shares/{shareRequest}/revoke', [ResourceShareController::class, 'revoke']);
    Route::patch('shares/{shareRequest}/permission', [ResourceShareController::class, 'permission']);
    Route::get('collaboration/{type}/{resource}/threads', [CollaborationCommentController::class, 'index']);
    Route::post('collaboration/{type}/{resource}/threads', [CollaborationCommentController::class, 'store']);
    Route::get('collaboration/{type}/{resource}/mention-candidates', [CollaborationCommentController::class, 'candidates']);
    Route::get('collaboration/threads/{thread}', [CollaborationCommentController::class, 'show']);
    Route::get('collaboration/resources/{type}/{resource}/revisions', [ResourceRevisionController::class, 'index']);
    Route::get('collaboration/resources/{type}/{resource}/revisions/{revision}', [ResourceRevisionController::class, 'show']);
    Route::get('collaboration/resources/{type}/{resource}/revision-comparison', [RevisionComparisonController::class, 'compare']);
    Route::get('collaboration/resources/{type}/{resource}/draft', [ResourceDraftController::class, 'show']);
    Route::put('collaboration/resources/{type}/{resource}/draft', [ResourceDraftController::class, 'store']);
    Route::post('collaboration/resources/{type}/{resource}/draft/apply', [ResourceDraftController::class, 'apply']);
    Route::delete('collaboration/resources/{type}/{resource}/draft', [ResourceDraftController::class, 'destroy']);
    Route::get('collaboration/resources/{type}/{resource}/revisions/{revision}/compare-previous', [RevisionComparisonController::class, 'previous']);
    Route::get('changes', [PullUpdateController::class, 'changes']);
    Route::get('collaboration/resources/{type}/{resource}/revision-state', [PullUpdateController::class, 'state']);
    Route::get('collaboration/resources/{type}/{resource}/review-changes', [PullUpdateController::class, 'review']);
    Route::post('collaboration/resources/{type}/{resource}/pull', [PullUpdateController::class, 'pull']);
    Route::post('collaboration/resources/{type}/{resource}/ignore', [PullUpdateController::class, 'ignore']);
    Route::get('collaboration/resources/{type}/{resource}/reminder', [RevisionReminderController::class, 'show']);
    Route::post('collaboration/resources/{type}/{resource}/reminder', [RevisionReminderController::class, 'store']);
    Route::delete('collaboration/resources/{type}/{resource}/reminder', [RevisionReminderController::class, 'destroy']);
    Route::post('collaboration/threads/{thread}/comments', [CollaborationCommentController::class, 'reply']);
    Route::post('collaboration/threads/{thread}/acknowledge', [CollaborationCommentController::class, 'acknowledge']);
    Route::post('collaboration/threads/{thread}/resolve', [CollaborationCommentController::class, 'resolve']);
    Route::post('collaboration/threads/{thread}/reopen', [CollaborationCommentController::class, 'reopen']);
    Route::patch('collaboration/comments/{comment}', [CollaborationCommentController::class, 'update']);
    Route::get('devices', [DeviceController::class, 'index']);
    Route::post('devices', [DeviceController::class, 'store']);
    Route::get('devices/{device}', [DeviceController::class, 'show']);
    Route::get('devices/{device}/dashboard', [DeviceDashboardController::class, 'show']);
    Route::patch('devices/{device}/dashboard', [DeviceDashboardController::class, 'update']);
    Route::get('device-credentials', [DeviceCredentialController::class, 'all']);
    Route::get('devices/{device}/credentials', [DeviceCredentialController::class, 'index']);
    Route::post('devices/{device}/credentials', [DeviceCredentialController::class, 'store']);
    Route::post('devices/{device}/credentials/{credential}/revoke', [DeviceCredentialController::class, 'revoke']);
    Route::patch('devices/{device}', [DeviceController::class, 'update']);
    Route::put('devices/{device}', [DeviceController::class, 'update']);
    Route::delete('devices/{device}', [DeviceController::class, 'destroy']);
    Route::get('devices/{device}/snapshots', [DeviceSnapshotController::class, 'index']);
    Route::post('devices/{device}/snapshots', [DeviceSnapshotController::class, 'store']);
    Route::get('devices/{device}/snapshots/{snapshot}', [DeviceSnapshotController::class, 'show']);
    Route::post('devices/{device}/snapshots/compare', [DeviceSnapshotController::class, 'compare']);
    Route::get('devices/{device}/parameters', [DeviceParameterController::class, 'index']);
    Route::post('devices/{device}/parameters', [DeviceParameterController::class, 'store']);
    Route::patch('devices/{device}/parameters/{parameter}', [DeviceParameterController::class, 'update']);
    Route::delete('devices/{device}/parameters/{parameter}', [DeviceParameterController::class, 'destroy']);
    Route::get('device-templates/published', [TemplatePublicationController::class, 'catalog']);
    Route::get('device-templates/published/{template}', [TemplatePublicationController::class, 'published']);
    Route::get('device-templates', [DeviceTemplateController::class, 'index']);
    Route::post('device-templates', [DeviceTemplateController::class, 'store']);
    Route::get('device-templates/{template}', [DeviceTemplateController::class, 'show']);
    Route::patch('device-templates/{template}', [DeviceTemplateController::class, 'update']);
    Route::delete('device-templates/{template}', [DeviceTemplateController::class, 'destroy']);
    Route::post('device-templates/{template}/duplicate', [DeviceTemplateController::class, 'duplicate']);
    Route::post('device-templates/{template}/parameters', [DeviceTemplateController::class, 'addParameter']);
    Route::patch('device-templates/{template}/parameters/{parameter}', [DeviceTemplateController::class, 'updateParameter']);
    Route::delete('device-templates/{template}/parameters/{parameter}', [DeviceTemplateController::class, 'deleteParameter']);
    Route::post('device-templates/{template}/metadata', [DeviceTemplateController::class, 'addMetadata']);
    Route::post('device-templates/{template}/events', [DeviceTemplateController::class, 'addEvent']);
    Route::patch('device-templates/{template}/metadata/{definition}', [DeviceTemplateController::class, 'updateMetadata']);
    Route::patch('device-templates/{template}/events/{definition}', [DeviceTemplateController::class, 'updateEvent']);
    Route::get('device-templates/{template}/dashboard', [DeviceTemplateController::class, 'dashboard']);
    Route::patch('device-templates/{template}/dashboard', [DeviceTemplateController::class, 'updateDashboard']);
    Route::post('device-templates/{template}/devices', [DeviceTemplateController::class, 'createDevice']);
    Route::get('device-templates/{template}/publication', [TemplatePublicationController::class, 'state']);
    Route::get('device-templates/{template}/publication/versions', [TemplatePublicationVersionController::class, 'index']);
    Route::get('device-templates/{template}/publication/versions/{version}', [TemplatePublicationVersionController::class, 'show']);
    Route::get('device-templates/{template}/review-history', [TemplatePublicationController::class, 'history']);
    Route::post('device-templates/{template}/publication-submissions', [TemplatePublicationController::class, 'submit']);
    Route::post('devices/{device}/apply-template', [DeviceTemplateController::class, 'apply']);
    Route::get('operational-events', [OperationalEventController::class, 'index']);
    Route::get('operational-events/{event}', [OperationalEventController::class, 'show']);
    Route::get('fleet/devices', [FleetController::class, 'index']);
    Route::get('firmware/artifacts', [FirmwareArtifactController::class, 'index']);
    Route::post('firmware/artifacts', [FirmwareArtifactController::class, 'store']);
    Route::get('firmware/artifacts/{artifact}', [FirmwareArtifactController::class, 'show']);
    Route::patch('firmware/artifacts/{artifact}', [FirmwareArtifactController::class, 'update']);
    Route::get('firmware/artifacts/{artifact}/download', [FirmwareArtifactController::class, 'download']);
    Route::delete('firmware/artifacts/{artifact}', [FirmwareArtifactController::class, 'destroy']);
    Route::get('firmware/artifacts/{artifact}/release', [FirmwareReleaseController::class, 'state']);
    Route::post('firmware/artifacts/{artifact}/release-submissions', [FirmwareReleaseController::class, 'submit']);
    Route::get('firmware/artifacts/{artifact}/releases', [FirmwareReleaseController::class, 'history']);
    Route::get('firmware/deployments', [FirmwareDeploymentController::class, 'index']);
    Route::post('firmware/deployments', [FirmwareDeploymentController::class, 'store']);
    Route::get('firmware/deployments/{deployment}', [FirmwareDeploymentController::class, 'show']);
    Route::get('provisioning-sessions', [ProvisioningSessionController::class, 'index']);
    Route::post('provisioning-sessions', [ProvisioningSessionController::class, 'store']);
    Route::get('provisioning-sessions/{session}', [ProvisioningSessionController::class, 'show']);
    Route::post('provisioning-sessions/{session}/cancel', [ProvisioningSessionController::class, 'cancel']);
    Route::post('provisioning-sessions/{session}/fail', [ProvisioningSessionController::class, 'fail']);
    Route::post('provisioning-sessions/{session}/complete', [ProvisioningSessionController::class, 'complete']);
    Route::get('locations', [LocationController::class, 'index']);
    Route::post('locations', [LocationController::class, 'store']);
    Route::get('locations/{location}', [LocationController::class, 'show']);
    Route::patch('locations/{location}', [LocationController::class, 'update']);
    Route::get('locations/{location}/devices', [LocationController::class, 'devices']);
    Route::get('webhooks', [WebhookController::class, 'index']);
    Route::post('webhooks', [WebhookController::class, 'store']);
    Route::get('webhooks/{webhook}', [WebhookController::class, 'show']);
    Route::patch('webhooks/{webhook}', [WebhookController::class, 'update']);
    Route::delete('webhooks/{webhook}', [WebhookController::class, 'destroy']);
    Route::post('webhooks/{webhook}/rotate-secret', [WebhookController::class, 'rotate']);
    Route::post('webhooks/{webhook}/test', [WebhookController::class, 'test']);
    Route::get('webhooks/{webhook}/activation', [WebhookActivationController::class, 'state']);
    Route::post('webhooks/{webhook}/activation-submissions', [WebhookActivationController::class, 'submit']);
    Route::post('webhooks/{webhook}/activate', [WebhookActivationController::class, 'activate']);
    Route::post('webhooks/{webhook}/deactivate', [WebhookActivationController::class, 'deactivate']);
    Route::get('webhooks/{webhook}/deliveries', [WebhookDeliveryController::class, 'index']);
    Route::post('webhooks/{webhook}/deliveries/{delivery}/retry', [WebhookDeliveryController::class, 'retry']);
    Route::get('crash-reports', [CrashReportController::class, 'index']);
    Route::get('crash-reports/{crashReport}', [CrashReportController::class, 'show']);
    Route::get('reports/published/catalog', [ReportPublicationController::class, 'catalog']);
    Route::get('reports/published/{report}', [ReportPublicationController::class, 'published']);
    Route::post('reports/published/{report}/runs', [ReportPublicationController::class, 'run']);
    Route::get('reports/{report}/publication', [ReportPublicationController::class, 'state']);
    Route::post('reports/{report}/publication-submissions', [ReportPublicationController::class, 'submit']);
    Route::get('reports/{report}/review-history', [ReportPublicationController::class, 'history']);
    Route::get('reports/{report}/publication/versions', [ReportPublicationController::class, 'versions']);
    Route::get('reports', [ReportController::class, 'index']);
    Route::post('reports', [ReportController::class, 'store']);
    Route::get('reports/{report}', [ReportController::class, 'show']);
    Route::patch('reports/{report}', [ReportController::class, 'update']);
    Route::delete('reports/{report}', [ReportController::class, 'destroy']);
    Route::post('reports/{report}/runs', [ReportRunController::class, 'store']);
    Route::get('reports/{report}/runs', [ReportRunController::class, 'index']);
    Route::get('reports/{report}/runs/{run}', [ReportRunController::class, 'show']);
    Route::get('reports/{report}/runs/{run}/download', [ReportRunController::class, 'download']);
    Route::get('dashboards/published/catalog', [DashboardPublicationController::class, 'catalog']);
    Route::get('dashboards/published/{dashboard}', [DashboardPublicationController::class, 'published']);
    Route::get('dashboards', [DashboardController::class, 'index']);
    Route::get('dashboards/default', [DashboardController::class, 'default']);
    Route::post('dashboards', [DashboardController::class, 'store']);
    Route::get('dashboards/{dashboard}', [DashboardController::class, 'show']);
    Route::post('dashboards/{dashboard}/map-assets', [DashboardMapAssetController::class, 'store']);
    Route::get('dashboards/{dashboard}/map-projection', [DashboardMapProjectionController::class, 'show']);
    Route::get('dashboard-map-assets/{asset}', [DashboardMapAssetController::class, 'show']);
    Route::get('dashboards/{dashboard}/shares', [DashboardController::class, 'shares']);
    Route::get('dashboards/{dashboard}/publication', [DashboardPublicationController::class, 'state']);
    Route::post('dashboards/{dashboard}/publication-submissions', [DashboardPublicationController::class, 'submit']);
    Route::get('dashboards/{dashboard}/publication/history', [DashboardPublicationController::class, 'history']);
    Route::get('dashboards/{dashboard}/publication/versions', [DashboardPublicationController::class, 'versions']);
    Route::put('dashboards/{dashboard}', [DashboardController::class, 'update']);
    Route::patch('dashboards/{dashboard}', [DashboardController::class, 'update']);
    Route::delete('dashboards/{dashboard}', [DashboardController::class, 'destroy']);
    Route::post('dashboards/{dashboard}/duplicate', [DashboardController::class, 'duplicate']);
    Route::get('resources/{type}/{id}/attention', [ResourceAttentionController::class, 'show']);
    Route::get('resources/{type}/{id}/lifecycle', [ResourceLifecycleController::class, 'show']);
    Route::get('my-work/needs-attention', [ResourceAttentionController::class, 'myWork']);
    Route::middleware('admin')->prefix('admin')->group(function () {
        Route::get('locations', [AdminLocationController::class, 'index']);
        Route::post('locations', [AdminLocationController::class, 'store']);
        Route::get('locations/{location}', [AdminLocationController::class, 'show']);
        Route::patch('locations/{location}', [AdminLocationController::class, 'update']);
        Route::get('locations/{location}/devices', [AdminLocationController::class, 'devices']);
        Route::get('reviews/summary', [AdminReviewCenterController::class, 'summary']);
        Route::get('reviews', [AdminReviewCenterController::class, 'index']);
        Route::get('reviews/{resourceType}/{submission}', [AdminReviewCenterController::class, 'show']);
        Route::get('recently-created', [AdminRecentResourceController::class, 'created']);
        Route::get('recently-updated', [AdminRecentResourceController::class, 'updated']);
        Route::get('disabled-resources/summary', [AdminDisabledResourceController::class, 'summary']);
        Route::get('disabled-resources', [AdminDisabledResourceController::class, 'index']);
        Route::get('resources/inventory/metadata', [AdminResourceInventoryController::class, 'metadata']);
        Route::get('resources/inventory', [AdminResourceInventoryController::class, 'index']);
        Route::get('resources/inventory/{type}/{id}', [AdminResourceInventoryController::class, 'show']);
        Route::post('resources/inventory/{type}/{id}/viewed', [AdminResourceViewController::class, 'store']);
        Route::get('needs-attention', [ResourceAttentionController::class, 'index']);
        Route::get('needs-attention/count', [ResourceAttentionController::class, 'count']);
        Route::post('resources/{type}/{id}/attention', [ResourceAttentionController::class, 'mark']);
        Route::patch('resources/{type}/{id}/attention', [ResourceAttentionController::class, 'update']);
        Route::post('resources/{type}/{id}/attention/clear', [ResourceAttentionController::class, 'clear']);
        Route::post('resources/{type}/{id}/lifecycle/disable', [ResourceLifecycleController::class, 'disable']);
        Route::post('resources/{type}/{id}/lifecycle/restore', [ResourceLifecycleController::class, 'restore']);
        Route::post('resources/{type}/{id}/lifecycle/archive', [ResourceLifecycleController::class, 'archive']);
        Route::get('webhook-activation-submissions/{s}', [WebhookActivationReviewController::class, 'show']);
        Route::get('webhook-activation-submissions/{s}/history', [WebhookActivationReviewController::class, 'history']);
        Route::post('webhook-activation-submissions/{s}/claim', [WebhookActivationReviewController::class, 'claim']);
        Route::post('webhook-activation-submissions/{s}/release', [WebhookActivationReviewController::class, 'release']);
        Route::post('webhook-activation-submissions/{s}/takeover', [WebhookActivationReviewController::class, 'takeover']);
        Route::post('webhook-activation-submissions/{s}/approve', [WebhookActivationReviewController::class, 'approve']);
        Route::post('webhook-activation-submissions/{s}/request-changes', [WebhookActivationReviewController::class, 'requestChanges']);
        Route::post('webhook-activation-submissions/{s}/reject', [WebhookActivationReviewController::class, 'reject']);
        Route::get('firmware-submissions/{submission}', [FirmwareReleaseReviewController::class, 'show']);
        Route::get('firmware-submissions/{submission}/history', [FirmwareReleaseReviewController::class, 'history']);
        Route::post('firmware-submissions/{submission}/claim', [FirmwareReleaseReviewController::class, 'claim']);
        Route::post('firmware-submissions/{submission}/release', [FirmwareReleaseReviewController::class, 'release']);
        Route::post('firmware-submissions/{submission}/takeover', [FirmwareReleaseReviewController::class, 'takeover']);
        Route::post('firmware-submissions/{submission}/approve', [FirmwareReleaseReviewController::class, 'approve']);
        Route::post('firmware-submissions/{submission}/request-changes', [FirmwareReleaseReviewController::class, 'requestChanges']);
        Route::post('firmware-submissions/{submission}/reject', [FirmwareReleaseReviewController::class, 'reject']);
        Route::get('dashboard-publication-submissions', [DashboardPublicationReviewController::class, 'index']);
        Route::get('dashboard-publication-submissions/{submission}', [DashboardPublicationReviewController::class, 'show']);
        Route::get('dashboard-publication-submissions/{submission}/history', [DashboardPublicationReviewController::class, 'history']);
        Route::post('dashboard-publication-submissions/{submission}/claim', [DashboardPublicationReviewController::class, 'claim']);
        Route::post('dashboard-publication-submissions/{submission}/release', [DashboardPublicationReviewController::class, 'release']);
        Route::post('dashboard-publication-submissions/{submission}/takeover', [DashboardPublicationReviewController::class, 'takeover']);
        Route::post('dashboard-publication-submissions/{submission}/approve', [DashboardPublicationReviewController::class, 'approve']);
        Route::post('dashboard-publication-submissions/{submission}/request-changes', [DashboardPublicationReviewController::class, 'requestChanges']);
        Route::post('dashboard-publication-submissions/{submission}/reject', [DashboardPublicationReviewController::class, 'reject']);
        Route::get('template-publication-submissions', [TemplatePublicationReviewController::class, 'index']);
        Route::get('template-publication-submissions/{submission}', [TemplatePublicationReviewController::class, 'show']);
        Route::get('template-publication-submissions/{submission}/history', [TemplatePublicationReviewController::class, 'history']);
        Route::post('template-publication-submissions/{submission}/approve', [TemplatePublicationReviewController::class, 'approve']);
        Route::post('template-publication-submissions/{submission}/request-changes', [TemplatePublicationReviewController::class, 'requestChanges']);
        Route::post('template-publication-submissions/{submission}/reject', [TemplatePublicationReviewController::class, 'reject']);
        Route::post('template-publication-submissions/{submission}/claim', [TemplatePublicationReviewController::class, 'claim']);
        Route::post('template-publication-submissions/{submission}/release', [TemplatePublicationReviewController::class, 'release']);
        Route::post('template-publication-submissions/{submission}/takeover', [TemplatePublicationReviewController::class, 'takeover']);
        Route::get('automation-publication-submissions', [AutomationPublicationReviewController::class, 'index']);
        Route::get('automation-publication-submissions/{submission}', [AutomationPublicationReviewController::class, 'show']);
        Route::get('automation-publication-submissions/{submission}/history', [AutomationPublicationReviewController::class, 'history']);
        Route::post('automation-publication-submissions/{s}/approve', [AutomationPublicationReviewController::class, 'approve']);
        Route::post('automation-publication-submissions/{s}/request-changes', [AutomationPublicationReviewController::class, 'requestChanges']);
        Route::post('automation-publication-submissions/{s}/reject', [AutomationPublicationReviewController::class, 'reject']);
        Route::post('automation-publication-submissions/{s}/claim', [AutomationPublicationReviewController::class, 'claim']);
        Route::post('automation-publication-submissions/{s}/release', [AutomationPublicationReviewController::class, 'release']);
        Route::post('automation-publication-submissions/{s}/takeover', [AutomationPublicationReviewController::class, 'takeover']);
        Route::get('report-publication-submissions', [ReportPublicationReviewController::class, 'index']);
        Route::get('report-publication-submissions/{submission}', [ReportPublicationReviewController::class, 'show']);
        Route::get('report-publication-submissions/{submission}/history', [ReportPublicationReviewController::class, 'history']);
        Route::post('report-publication-submissions/{s}/approve', [ReportPublicationReviewController::class, 'approve']);
        Route::post('report-publication-submissions/{s}/request-changes', [ReportPublicationReviewController::class, 'requestChanges']);
        Route::post('report-publication-submissions/{s}/reject', [ReportPublicationReviewController::class, 'reject']);
        Route::post('report-publication-submissions/{s}/claim', [ReportPublicationReviewController::class, 'claim']);
        Route::post('report-publication-submissions/{s}/release', [ReportPublicationReviewController::class, 'release']);
        Route::post('report-publication-submissions/{s}/takeover', [ReportPublicationReviewController::class, 'takeover']);
        Route::get('access-requests', [AccessRequestController::class, 'index']);
        Route::post('access-requests/{shareRequest}/approve', [AccessRequestController::class, 'approve']);
        Route::post('access-requests/{shareRequest}/reject', [AccessRequestController::class, 'reject']);
        Route::get('devices/{device}/dashboard', [DeviceDashboardController::class, 'adminShow']);
        Route::patch('devices/{device}/dashboard', [DeviceDashboardController::class, 'adminUpdate']);
        Route::get('dashboards/global', [DashboardController::class, 'globalDefault']);
        Route::put('dashboards/global', [DashboardController::class, 'globalUpdate']);
        Route::get('system-settings', [SystemSettingController::class, 'index']);
        Route::patch('system-settings/{key}', [SystemSettingController::class, 'update']);
        Route::post('system-settings/{key}/reset', [SystemSettingController::class, 'reset']);
        Route::get('crash-reports', [AdminCrashReportController::class, 'index']);
        Route::get('crash-reports/{crashReport}', [AdminCrashReportController::class, 'show']);
        Route::get('operational-events', [AdminOperationalEventController::class, 'index']);
        Route::get('operational-events/{event}', [AdminOperationalEventController::class, 'show']);
        Route::get('provisioning-sessions', [AdminProvisioningSessionController::class, 'index']);
        Route::get('provisioning-sessions/{session}', [AdminProvisioningSessionController::class, 'show']);
        Route::get('operations/overview', [AdminGlobalOperationsController::class, 'overview']);
        Route::get('monitored-devices', [AdminMonitoredDeviceController::class, 'index']);
        Route::post('monitored-devices', [AdminMonitoredDeviceController::class, 'store']);
        Route::delete('monitored-devices/{device}', [AdminMonitoredDeviceController::class, 'destroy']);
        Route::get('devices', [AdminGlobalDeviceController::class, 'index']);
        Route::post('devices', [AdminGlobalDeviceController::class, 'store']);
        Route::get('organizations', [AdminController::class, 'organizations']);
        Route::patch('organizations/{organization}/status', [AdminController::class, 'organizationStatus']);
        Route::get('users', [AdminController::class, 'users']);
        Route::get('users/options', [DeviceAccessController::class, 'userOptions']);
        Route::get('users/{user}', [AdminController::class, 'showUser']);
        Route::post('users', [AdminController::class, 'store']);
        Route::patch('users/{user}/status', [AdminController::class, 'userStatus']);
        Route::get('devices/options', [DeviceAccessController::class, 'deviceOptions']);
        Route::get('devices/{device}', [AdminGlobalDeviceController::class, 'show']);
        Route::get('devices/{device}/credentials', [AdminDeviceCredentialController::class, 'index']);
        Route::get('devices/{device}/snapshots', [AdminDeviceSnapshotController::class, 'index']);
        Route::post('devices/{device}/snapshots', [AdminDeviceSnapshotController::class, 'store']);
        Route::get('devices/{device}/snapshots/{snapshot}', [AdminDeviceSnapshotController::class, 'show']);
        Route::post('devices/{device}/snapshots/compare', [AdminDeviceSnapshotController::class, 'compare']);
        Route::post('devices/{device}/credentials', [AdminDeviceCredentialController::class, 'store']);
        Route::post('devices/{device}/credentials/{credential}/revoke', [AdminDeviceCredentialController::class, 'revoke']);
        Route::patch('devices/{device}', [AdminGlobalDeviceController::class, 'update']);
        Route::get('devices/{device}/parameters', [AdminDeviceParameterController::class, 'index']);
        Route::post('devices/{device}/parameters', [AdminDeviceParameterController::class, 'store']);
        Route::patch('devices/{device}/parameters/{parameter}', [AdminDeviceParameterController::class, 'update']);
        Route::delete('devices/{device}/parameters/{parameter}', [AdminDeviceParameterController::class, 'destroy']);
        Route::get('device-templates', [AdminDeviceTemplateController::class, 'index']);
        Route::post('device-templates', [AdminDeviceTemplateController::class, 'store']);
        Route::get('device-templates/{template}', [AdminDeviceTemplateController::class, 'show']);
        Route::patch('device-templates/{template}', [AdminDeviceTemplateController::class, 'update']);
        Route::delete('device-templates/{template}', [AdminDeviceTemplateController::class, 'destroy']);
        Route::post('device-templates/{template}/duplicate', [AdminDeviceTemplateController::class, 'duplicate']);
        Route::post('device-templates/{template}/parameters', [AdminDeviceTemplateController::class, 'addParameter']);
        Route::patch('device-templates/{template}/parameters/{parameter}', [AdminDeviceTemplateController::class, 'updateParameter']);
        Route::delete('device-templates/{template}/parameters/{parameter}', [AdminDeviceTemplateController::class, 'deleteParameter']);
        Route::post('devices/{device}/apply-template', [AdminDeviceTemplateController::class, 'apply']);
        Route::get('device-access', [DeviceAccessController::class, 'index']);
        Route::post('device-access', [DeviceAccessController::class, 'store']);
        Route::patch('device-access/{assignment}', [DeviceAccessController::class, 'update']);
        Route::delete('device-access/{assignment}', [DeviceAccessController::class, 'destroy']);
        Route::get('devices/{device}/access', [DeviceAccessController::class, 'deviceAccess']);
        Route::get('users/{user}/device-access', [DeviceAccessController::class, 'userDeviceAccess']);
    });
});
Route::middleware(['auth:sanctum', 'active'])->group(function () {
    Route::get('resources/{type}/{resource}/editing-sessions', [ResourceEditingSessionController::class, 'index']);
    Route::post('resources/{type}/{resource}/editing-sessions', [ResourceEditingSessionController::class, 'store']);
    Route::post('resources/{type}/{resource}/editing-sessions/{session}/heartbeat', [ResourceEditingSessionController::class, 'heartbeat']);
    Route::delete('resources/{type}/{resource}/editing-sessions/{session}', [ResourceEditingSessionController::class, 'destroy']);
});
