export type ResourceTabType="device"|"location";
export type ResourceTabCapability="edit"|"dashboard.edit"|"parameters.edit"|"credentials.manage"|"analytics.view";
export interface ResourceTabDefinition{key:string;label:string;classification:"config"|"runtime"|"collaboration"|"history"|"security";capability?:ResourceTabCapability;appOnly?:boolean}
export interface ResourceTabContext{admin:boolean;capabilities:Partial<Record<ResourceTabCapability,boolean>>}
export const resourceTabRegistry:Record<ResourceTabType,{defaultKey:string;tabs:ResourceTabDefinition[]}>= {
 device:{defaultKey:"overview",tabs:[{key:"overview",label:"Overview",classification:"config"},{key:"dashboard",label:"Dashboard",classification:"config"},{key:"parameters",label:"Parameters",classification:"config"},{key:"metadata",label:"Metadata",classification:"config"},{key:"events",label:"Events",classification:"runtime"},{key:"comments",label:"Comments",classification:"collaboration"},{key:"revisions",label:"Revisions",classification:"history"},{key:"telemetry",label:"Telemetry",classification:"runtime",capability:"analytics.view",appOnly:true},{key:"analytics",label:"Analytics",classification:"runtime",capability:"analytics.view",appOnly:true},{key:"configuration",label:"Configuration",classification:"config",capability:"edit",appOnly:true},{key:"snapshots",label:"Snapshots",classification:"history",capability:"edit",appOnly:true},{key:"credentials",label:"Credentials",classification:"security",capability:"credentials.manage"},{key:"crashes",label:"Crash Reports",classification:"runtime"}]},
 location:{defaultKey:"overview",tabs:[{key:"overview",label:"Overview",classification:"config"},{key:"comments",label:"Comments",classification:"collaboration"},{key:"revisions",label:"Revisions",classification:"history"}]},
};
export function resolveResourceTabs(type:ResourceTabType,requested:string|null,context:ResourceTabContext){const definition=resourceTabRegistry[type];const visible=definition.tabs.filter(tab=>(!tab.appOnly||!context.admin)&&(!tab.capability||context.capabilities[tab.capability]===true));const active=visible.some(tab=>tab.key===requested)?requested!:visible.find(tab=>tab.key===definition.defaultKey)?.key??visible[0]?.key;return{tabs:visible,activeKey:active,requestedWasValid:requested===null||active===requested}}
