import {ChevronLeft,ChevronRight} from "lucide-react";
import {Link,useLocation} from "react-router-dom";
import {primaryNavigationSectionLabels,routeMatches,type PrimaryNavigationItem} from "../../navigation/app-navigation";

export default function PrimarySidebar({items,collapsed=false,onToggle,onNavigate,homePath="/app/dashboard"}:{items:PrimaryNavigationItem[];collapsed?:boolean;onToggle?:()=>void;onNavigate?:()=>void;homePath?:string}){
 const {pathname}=useLocation();
 const sections=Array.from(new Set(items.map(entry=>entry.section)));
 return <aside aria-label="Primary navigation" className="flex h-full flex-col border-r border-[var(--ds-border-subtle)] bg-[var(--ds-surface)] text-[var(--ds-text)]">
  <div className={`flex h-14 shrink-0 items-center border-b border-[var(--ds-border-subtle)] ${collapsed?"justify-center gap-0.5 px-1":"gap-2 px-3"}`}><Link to={homePath} onClick={onNavigate} aria-label="IoT Platform home" title={collapsed?"IoT Platform":undefined} className="flex min-w-0 items-center gap-2.5 overflow-hidden"><span className={`${collapsed?"h-7 w-7 text-xs":"h-8 w-8"} grid shrink-0 place-items-center rounded-[8px] bg-[var(--ds-primary-hover)] text-white`}>I</span>{!collapsed&&<span className="truncate whitespace-nowrap text-xs font-bold tracking-[0.12em]">IOT PLATFORM</span>}</Link>{onToggle&&<button type="button" aria-label={collapsed?"Expand primary navigation":"Collapse primary navigation"} aria-expanded={!collapsed} onClick={onToggle} title={collapsed?"Expand navigation":"Collapse navigation"} className={`${collapsed?"h-7 w-7":"h-8 w-8"} grid shrink-0 place-items-center rounded-[8px] text-[var(--ds-text-muted)] hover:bg-white/[.05] hover:text-[var(--ds-text)] focus-visible:ring-2 focus-visible:ring-[var(--ds-focus)]`}>{collapsed?<ChevronRight size={15}/>:<ChevronLeft size={15}/>}</button>}</div>
  <nav aria-label="Platform areas" className="flex-1 overflow-y-auto p-2">{sections.map((section,index)=><section key={section} aria-labelledby={collapsed?undefined:`primary-${section}`} className={index?"mt-3":""}>{!collapsed&&<h2 id={`primary-${section}`} className="mb-1 px-2 text-[10px] font-semibold uppercase tracking-wide text-[var(--ds-text-subtle)]">{primaryNavigationSectionLabels[section]}</h2>}<div className="space-y-1">{items.filter(entry=>entry.section===section).map(entry=>{const Icon=entry.icon;const active=routeMatches(pathname,entry.matches);return <Link key={entry.id} to={entry.path} onClick={onNavigate} aria-current={active?"page":undefined} aria-label={collapsed?entry.label:undefined} title={collapsed?entry.label:undefined} className={`flex min-h-10 items-center gap-2.5 rounded-[8px] px-2.5 text-xs font-medium transition focus-visible:ring-2 focus-visible:ring-[var(--ds-focus)] ${active?"border-l-2 border-white bg-[var(--ds-primary-hover)] text-white":"text-[var(--ds-text-muted)] hover:bg-white/[.05] hover:text-[var(--ds-text)]"}`}><Icon size={17} aria-hidden="true" className="shrink-0"/>{!collapsed&&<span>{entry.label}</span>}</Link>})}</div></section>)}</nav>
 </aside>;
}
