import {ChevronLeft,ChevronRight} from "lucide-react";
import {Link} from "react-router-dom";
import type {ResolvedSecondaryNavigation} from "../../navigation/secondary-navigation";

export default function SecondarySidebar({resolved,collapsed=false,onToggle,onNavigate}:{resolved:ResolvedSecondaryNavigation;collapsed?:boolean;onToggle?:()=>void;onNavigate?:()=>void}){
 const {context,sections,activeItemId}=resolved;
 if(collapsed)return <aside aria-label={`${context.label} contextual navigation`} className="flex h-full flex-col items-center border-r border-[var(--ds-border-subtle)] bg-[var(--ds-surface-elevated)] py-3"><button type="button" aria-label={`Expand ${context.label} contextual navigation`} aria-expanded="false" onClick={onToggle} title={`Open ${context.label} navigation`} className="grid min-h-10 min-w-10 place-items-center rounded-[8px] text-[var(--ds-text-muted)] hover:bg-white/[.05] focus-visible:ring-2 focus-visible:ring-[var(--ds-focus)]"><ChevronRight size={16} aria-hidden="true"/></button></aside>;
 return <aside aria-label={`${context.label} contextual navigation`} className="flex h-full flex-col border-r border-[var(--ds-border-subtle)] bg-[var(--ds-surface-elevated)]"><div className="flex h-14 items-center gap-2 border-b border-[var(--ds-border-subtle)] px-3"><div className="min-w-0"><p className="text-[10px] uppercase tracking-[0.14em] text-[var(--ds-text-subtle)]">Current area</p><p className="truncate text-sm font-semibold">{context.label}</p></div>{onToggle&&<button type="button" aria-label={`Collapse ${context.label} contextual navigation`} aria-expanded="true" onClick={onToggle} title={`Collapse ${context.label} navigation`} className="grid h-8 w-8 shrink-0 place-items-center rounded-[8px] text-[var(--ds-text-muted)] hover:bg-white/[.05] hover:text-[var(--ds-text)] focus-visible:ring-2 focus-visible:ring-[var(--ds-focus)]"><ChevronLeft size={15} aria-hidden="true"/></button>}</div><nav aria-label={`${context.label} contextual pages`} className="flex-1 space-y-5 overflow-y-auto p-3">{sections.map(section=><section key={section.id} aria-labelledby={`secondary-${context.key}-${section.id}`}><h2 id={`secondary-${context.key}-${section.id}`} className="mb-2 px-2 text-[10px] font-semibold uppercase tracking-[0.14em] text-[var(--ds-text-subtle)]">{section.label}</h2><div className="space-y-1">{section.items.map(entry=>{const Icon=entry.icon;const active=activeItemId===entry.id;return <Link key={entry.id} to={entry.path} onClick={onNavigate} aria-current={active?"page":undefined} className={`flex min-h-10 items-center gap-2 rounded-[8px] px-2.5 text-xs focus-visible:ring-2 focus-visible:ring-[var(--ds-focus)] ${active?"border-l-2 border-[var(--ds-primary)] bg-white/[.08] text-[var(--ds-text)]":"text-[var(--ds-text-muted)] hover:bg-white/[.05] hover:text-[var(--ds-text)]"}`}><Icon size={15} aria-hidden="true"/><span className="flex-1">{entry.label}</span></Link>})}</div></section>)}</nav></aside>;
}
