import {useEffect,useMemo,useState,type ReactNode} from "react";
import {Minus,PanelLeftOpen,PanelRightOpen,Pencil,Save,X} from "lucide-react";
import {Link,useSearchParams} from "react-router-dom";
import type {Dashboard} from "../../types/dashboard";
import {useDashboardStore} from "../../store/dashboard.store";
import {useEditingPresence} from "../../hooks/useEditingPresence";
import DashboardCanvas from "./builder/DashboardCanvas";
import WidgetLibrary from "./builder/WidgetLibrary";
import WidgetSettings from "./builder/WidgetSettings";
import {Button,ErrorState,Input,LoadingState,PageTitle,Select} from "../ui";
import CommentsPanel from "../collaboration/CommentsPanel";
import {useFeedback} from "../../context/FeedbackContext";

interface Props{load:()=>Promise<Dashboard>;save:(d:Dashboard)=>Promise<Dashboard>;fallback?:ReactNode;canEdit?:boolean;deviceId?:string;resourceId?:string;onConflict?:(e:unknown,d:Dashboard)=>void}
export default function DashboardWorkspace({load,save,fallback,canEdit=true,deviceId,resourceId,onConflict}:Props){
 const feedback=useFeedback();
 const[params]=useSearchParams();const[dashboard,setDashboard]=useState<Dashboard|null>(null);const[editing,setEditing]=useState(false);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[error,setError]=useState("");const[baseline,setBaseline]=useState("");const[leftOpen,setLeftOpen]=useState(true);const[rightOpen,setRightOpen]=useState(true);const[timeRange,setTimeRange]=useState<"1h"|"6h"|"24h"|"7d"|"30d">("24h");const widgets=useDashboardStore(s=>s.widgets);const loadWidgets=useDashboardStore(s=>s.loadWidgets);const setGlobalTimeRange=useDashboardStore(s=>s.setTimeRange);const[name,setName]=useState("");const[commentAnchor,setCommentAnchor]=useState<string|null|undefined>(()=>params.get("widget")??(params.get("thread")?null:undefined));
 useEffect(()=>{let active=true;load().then(v=>{if(!active)return;setDashboard(v);setName(v.name);loadWidgets(v.widgets);setBaseline(JSON.stringify(v.widgets))}).catch(()=>{if(active)setError("Dashboard could not be loaded.")}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[load,loadWidgets]);
 const editable=canEdit&&dashboard?.canEdit!==false;const{otherEditors,presenceUnavailable}=useEditingPresence(deviceId?'device':'dashboard',deviceId??resourceId??dashboard?.id,editing&&editable);const dirty=useMemo(()=>editing&&(name!==dashboard?.name||JSON.stringify(widgets)!==baseline),[editing,name,dashboard?.name,widgets,baseline]);
 useEffect(()=>{const warning=(e:BeforeUnloadEvent)=>{if(dirty)e.preventDefault()};window.addEventListener("beforeunload",warning);return()=>window.removeEventListener("beforeunload",warning)},[dirty]);
 useEffect(()=>setGlobalTimeRange(timeRange),[setGlobalTimeRange,timeRange]);
 const cancel=async()=>{if(dirty&&!await feedback.confirm({title:"Discard Dashboard changes?",description:"Your unsaved widget layout and settings will be lost. The last saved Dashboard will remain unchanged.",confirmLabel:"Discard changes",tone:"warning"}))return;if(dashboard){loadWidgets(dashboard.widgets);setName(dashboard.name);setBaseline(JSON.stringify(dashboard.widgets))}setEditing(false)};
 const persist=async()=>{if(!dashboard)return;setSaving(true);setError("");const working={...dashboard,name,widgets};try{const next=await save(working);setDashboard(next);loadWidgets(next.widgets);setBaseline(JSON.stringify(next.widgets));setEditing(false);feedback.notify({tone:"success",title:"Dashboard saved",description:"Widget layout and settings are now up to date."})}catch(reason){const status=(reason as{response?:{status?:number}}).response?.status;if(status===409&&onConflict)onConflict(reason,working);else setError(status===409?"This Dashboard changed while you were editing.":"Dashboard changes were rejected.");feedback.notify({tone:status===409?"warning":"error",title:status===409?"Dashboard changed":"Save failed",description:status===409?"Refresh or resolve the revision conflict before saving again.":"Your changes remain in the editor so you can retry."})}finally{setSaving(false)}};
 if(loading)return <LoadingState label="Loading Dashboard..."/>;if(error&&!dashboard)return <ErrorState description={error}/>;if(!dashboard)return null;
 return <div className="space-y-5"><header className="flex flex-wrap items-end justify-between gap-3"><div>{editing?<Input label="Dashboard name" value={name} onChange={e=>setName(e.target.value)}/>:deviceId||resourceId?<h2 className="text-xl font-semibold tracking-tight text-[var(--ds-text)]">{dashboard.name}</h2>:<PageTitle>{dashboard.name}</PageTitle>}</div><div className="flex flex-wrap items-end gap-2"><Select label="Dashboard range" value={timeRange} onChange={e=>setTimeRange(e.target.value as typeof timeRange)}>{["1h","6h","24h","7d","30d"].map(value=><option key={value}>{value}</option>)}</Select>{editing?<><Button variant="outline" leadingIcon={<X size={14}/>} onClick={cancel}>Cancel</Button><Button leadingIcon={<Save size={14}/>} loading={saving} onClick={()=>void persist()}>Save Dashboard</Button></>:<>{dashboard.canShare&&dashboard.id&&<Link className="inline-flex h-9 items-center rounded-md border border-[var(--ds-border)] px-3 text-sm" to={`/app/dashboard/${dashboard.id}/share`}>Share Dashboard</Link>}{editable&&dashboard.scope==="personal"&&dashboard.id&&<Link className="inline-flex h-9 items-center rounded-md border border-[var(--ds-border)] px-3 text-sm" to={`/app/dashboard/${dashboard.id}/publication`}>Publication</Link>}{(deviceId||resourceId)&&<Button variant="outline" onClick={()=>setCommentAnchor(null)}>Dashboard discussion</Button>}{editable&&<Button leadingIcon={<Pencil size={14}/>} onClick={()=>setEditing(true)}>Customize Dashboard</Button>}</>}</div></header>
 {editing&&otherEditors.length>0&&<p role="status" className="rounded-lg border border-amber-500/40 bg-amber-500/10 p-3 text-sm"><strong>{otherEditors.map(x=>x.user.displayName).join(', ')}</strong> {otherEditors.length===1?'is':'are'} also editing. This advisory warning does not prevent saving; revision checks protect against stale changes.</p>}
 {editing&&presenceUnavailable&&<p role="status" className="text-xs text-[var(--ds-text-muted)]">Editor presence is temporarily unavailable. Saving remains protected by revision checks.</p>}
 {error&&<div role="alert" className="text-sm text-[var(--ds-danger)]">{error}</div>}{editing?<div className="relative min-h-[70vh] rounded-xl border border-[var(--ds-border-subtle)] bg-[radial-gradient(circle_at_1px_1px,var(--ds-border)_1px,transparent_0)] bg-[size:20px_20px] p-2 sm:p-3"><div className="pointer-events-none absolute inset-x-2 top-2 z-30 sm:inset-x-3"><aside className="pointer-events-auto absolute left-0 top-0 w-[min(220px,calc(100vw-2rem))]">{leftOpen?<><button type="button" aria-expanded="true" aria-label="Minimize Widget Box" title="Minimize Widget Box" onClick={()=>setLeftOpen(false)} className="absolute right-3 top-3 z-10 flex h-7 w-7 items-center justify-center rounded-md text-[var(--ds-text-muted)] hover:bg-white/[.06] hover:text-[var(--ds-text)]"><Minus size={16}/></button><div className="max-h-[calc(100vh-8rem)] overflow-auto rounded-lg shadow-2xl"><WidgetLibrary definitions={dashboard.widgetDefinitions??[]} deviceId={deviceId}/></div></>:<button type="button" aria-expanded="false" aria-label="Expand Widget Box" title="Expand Widget Box" onClick={()=>setLeftOpen(true)} className="flex h-11 w-11 items-center justify-center rounded-lg border border-[var(--ds-border)] bg-[var(--ds-surface-raised)] shadow-xl"><PanelLeftOpen size={17}/></button>}</aside><aside className="pointer-events-auto absolute right-0 top-0 w-[min(280px,calc(100vw-2rem))]">{rightOpen?<><button type="button" aria-expanded="true" aria-label="Minimize Widget settings" title="Minimize Widget settings" onClick={()=>setRightOpen(false)} className="absolute right-3 top-3 z-10 flex h-7 w-7 items-center justify-center rounded-md text-[var(--ds-text-muted)] hover:bg-white/[.06] hover:text-[var(--ds-text)]"><Minus size={16}/></button><div className="max-h-[calc(100vh-8rem)] overflow-auto rounded-lg shadow-2xl"><WidgetSettings definitions={dashboard.widgetDefinitions??[]} deviceId={deviceId}/></div></>:<button type="button" aria-expanded="false" aria-label="Expand Widget settings" title="Expand Widget settings" onClick={()=>setRightOpen(true)} className="ml-auto flex h-11 w-11 items-center justify-center rounded-lg border border-[var(--ds-border)] bg-[var(--ds-surface-raised)] shadow-xl"><PanelRightOpen size={17}/></button>}</aside></div><div className="relative z-10 min-w-0"><DashboardCanvas definitions={dashboard.widgetDefinitions??[]} onComment={(deviceId||resourceId)?setCommentAnchor:undefined}/></div></div>:widgets.length?<DashboardCanvas definitions={dashboard.widgetDefinitions??[]} preview onComment={(deviceId||resourceId)?setCommentAnchor:undefined}/>:fallback??<div className="rounded-lg border border-dashed p-10 text-center">No widgets yet.</div>}
 {(deviceId||resourceId)&&commentAnchor!==undefined&&<div className="rounded-lg border border-[var(--ds-border)] p-4"><div className="mb-3 flex items-center justify-between"><p className="text-sm font-semibold">{commentAnchor?"Widget discussion":"Dashboard discussion"}</p><Button size="compact" variant="ghost" onClick={()=>setCommentAnchor(undefined)}>Close comments</Button></div><CommentsPanel resourceId={resourceId??deviceId!} resourceType={resourceId?"dashboard":undefined} canResolve={editable} anchor={commentAnchor?{type:"dashboard_widget",key:commentAnchor}:{type:"resource"}} contextLabel={commentAnchor?widgets.find(w=>w.id===commentAnchor)?.settings.title??"Widget":"Dashboard"}/></div>}
 </div>;
}
