import { useEffect, useState } from "react";
import { Button, Card, CardContent, CardHeader, ErrorState, LoadingState } from "../../ui";
import { getNotificationSettings, resetNotificationSettings, updateNotificationSettings } from "../../../services/profile.service";
import type { NotificationSettings as Settings } from "../../../types/profile";

export default function NotificationSettings(){
 const [settings,setSettings]=useState<Settings|null>(null);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState("");const [saved,setSaved]=useState(false);
 async function load(){setLoading(true);setError("");try{setSettings(await getNotificationSettings())}catch{setError("Notification preferences could not be loaded.")}finally{setLoading(false)}}
 useEffect(()=>{getNotificationSettings().then(setSettings).catch(()=>setError("Notification preferences could not be loaded.")).finally(()=>setLoading(false))},[]);
 function categoryValue(key:string){return settings?.categories.find(category=>category.key===key)?.override??true}
 function setCategory(key:string,value:boolean){if(!settings)return;setSettings({...settings,categories:settings.categories.map(category=>category.key===key?{...category,override:value}:category),rules:settings.rules.map(rule=>rule.category===key&&!rule.mandatory?{...rule,effectiveEnabled:rule.override??value}:rule)})}
 function setRule(key:string,value:boolean){if(!settings)return;setSettings({...settings,rules:settings.rules.map(rule=>rule.key===key?{...rule,override:value,effectiveEnabled:value}:rule)})}
 async function save(){if(!settings)return;setSaving(true);setSaved(false);setError("");try{setSettings(await updateNotificationSettings({categories:Object.fromEntries(settings.categories.filter(x=>x.override!==null).map(x=>[x.key,x.override as boolean])),rules:Object.fromEntries(settings.rules.filter(x=>x.override!==null&&!x.mandatory).map(x=>[x.key,x.override as boolean]))}));setSaved(true)}catch{setError("Notification preferences could not be saved.")}finally{setSaving(false)}}
 async function reset(){setSaving(true);setSaved(false);setError("");try{setSettings(await resetNotificationSettings());setSaved(true)}catch{setError("Notification preferences could not be reset.")}finally{setSaving(false)}}
 if(loading)return <Card><LoadingState label="Loading notification preferences..."/></Card>;if(!settings)return <Card><ErrorState description={error} retry={()=>void load()}/></Card>;
 return <Card><CardHeader title="Notification preferences" description="Control future optional in-app Notifications. Preferences never change access or workflow state."/><CardContent className="space-y-6"><p className="text-sm text-[var(--ds-text-muted)]">Delivery channel: In-app. Explicit reminders remain delivered because they are requests you scheduled.</p>{settings.categories.map(category=><section key={category.key} aria-labelledby={`notification-category-${category.key}`} className="space-y-3"><div className="flex items-center justify-between gap-4"><div><h3 id={`notification-category-${category.key}`} className="font-medium">{category.label}</h3>{category.hasMandatory&&<p className="text-xs text-[var(--ds-text-muted)]">Includes mandatory security or governance messages that are always on.</p>}</div><label className="flex items-center gap-2 text-sm"><span>Optional events</span><input aria-label={`${category.label} optional Notifications`} type="checkbox" checked={categoryValue(category.key)} onChange={event=>setCategory(category.key,event.target.checked)}/></label></div>{settings.rules.filter(rule=>rule.category===category.key).map(rule=><label key={rule.key} className="flex items-start justify-between gap-4 rounded-lg border border-[var(--ds-border-subtle)] p-3"><span><span className="block text-sm font-medium">{rule.label}</span><span className="block text-xs text-[var(--ds-text-muted)]">{rule.description}</span>{rule.mandatory&&<span className="block text-xs font-medium">Always on — {rule.mandatoryReason}</span>}</span><input type="checkbox" aria-label={rule.label} disabled={rule.mandatory} checked={rule.effectiveEnabled} onChange={event=>setRule(rule.key,event.target.checked)}/></label>)}</section>)}{error&&<p role="alert" className="text-sm text-[var(--ds-danger)]">{error}</p>}{saved&&<p role="status" className="text-sm text-[var(--ds-success)]">Preferences saved.</p>}<div className="flex flex-wrap gap-2"><Button onClick={()=>void save()} loading={saving}>Save preferences</Button><Button variant="secondary" onClick={()=>void reset()} disabled={saving}>Reset to defaults</Button></div></CardContent></Card>
}
