import { createContext, useCallback, useContext, useEffect, useMemo, useState } from "react";
import type { ReactNode } from "react";
import { getEntitlements, getSubscription } from "../services/billing.service";
import type { BillingEntitlements, EntitlementCheck, Subscription } from "../types/billing";
import { useAuth } from "./AuthContext";
interface BillingContextType { subscription:Subscription|null;entitlements:BillingEntitlements|null;loading:boolean;refresh():Promise<void>;hasFeature(feature:string):boolean;checkFeature(feature:string):EntitlementCheck;checkDeviceLimit(current:number):EntitlementCheck;checkUserLimit(current:number):EntitlementCheck;checkDashboardLimit(current:number):EntitlementCheck;checkAutomationLimit(current:number):EntitlementCheck; }
const BillingContext=createContext<BillingContextType|undefined>(undefined);
export function BillingProvider({children}:{children:ReactNode}){const {user,loading:authLoading}=useAuth();const [subscription,setSubscription]=useState<Subscription|null>(null);const [entitlements,setEntitlements]=useState<BillingEntitlements|null>(null);const [loading,setLoading]=useState(false);const refresh=useCallback(async()=>{if(!user){setSubscription(null);setEntitlements(null);return;}setLoading(true);try{const [s,e]=await Promise.all([getSubscription(),getEntitlements()]);setSubscription(s);setEntitlements(e);}finally{setLoading(false);}},[user]);useEffect(()=>{if(!authLoading)void refresh();},[authLoading,refresh]);const hasFeature=useCallback((f:string)=>entitlements?.features.includes(f)??false,[entitlements]);const checkFeature=useCallback((f:string):EntitlementCheck=>!subscription||!["active","trialing"].includes(subscription.status)?{allowed:false,reason:"subscription_inactive"}:hasFeature(f)?{allowed:true}:{allowed:false,reason:"feature_not_included"},[subscription,hasFeature]);const limit=useCallback((current:number,max:number):EntitlementCheck=>current>=max?{allowed:false,reason:"limit_reached",limit:max,currentUsage:current}:{allowed:true,limit:max,currentUsage:current},[]);const value=useMemo(()=>({subscription,entitlements,loading:authLoading||loading,refresh,hasFeature,checkFeature,checkDeviceLimit:(n:number)=>limit(n,entitlements?.deviceLimit??0),checkUserLimit:(n:number)=>limit(n,entitlements?.userLimit??0),checkDashboardLimit:(n:number)=>limit(n,entitlements?.dashboardLimit??0),checkAutomationLimit:(n:number)=>limit(n,entitlements?.automationLimit??0)}),[subscription,entitlements,authLoading,loading,refresh,hasFeature,checkFeature,limit]);return <BillingContext.Provider value={value}>{children}</BillingContext.Provider>;}
// eslint-disable-next-line react-refresh/only-export-components
export function useBilling(){const c=useContext(BillingContext);if(!c)throw new Error("BillingProvider missing");return c;}
