<?php
namespace App\Services;
use App\Collaboration\CollaborationResourceRegistry;
use App\Models\{CollaborationComment,CollaborationThreadTransition,ResourcePublicationVersion,ResourceReviewEvent,ResourceRevision,ResourceShareRequest,User};
use Carbon\CarbonImmutable;use Illuminate\Database\Eloquent\Model;use Illuminate\Support\Collection;
final class CollaborationActivityService{
 public function __construct(private CollaborationActivityRegistry $events,private CollaborationResourceRegistry $resources,private ResourceSectionRegistry $sections){}
 public function preview(User$user,int$limit=10):array{return$this->paginate($user,['page'=>1,'per_page'=>min(10,max(1,$limit))])['data']->all();}
 public function previewPersonal(User$user,int$limit=10):array{return$this->paginate($user,['page'=>1,'per_page'=>min(10,max(1,$limit))],true)['data']->all();}
 public function paginate(User $user,array $filters,bool$personalScope=false):array{$page=(int)($filters['page']??1);$per=(int)($filters['per_page']??20);$limit=$page*$per+1;$view=$this->authorized($user,'view',$personalScope);$comment=$this->authorized($user,'comment',$personalScope);$edit=$this->authorized($user,'edit',$personalScope);$share=$this->authorized($user,'share',$personalScope);$candidates=collect()->concat($this->revisions($filters,$limit,$view))->concat($this->comments($filters,$limit,$comment))->concat($this->transitions($filters,$limit,$comment))->concat($this->reviews($filters,$limit,$edit))->concat($this->publications($filters,$limit,$view))->concat($this->shares($filters,$limit,$share));$rows=$candidates->filter(fn($event)=>!($filters['section']??null)||in_array($filters['section'],$event['sectionKeys'],true))->sort(fn($a,$b)=>[$b['occurredAt'],$b['sortId']]<=>[$a['occurredAt'],$a['sortId']])->values();$bounded=$rows->count()>$page*$per;$rows=$rows->take($page*$per+($bounded?1:0));$this->hydrateResources($rows);$actors=User::whereIn('id',$rows->pluck('actorId')->filter()->unique())->get(['id','name','status'])->keyBy('id');$total=$rows->count();return['data'=>$rows->slice(($page-1)*$per,$per)->map(fn($e)=>$this->dto($e,$actors))->values(),'meta'=>['current_page'=>$page,'per_page'=>$per,'total'=>$total,'last_page'=>max($page+(int)$bounded,(int)ceil($total/$per),1),'bounded'=>$bounded]];}
 private function base($q,array $f,string $time='created_at'){if($v=$f['resource_type']??null)$q->where('resource_type',$v);if($v=$f['resource_id']??null)$q->where('resource_id',$v);if($v=$f['date_from']??null)$q->where($time,'>=',$v);if($v=$f['date_to']??null)$q->where($time,'<=',CarbonImmutable::parse($v)->endOfDay());return$q;}
 private function revisions(array$f,int$l,array$a):Collection{if(!$this->cat($f,'changes'))return collect();$q=$this->base(ResourceRevision::query(),$f);$this->allowed($q,$a);if($section=$f['section']??null)$q->whereNotNull('parent_revision_id')->whereJsonContains('changed_sections',$section);return$q->latest('created_at')->limit($l)->get(['id','resource_type','resource_id','revision_number','created_by','created_at','changed_sections','parent_revision_id'])->map(fn($r)=>$this->event("revision:$r->id",'resource.revised',$r->resource_type,$r->resource_id,$r->created_by,$r->created_at,['revisionId'=>(string)$r->id,'revisionNumber'=>$r->revision_number],$r->parent_revision_id?$this->sections->normalize($r->resource_type,$r->changed_sections??[]):[]));}
 private function comments(array$f,int$l,array$a):Collection{if(!$this->cat($f,'comments'))return collect();$q=CollaborationComment::with('thread:id,resource_type,resource_id,anchor_type,anchor_key')->whereHas('thread',function($t)use($a,$f){$this->allowed($t,$a);if($section=$f['section']??null)$t->whereIn('anchor_type',$this->anchorTypes($f['resource_type'],$section));})->latest('created_at')->limit($l);$this->dates($q,$f);return$q->get(['id','thread_id','parent_comment_id','created_by','created_at'])->filter(fn($c)=>$c->thread&&(!($f['resource_type']??null)||$c->thread->resource_type===$f['resource_type'])&&(!($f['resource_id']??null)||(int)$c->thread->resource_id===(int)$f['resource_id']))->map(fn($c)=>$this->event("comment:$c->id",$c->parent_comment_id?'comment.replied':'comment.created',$c->thread->resource_type,$c->thread->resource_id,$c->created_by,$c->created_at,['threadId'=>(string)$c->thread_id,'commentId'=>(string)$c->id],$this->sections->mapAnchor($c->thread->resource_type,$c->thread->anchor_type)));}
 private function transitions(array$f,int$l,array$a):Collection{if(!$this->cat($f,'comments'))return collect();$q=CollaborationThreadTransition::with('thread:id,resource_type,resource_id,anchor_type,anchor_key')->whereHas('thread',function($t)use($a,$f){$this->allowed($t,$a);if($section=$f['section']??null)$t->whereIn('anchor_type',$this->anchorTypes($f['resource_type'],$section));})->latest('created_at')->limit($l);$this->dates($q,$f);return$q->get()->filter(fn($t)=>$t->thread&&in_array($t->to_status,['resolved','open'],true)&&(!($f['resource_type']??null)||$t->thread->resource_type===$f['resource_type'])&&(!($f['resource_id']??null)||(int)$t->thread->resource_id===(int)$f['resource_id']))->map(fn($t)=>$this->event("thread-transition:$t->id",$t->to_status==='resolved'?'comment.resolved':'comment.reopened',$t->thread->resource_type,$t->thread->resource_id,$t->actor_id,$t->created_at,['threadId'=>(string)$t->thread_id],$this->sections->mapAnchor($t->thread->resource_type,$t->thread->anchor_type)));}
 private function reviews(array$f,int$l,array$a):Collection{if(!$this->cat($f,'review'))return collect();$q=$this->base(ResourceReviewEvent::query(),$f);$this->allowed($q,$a);return$q->whereIn('event_type',ReviewHistoryService::ACTIVE_TYPES)->latest('created_at')->limit($l)->get(['id','resource_type','resource_id','event_type','actor_id','resource_revision_id','created_at'])->map(fn($e)=>$this->event("review:$e->id",$e->event_type,$e->resource_type,$e->resource_id,$e->actor_id,$e->created_at,['revisionId'=>$e->resource_revision_id?(string)$e->resource_revision_id:null]));}
 private function publications(array$f,int$l,array$a):Collection{if(!$this->cat($f,'publication'))return collect();$q=$this->base(ResourcePublicationVersion::query(),$f,'published_at');$this->allowed($q,$a);return$q->latest('published_at')->limit($l)->get(['id','resource_type','resource_id','publication_number','resource_revision_id','published_by','published_at'])->map(fn($v)=>$this->event("publication:$v->id",'publication.published',$v->resource_type,$v->resource_id,$v->published_by,$v->published_at,['publicationVersionId'=>(string)$v->id,'publicationNumber'=>$v->publication_number,'revisionId'=>(string)$v->resource_revision_id]));}
 private function shares(array$f,int$l,array$a):Collection{if(!$this->cat($f,'sharing'))return collect();$q=$this->base(ResourceShareRequest::query(),$f);$this->allowed($q,$a);return$q->latest('created_at')->limit($l)->get()->flatMap(function($s){$m=['shareRequestId'=>(string)$s->id];$out=[$this->event("share-request:$s->id",'share.requested',$s->resource_type,$s->resource_id,$s->sender_user_id,$s->created_at,$m)];if($s->accepted_at)$out[]=$this->event("share-accepted:$s->id",'share.accepted',$s->resource_type,$s->resource_id,$s->recipient_user_id,$s->accepted_at,$m);if($s->declined_at)$out[]=$this->event("share-rejected:$s->id",'share.rejected',$s->resource_type,$s->resource_id,$s->recipient_user_id,$s->declined_at,$m);return$out;});}
 private function authorized(User $user,string $ability,bool$personalScope=false):array{$out=[];foreach(CollaborationActivityRegistry::RESOURCES as$type){$definition=$this->resources->definition($type);$q=$definition->modelClass::query()->where('organization_id',$user->organization_id);if($type==='dashboard')$q->where('scope_type','personal');if(in_array($ability,['comment','edit','share'],true))$q->whereNotExists(fn($l)=>$l->selectRaw('1')->from('resource_lifecycle_states as ls')->whereColumn('ls.resource_id',$q->qualifyColumn('id'))->where('ls.resource_type',$type)->where('ls.state','!=','active'));if($type==='device'){$q->whereExists(fn($a)=>$a->selectRaw('1')->from('device_access_assignments as daa')->whereColumn('daa.device_id',$q->qualifyColumn('id'))->where('daa.user_id',$user->id)->when(in_array($ability,['edit','share'],true),fn($x)=>$x->where('daa.access_level','full_access')));if($ability==='edit'&&!$user->isPlatformAdmin())$q->whereRaw('1 = 0');}elseif($type==='dashboard'){$q->where(function($access)use($user,$ability,$q){$access->where('owner_user_id',$user->id);if($ability!=='share')$access->orWhereExists(fn($g)=>$g->selectRaw('1')->from('resource_collaborators as rc')->whereColumn('rc.resource_id',$q->qualifyColumn('id'))->where(['rc.resource_type'=>'dashboard','rc.user_id'=>$user->id])->whereIn('rc.permission',$ability==='view'||$ability==='comment'?['view','edit']:['edit']));});}elseif($personalScope||!$user->isPlatformAdmin()){$q->whereExists(fn($g)=>$g->selectRaw('1')->from('resource_collaborators as rc')->whereColumn('rc.resource_id',$q->qualifyColumn('id'))->where(['rc.resource_type'=>$type,'rc.user_id'=>$user->id])->whereIn('rc.permission',$ability==='view'||$ability==='comment'?['view','edit']:['edit']));}$out[$type]=$q->pluck($q->qualifyColumn('id'))->map(fn($id)=>(int)$id)->all();}return$out;}
 private function allowed($query,array$allowed):void{$query->where(function($q)use($allowed){$q->whereRaw('1 = 0');foreach($allowed as$type=>$ids)if($ids)$q->orWhere(fn($branch)=>$branch->where('resource_type',$type)->whereIn('resource_id',$ids));});}
 private function hydrateResources(Collection $events):void{$models=[];foreach($events->groupBy('resourceType')as$type=>$typed){$definition=$this->resources->definition($type);$models[$type]=$definition->modelClass::query()->whereIn('id',$typed->pluck('resourceId')->unique())->get()->keyBy(fn($model)=>(string)$model->getKey());}$events->transform(function($event)use($models){$event['resource']=$models[$event['resourceType']]->get((string)$event['resourceId']);return$event;});}
 private function anchorTypes(string$type,string$section):array{return match("$type:$section"){'device:dashboard'=>['dashboard_widget'],'device:parameters'=>['parameter'],'dashboard:widgets'=>['dashboard_widget'],'location:metadata'=>['metadata','name','description'],default=>['__none__']};}
 private function dto(array$e,Collection$actors):array{$a=$e['actorId']?$actors->get($e['actorId']):null;$label=$this->label($e['resource']);$metadata=array_filter($e['metadata'],fn($k)=>in_array($k,['revisionId','revisionNumber','threadId','commentId','shareRequestId','publicationVersionId','publicationNumber'],true),ARRAY_FILTER_USE_KEY);return['id'=>$e['id'],'eventType'=>$e['eventType'],'category'=>$e['category'],'resourceType'=>$e['resourceType'],'resourceId'=>(string)$e['resourceId'],'resourceLabel'=>$label,'actor'=>$a?['id'=>(string)$a->id,'displayName'=>$a->name,'inactive'=>$a->status!=='active']:null,'occurredAt'=>$e['occurredAt'],'summary'=>$this->events->summary($e['eventType'],$label),'deepLink'=>$this->link($e),'metadata'=>$metadata,'sectionKeys'=>$e['sectionKeys'],'sections'=>$this->sections->decorate($e['resourceType'],$e['sectionKeys'])];}
 private function event(string$id,string$type,string$resourceType,int$resourceId,?int$actorId,$at,array$metadata=[],array$sectionKeys=[]):array{$d=$this->events->event($type);$sectionKeys=$this->sections->normalize($resourceType,$sectionKeys);return compact('id','resourceType','resourceId','actorId','metadata','sectionKeys')+['eventType'=>$type,'category'=>$d['category'],'occurredAt'=>$at?->toISOString(),'sortId'=>$id];}
 private function dates($q,array$f):void{if($v=$f['date_from']??null)$q->where('created_at','>=',$v);if($v=$f['date_to']??null)$q->where('created_at','<=',CarbonImmutable::parse($v)->endOfDay());}
 private function cat(array$f,string$c):bool{return!isset($f['category'])||$f['category']===$c;}private function label(Model$r):string{return(string)($r->getAttribute('name')??$r->getAttribute('title')??ucfirst(class_basename($r)));}
 private function link(array$e):string{$base=match($e['resourceType']){'device'=>"/app/devices/{$e['resourceId']}",'device_template'=>"/app/developer/templates/{$e['resourceId']}",'dashboard'=>"/app/dashboard/{$e['resourceId']}",'automation'=>"/app/automations/{$e['resourceId']}",'report'=>"/app/reports/{$e['resourceId']}",'location'=>"/app/locations/{$e['resourceId']}",'webhook'=>"/app/developer/webhooks/{$e['resourceId']}",'firmware'=>'/app/developer/firmware'};if(isset($e['metadata']['threadId']))return"$base?thread={$e['metadata']['threadId']}";if(isset($e['metadata']['revisionId']))return"$base?revision={$e['metadata']['revisionId']}";return$base;}
}
