<?php
namespace App\Services;
use App\Collaboration\CollaborationResourceReference;use App\Collaboration\CollaborationResourceRegistry;use App\Models\FirmwareArtifact;use App\Models\FirmwareDeployment;use App\Models\User;use App\Services\Admin\DeviceAccessService;use Illuminate\Support\Facades\DB;use Illuminate\Validation\ValidationException;
class FirmwareDeploymentService
{
 public function __construct(private DeviceAccessService $access,private OperationalEventService $events,private CollaborationResourceRegistry $registry){}
 public function create(User $user,FirmwareArtifact $artifact,array $deviceIds):FirmwareDeployment
 {
  $this->registry->resolve($user,new CollaborationResourceReference('firmware',$artifact->id),'view');app(ResourceLifecycleService::class)->assertActive('firmware',$artifact->id,'Disabled or Archived Firmware cannot be deployed.');$release=$artifact->currentRelease()->first();if(!$release)throw ValidationException::withMessages(['firmware_artifact_id'=>['Only an approved Firmware release is eligible for deployment.']]);$ids=array_values(array_unique(array_map('intval',$deviceIds)));if(count($ids)!==count($deviceIds))throw ValidationException::withMessages(['device_ids'=>['Duplicate Device targets are not allowed.']]);$devices=$this->access->accessibleDevices($user)->whereIn('id',$ids)->with('template')->get();if($devices->count()!==count($ids))throw ValidationException::withMessages(['device_ids'=>['One or more Devices are unavailable.']]);foreach($devices as $device){app(ResourceLifecycleService::class)->assertActive('device',$device->id,'Disabled or Archived Devices cannot receive deployments.');if(!$this->access->canManageDevice($user,$device))throw ValidationException::withMessages(['device_ids'=>['Full Access is required for every target Device.']]);if(!$this->compatible($artifact,$device))throw ValidationException::withMessages(['device_ids'=>["{$device->name} is not compatible with this artifact."]]);}
  $deployment=DB::transaction(function()use($user,$artifact,$release,$devices){$d=$artifact->deployments()->create(['organization_id'=>$artifact->organization_id,'firmware_release_id'=>$release->id,'created_by'=>$user->id,'status'=>'delivery_unavailable','failed_at'=>now(),'failure_message'=>'Firmware delivery is not configured.']);foreach($devices as $device)$d->targets()->create(['device_id'=>$device->id,'status'=>'delivery_unavailable','failure_code'=>'delivery_not_configured','failure_message'=>'Firmware delivery is not configured.']);return $d;});$this->events->firmwareDeliveryUnavailable($deployment);return $this->detail($deployment);
 }
 public function detail(FirmwareDeployment $deployment):FirmwareDeployment{return $deployment->load(['artifact:id,name,version','release:id,domain_version,artifact_sha256','creator:id,name','targets.device:id,name,external_id']);}
 private function compatible(FirmwareArtifact $artifact,$device):bool{return (!$artifact->device_template_id||$artifact->device_template_id===$device->device_template_id)&&(!$artifact->device_type||$artifact->device_type===$device->type)&&(!$artifact->protocol||strtolower($artifact->protocol)===strtolower($device->protocol));}
}
