<?php
namespace App\Services;
use App\Jobs\GenerateReportJob;use App\Models\{Report,ReportRun,ResourcePublicationVersion,ResourceRevision,User};use Illuminate\Support\Facades\Storage;use Illuminate\Support\Str;
class ReportGenerationService{
 public function __construct(private ReportConfigurationService $configuration,private ReportGeneratorRegistry $registry,private ReportAccessService $access){}
 public function request(Report $report,User $user):ReportRun{$this->access->assertRun($user,$report);$revision=ResourceRevision::where(['resource_type'=>'report','resource_id'=>$report->id])->latest('revision_number')->firstOrFail();return $this->create($report,$revision,null,$user);}
 public function requestPublished(ResourcePublicationVersion $version,User $user):ReportRun{$version->loadMissing('revision');abort_unless($version->resource_type==='report',404);abort_unless($this->access->canRunPublished($user,$version),403);$report=Report::findOrFail($version->resource_id);return $this->create($report,$version->revision,$version,$user);}
 private function create(Report $report,ResourceRevision $revision,?ResourcePublicationVersion $version,User $user):ReportRun{$type=(string)data_get($revision->snapshot,'metadata.reportType');$config=$revision->snapshot['configuration']??[];$resolved=$this->configuration->validate($user,$type,$config,true);$run=$report->runs()->create(['report_revision_id'=>$revision->id,'publication_version_id'=>$version?->id,'organization_id'=>$report->organization_id,'requested_by'=>$user->id,'status'=>'pending','resolved_configuration'=>$resolved]);GenerateReportJob::dispatch($run->id)->afterCommit();return $run;}
 public function generate(ReportRun $run):void{$run->loadMissing(['requester','report','revision','publicationVersion.revision']);abort_unless($run->requester&&$run->report&&$run->revision,422,'Report run provenance is unavailable.');if($run->publication_version_id){abort_unless($run->publicationVersion&&$run->publicationVersion->resource_revision_id===$run->report_revision_id,422,'Published Report provenance is invalid.');abort_unless($this->access->canRunPublished($run->requester,$run->publicationVersion),403);}else{$this->access->assertRun($run->requester,$run->report);}abort_unless($run->revision->resource_type==='report'&&(int)$run->revision->resource_id===(int)$run->report_id,422,'Pinned Report revision is invalid.');$this->configuration->assertCurrentAccess($run->requester,$run->resolved_configuration);$type=(string)data_get($run->revision->snapshot,'metadata.reportType');$generator=$this->registry->for($type);$run->update(['status'=>'running','started_at'=>now(),'failure_code'=>null,'failure_message'=>null]);$stream=tmpfile();if($stream===false)throw new \RuntimeException('Report workspace unavailable.');fputcsv($stream,array_map([$this,'safeCell'],$generator->headers()));$count=0;foreach($generator->rows($run) as $row){fputcsv($stream,array_map([$this,'safeCell'],$row));$count++;}rewind($stream);$path='reports/'.$run->organization_id.'/'.$run->id.'-'.Str::random(12).'.csv';if(!Storage::disk('local')->writeStream($path,$stream)){fclose($stream);throw new \RuntimeException('Report artifact could not be stored.');}fclose($stream);$size=Storage::disk('local')->size($path);$run->update(['status'=>'completed','completed_at'=>now(),'row_count'=>$count,'artifact_disk'=>'local','artifact_path'=>$path,'artifact_format'=>'csv','artifact_size'=>$size]);}
 public function safeCell(mixed $value):string{$text=$value===null?'':(string)$value;if($text!==''&&in_array($text[0],['=','+','-','@'],true))return "'".$text;return $text;}
}
