<?php
namespace App\Services;
final class ResourceRevisionSectionResolver{
 public function __construct(private ResourceSectionRegistry$registry){}
 public function resolve(string$type,?array$before,array$after):array{if($type==='dashboard')return$this->dashboard($before,$after);if($type==='device')return$this->device($before,$after);$keys=$before===null?array_keys($after):array_values(array_filter(array_keys($after),fn($key)=>($before[$key]??null)!==$after[$key]));return$this->registry->normalize($type,$keys);}
 private function device(?array$before,array$after):array{if($before===null)return$this->registry->normalize('device',['metadata','dashboard','parameters']);$keys=[];$oldMetadata=$before['metadata']??[];$newMetadata=$after['metadata']??[];unset($oldMetadata['location'],$newMetadata['location']);if($oldMetadata!==$newMetadata)$keys[]='metadata';if(($before['dashboard']??null)!==($after['dashboard']??null))$keys[]='dashboard';if(($before['parameters']??null)!==($after['parameters']??null))$keys[]='parameters';return$this->registry->normalize('device',$keys);} private function dashboard(?array$before,array$after):array{if($before===null)return$this->registry->normalize('dashboard',['metadata','layout','widgets','sources']);$keys=[];if(($before['metadata']??null)!==($after['metadata']??null))$keys[]='metadata';$old=$this->widgets($before);$new=$this->widgets($after);if(array_keys($old)!==array_keys($new))$keys[]='widgets';foreach(array_unique(array_merge(array_keys($old),array_keys($new)))as$id){$a=$old[$id]??null;$b=$new[$id]??null;if($a===null||$b===null)continue;if(($a['layout']??null)!==($b['layout']??null))$keys[]='layout';if(array_diff_assoc($this->presentation($a),$this->presentation($b))||array_diff_assoc($this->presentation($b),$this->presentation($a)))$keys[]='widgets';if($this->source($a)!==$this->source($b))$keys[]='sources';if($this->settings($a)!==$this->settings($b))$keys[]='widgets';}return$this->registry->normalize('dashboard',$keys);}
 private function widgets(array$snapshot):array{$rows=$snapshot['dashboard']['widgets']??[];$out=[];foreach($rows as$row)if(is_array($row)&&isset($row['id']))$out[(string)$row['id']]=$row;ksort($out);return$out;}
 private function presentation(array$widget):array{return array_intersect_key($widget,array_flip(['type','title']));}private function source(array$widget):array{return array_intersect_key($widget['configuration']??[],array_flip(['deviceId','parameterId','telemetryKey','metric','query','aggregation']));}private function settings(array$widget):array{return array_diff_key($widget['configuration']??[],array_flip(['deviceId','parameterId','telemetryKey','metric','query','aggregation']));}
}
