import { useEffect, useState } from "react";
import type { Widget } from "../../types/dashboard";
import type { TelemetryRecord } from "../../types/telemetry";
import type { Device } from "../../types/device";
import { getTelemetryHistory } from "../../services/analytics.service";
import { getDevice, getDevices } from "../../services/device.service";
import { listDeviceEvents } from "../../services/operational-event.service";
import { listProvisioningSessions } from "../../services/provisioning.service";
import type {OperationalEvent} from "../../types/operational-event";
import type {ProvisioningSession} from "../../types/provisioning";
import { getGlobalOperationsOverview } from "../../services/admin.service";
import type {GlobalOperationsOverview} from "../../types/admin";
import DashboardWidget from "../dashboard/widgets/DashboardWidget";
import MetricWidget from "../dashboard/widgets/MetricWidget";
import ChartWidget from "../dashboard/widgets/ChartWidget";
import GaugeWidget from "../dashboard/widgets/GaugeWidget";
import StatusWidget from "../dashboard/widgets/StatusWidget";
import TableWidget from "../dashboard/widgets/TableWidget";
import DeviceWidget from "../dashboard/widgets/DeviceWidget";
import GeomapWidget from "../dashboard/widgets/GeomapWidget";
import ImageMapWidget from "../dashboard/widgets/ImageMapWidget";
import {hasWidgetRenderer} from "../dashboard/widgets/widgetRendererRegistry";
import {useDashboardStore} from "../../store/dashboard.store";
import { dashboardMapAssetUrl } from "../../services/dashboard.service";

export default function WidgetRenderer({ widget, editable = false, onComment, timeRange }: { widget: Widget; editable?: boolean; onComment?:()=>void; timeRange?:"1h"|"6h"|"24h"|"7d"|"30d" }) {
  const [records, setRecords] = useState<TelemetryRecord[]>([]);
  const [device, setDevice] = useState<Device | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [globalData,setGlobalData]=useState<GlobalOperationsOverview|null>(null);
  const [devices,setDevices]=useState<Device[]>([]);
  const [events,setEvents]=useState<OperationalEvent[]>([]);
  const [activations,setActivations]=useState<ProvisioningSession[]>([]);
  const source = widget.settings.datasource;
  const dashboardTimeRange=useDashboardStore(state=>state.timeRange);
  const fleetDevices = devices.filter(item => widget.settings.sourceMode === "explicit_devices" ? (widget.settings.deviceIds ?? []).includes(String(item.id)) : widget.settings.sourceMode === "template_devices" ? String(item.template?.id ?? "") === String(widget.settings.deviceTemplateId ?? "") : true);
  const fleetEvents = events.filter(item => { const id=String(item.device?.id ?? ""); if (widget.settings.sourceMode === "explicit_devices") return (widget.settings.deviceIds ?? []).includes(id); if (widget.settings.sourceMode === "template_devices") return fleetDevices.some(device=>String(device.id)===id); return true; });

  useEffect(() => {
    const deviceCollections=["device_count","device_table","geo_map","image_map","device_connection_map","metric_by_devices"];
    const eventWidgets=["event_count_tile","latest_events","event_count_chart","events_over_time","events_breakdown_over_time","events_by_organization","events_by_device","events_by_template"];
    if(deviceCollections.includes(widget.type)||eventWidgets.includes(widget.type)||widget.type==="activations") {let active=true;const timer=window.setTimeout(()=>{setLoading(true);setError("");const request=deviceCollections.includes(widget.type)?getDevices().then(value=>{if(active)setDevices(value)}):eventWidgets.includes(widget.type)?listDeviceEvents({per_page:100}).then(value=>{if(active)setEvents(value.data as OperationalEvent[])}):listProvisioningSessions({status:"completed",per_page:100}).then(value=>{if(active)setActivations(value.data)});request.catch(()=>{if(active)setError("Unable to load authorized widget data.")}).finally(()=>{if(active)setLoading(false)})},0);return()=>{active=false;window.clearTimeout(timer)};}
    if (widget.type.startsWith("global_")) {let active=true;const timer=window.setTimeout(()=>{setLoading(true);getGlobalOperationsOverview().then(value=>{if(active)setGlobalData(value)}).catch(()=>{if(active)setError("Unable to load global widget data.")}).finally(()=>{if(active)setLoading(false)})},0);return()=>{active=false;window.clearTimeout(timer)};}
    if (!source?.deviceId) return;
    let active = true;
    const timer = window.setTimeout(() => {
      setLoading(true);
      setError("");
      const request = widget.type === "device" || widget.type === "status"
        ? getDevice(source.deviceId).then((value) => { if (active) setDevice(value); })
        : source.telemetryKey
          ? getTelemetryHistory(source.telemetryKey, { deviceId: source.deviceId, range: timeRange??dashboardTimeRange??widget.settings.timeRange??"24h", interval: "hour", aggregation: "average" }).then((value) => {
              if (active) setRecords(value.points.map((point, index) => ({ id: `${point.timestamp}-${index}`, deviceId: source.deviceId, key: source.telemetryKey, value: point.value, unit: value.unit ?? "", recordedAt: point.timestamp })));
            })
          : Promise.resolve();
      request.catch(() => { if (active) setError("Unable to load widget data."); }).finally(() => { if (active) setLoading(false); });
    }, 0);
    return () => { active = false; window.clearTimeout(timer); };
  }, [source?.deviceId, source?.telemetryKey, widget.type,widget.settings.timeRange,timeRange,dashboardTimeRange]);

  const latest = records.at(-1) ?? null;
  let content: React.ReactNode = null;
  if (widget.type === "metric") content = <MetricWidget value={latest?.value ?? null} label={source?.telemetryKey} unit={latest?.unit ?? source?.unit} />;
  else if (widget.type === "chart") content = <ChartWidget records={records} type={widget.settings.chartType} />;
  else if (widget.type === "gauge" && latest) content = <GaugeWidget value={latest.value} min={widget.settings.minimum} max={widget.settings.maximum} unit={latest.unit ?? source?.unit} />;
  else if (widget.type === "table") content = <TableWidget records={records} />;
  else if (widget.type === "status" && device) content = <StatusWidget status={device.status === "online" ? "online" : device.status === "maintenance" ? "warning" : "offline"} label={device.status} />;
  else if (widget.type === "device" && device) content = <DeviceWidget device={device} />;
  else if(widget.type==="global_device_summary"&&globalData)content=<div className="grid h-full grid-cols-2 gap-2">{([["Total",globalData.devices.total,"var(--ds-chart-1)"],["Online",globalData.devices.online,"var(--ds-chart-2)"],["Offline",globalData.devices.offline,"var(--ds-chart-5)"],["Organizations",globalData.organizations.total,"var(--ds-chart-6)"]] as [string,number,string][]).map(([label,value,color])=><div key={label} className="flex flex-col items-center justify-center rounded-[10px] border p-2 text-center" style={{borderColor:`color-mix(in oklab, ${color} 40%, transparent)`,background:`color-mix(in oklab, ${color} 10%, var(--ds-card-alt))`,boxShadow:`inset 0 1px 1px var(--ds-inset-shadow), 0 0 14px -6px ${color}`}}><strong className="text-xl font-bold tabular-nums" data-numeric style={{color,textShadow:`0 0 14px color-mix(in oklab, ${color} 70%, transparent)`}}>{value}</strong><span className="text-[9.5px] font-semibold uppercase tracking-[0.12em] text-[var(--ds-text-subtle)]">{label}</span></div>)}</div>;
  else if(widget.type==="global_failure_summary"&&globalData)content=<div className="grid h-full grid-cols-2 gap-2">{([["Events",globalData.operationalWindow.errors,"var(--ds-chart-3)"],["Crashes",globalData.operationalWindow.crashes,"var(--ds-chart-5)"],["Firmware",globalData.operationalWindow.failedFirmwareDeployments,"var(--ds-chart-4)"],["Webhooks",globalData.operationalWindow.failedWebhookDeliveries,"var(--ds-chart-2)"]] as [string,number,string][]).map(([label,value,color])=><div key={label} className="flex flex-col items-center justify-center rounded-[10px] border p-2 text-center" style={{borderColor:`color-mix(in oklab, ${color} 40%, transparent)`,background:`color-mix(in oklab, ${color} 10%, var(--ds-card-alt))`,boxShadow:`inset 0 1px 1px var(--ds-inset-shadow), 0 0 14px -6px ${color}`}}><strong className="text-xl font-bold tabular-nums" data-numeric style={{color,textShadow:`0 0 14px color-mix(in oklab, ${color} 70%, transparent)`}}>{value}</strong><span className="text-[9.5px] font-semibold uppercase tracking-[0.12em] text-[var(--ds-text-subtle)]">{label}</span></div>)}</div>;
  else if(widget.type==="label")content=<div className="kpi-row"><span aria-hidden className="kpi-icon text-[var(--ds-chart-6)]" style={{background:"color-mix(in oklab, var(--ds-chart-6) 16%, transparent)",boxShadow:"inset 0 0 0 1px color-mix(in oklab, var(--ds-chart-6) 42%, transparent), 0 0 20px -5px var(--ds-chart-6)"}}><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 2H2v10l9.3 9.3a1 1 0 0 0 1.4 0l8.6-8.6a1 1 0 0 0 0-1.4Z"/><circle cx="7" cy="7" r="1.5"/></svg></span><p className={`min-w-0 break-words ${widget.settings.fontStyle==="medium"?"font-medium":widget.settings.fontStyle==="bold"||!widget.settings.fontStyle?"font-bold":widget.settings.fontStyle==="italic"?"italic":"font-normal"}`} style={{fontSize:`${widget.settings.fontSize??24}px`,lineHeight:1.2,textShadow:"0 0 16px var(--ds-primary-glow)"}}>{widget.settings.staticValue||"Label"} {source?.unit}</p></div>;
  else if(widget.type==="device_count"){const onlineCount=fleetDevices.filter(d=>d.status==="online").length;content=<div className="kpi-row"><span aria-hidden className="kpi-icon text-white" style={{background:"linear-gradient(145deg, var(--ds-chart-1), var(--ds-primary-strong))",boxShadow:"inset 0 1px 0 rgb(255 255 255 / .2), 0 0 22px -4px var(--ds-primary-glow)"}}><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="4" y="4" width="16" height="16" rx="2"/><rect x="9" y="9" width="6" height="6"/><path d="M9 1v3M15 1v3M9 20v3M15 20v3M1 9h3M1 15h3M20 9h3M20 15h3"/></svg></span><div className="flex min-w-0 flex-col gap-1"><p className="truncate text-[10px] font-bold uppercase tracking-[0.2em] text-[var(--ds-text-subtle)]">Devices</p><p className="kpi-value" data-numeric style={{textShadow:"0 0 18px var(--ds-primary-glow), 0 0 4px rgb(255 255 255 / .15)"}}>{fleetDevices.length}</p><div className="kpi-chips text-[11px]"><span className="inline-flex items-center gap-1.5 rounded-full border border-[color-mix(in_oklab,var(--ds-chart-2)_45%,transparent)] bg-[var(--ds-card-alt)] px-2 py-0.5 font-semibold text-[var(--ds-chart-2)]" style={{boxShadow:"0 0 10px -4px var(--ds-chart-2)"}}><span aria-hidden className="h-1.5 w-1.5 rounded-full bg-[var(--ds-chart-2)] shadow-[0_0_6px_1px_var(--ds-chart-2)]"/>{onlineCount} online</span><span className="inline-flex items-center gap-1.5 rounded-full border border-[color-mix(in_oklab,var(--ds-chart-5)_45%,transparent)] bg-[var(--ds-card-alt)] px-2 py-0.5 font-semibold text-[var(--ds-chart-5)]" style={{boxShadow:"0 0 10px -4px var(--ds-chart-5)"}}><span aria-hidden className="h-1.5 w-1.5 rounded-full bg-[var(--ds-chart-5)] shadow-[0_0_6px_1px_var(--ds-chart-5)]"/>{fleetDevices.length-onlineCount} offline</span></div></div></div>;}
  else if(widget.type==="device_table")content=fleetDevices.length?<div className="max-h-full overflow-auto rounded-[8px] border border-[var(--ds-border-subtle)]"><table className="w-full border-collapse text-left text-xs"><thead className="sticky top-0 z-10"><tr className="bg-[var(--ds-card-alt)] text-[9.5px] font-semibold uppercase tracking-[0.12em] text-[var(--ds-text-subtle)]"><th className="px-2.5 py-2">Device</th><th className="px-2.5 py-2">Status</th><th className="px-2.5 py-2">Last seen</th></tr></thead><tbody>{fleetDevices.slice(0,widget.settings.rowLimit??25).map(item=><tr key={item.id} className="border-t border-[var(--ds-border-subtle)] transition-colors hover:bg-[var(--ds-primary-surface)]"><td className="px-2.5 py-2 font-medium text-[var(--ds-text)]">{item.name}</td><td className="px-2.5 py-2"><span className={`inline-flex items-center gap-1.5 font-semibold ${item.status==="online"?"text-[var(--ds-chart-2)]":"text-[var(--ds-chart-5)]"}`}><span aria-hidden className={`h-1.5 w-1.5 rounded-full ${item.status==="online"?"bg-[var(--ds-chart-2)] shadow-[0_0_5px_1px_var(--ds-chart-2)]":"bg-[var(--ds-chart-5)] shadow-[0_0_5px_1px_var(--ds-chart-5)]"}`}/>{item.status}</span></td><td className="px-2.5 py-2 text-[var(--ds-text-muted)]">{item.lastSeen?new Date(item.lastSeen).toLocaleString():"Never"}</td></tr>)}</tbody></table></div>:null;
  else if(widget.type==="device_connection_map")content=fleetDevices.length?<div role="img" aria-label="Authorized Device connection statuses" className="grid h-full auto-rows-fr grid-cols-2 content-stretch gap-2">{fleetDevices.slice(0,50).map(item=><div key={item.id} className="flex items-center gap-2 rounded-[8px] border border-[var(--ds-border-subtle)] bg-[var(--ds-card-alt)] p-2 text-xs shadow-[inset_0_1px_1px_var(--ds-inset-shadow)]"><span aria-hidden className={`h-2 w-2 shrink-0 rounded-full ${item.status==="online"?"bg-[var(--ds-chart-2)] shadow-[0_0_6px_1px_var(--ds-chart-2)]":"bg-[var(--ds-chart-5)] shadow-[0_0_6px_1px_var(--ds-chart-5)]"}`}/><span className="min-w-0"><span className="block truncate font-medium text-[var(--ds-text)]">{item.name}</span><span className={`block text-[10px] font-bold uppercase tracking-[0.08em] ${item.status==="online"?"text-[var(--ds-chart-2)]":"text-[var(--ds-chart-5)]"}`}>{item.status}</span></span></div>)}</div>:null;
  else if(widget.type==="geo_map")content=<GeomapWidget devices={fleetDevices}/>;
  else if(widget.type==="image_map")content=<ImageMapWidget devices={fleetDevices} editable={editable} onMarkersChange={markers=>useDashboardStore.getState().updateWidget(widget.id,{settings:{...widget.settings,markers}})} backgroundImageUrl={widget.settings.imageAssetId?dashboardMapAssetUrl(widget.settings.imageAssetId):undefined} markers={widget.settings.markers}/>;
  else if(widget.type==="switch"&&latest){const checked=Number(latest.value)>0;content=<div className="kpi-row"><span aria-hidden className="kpi-icon" style={{color:checked?"#1F2937":"var(--ds-text-muted)",background:checked?"linear-gradient(145deg, var(--ds-chart-3), color-mix(in oklab, var(--ds-chart-4) 70%, var(--ds-chart-3)))":"var(--ds-card-alt)",boxShadow:checked?"inset 0 1px 0 rgb(255 255 255 / .3), 0 0 22px -4px var(--ds-chart-3)":"inset 0 0 0 1px var(--ds-border-subtle)"}}><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 2v10"/><path d="M18.4 6.6a9 9 0 1 1-12.8 0"/></svg></span><div className="flex min-w-0 flex-col gap-1.5"><button type="button" role="switch" aria-checked={checked} disabled className={`relative inline-flex h-8 w-14 shrink-0 rounded-full border transition-colors ${checked?"border-transparent":"border-[var(--ds-border)] bg-[var(--ds-card-alt)] shadow-[inset_0_2px_3px_var(--ds-inset-shadow)]"}`} style={checked?{background:"linear-gradient(135deg, var(--ds-primary), var(--ds-primary-strong))",boxShadow:"inset 0 1px 2px rgb(0 0 0 / .2), 0 0 14px -2px var(--ds-primary-glow)"}:undefined}><span aria-hidden className={`absolute top-1 h-6 w-6 rounded-full bg-white transition-all ${checked?"left-7":"left-1"}`} style={{boxShadow:"0 2px 5px rgb(0 0 0 / .35), inset 0 1px 1px rgb(255 255 255 / .9)"}}/></button><p className="text-xs font-semibold text-[var(--ds-text)]">Current value: {checked?"On":"Off"}</p><p className="text-[11px] text-[var(--ds-text-subtle)]">Read-only: no supported writable Device parameter transport.</p></div></div>}
  else if(widget.type==="slider"&&latest){const sMin=widget.settings.minimum??0;const sMax=widget.settings.maximum??100;const sPct=Math.max(0,Math.min(100,((Number(latest.value)-sMin)/((sMax-sMin)||1))*100));content=<div className="kpi-row"><span aria-hidden className="kpi-icon text-[var(--ds-primary-soft)]" style={{background:"linear-gradient(145deg, var(--ds-primary-surface), color-mix(in oklab, var(--ds-primary) 32%, transparent))",boxShadow:"inset 0 0 0 1px var(--ds-primary-outline), 0 0 22px -4px var(--ds-primary-glow)"}}><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><line x1="4" x2="4" y1="21" y2="14"/><line x1="4" x2="4" y1="10" y2="3"/><line x1="12" x2="12" y1="21" y2="12"/><line x1="12" x2="12" y1="8" y2="3"/><line x1="20" x2="20" y1="21" y2="16"/><line x1="20" x2="20" y1="12" y2="3"/><line x1="2" x2="6" y1="14" y2="14"/><line x1="10" x2="14" y1="8" y2="8"/><line x1="18" x2="22" y1="16" y2="16"/></svg></span><div className="flex min-w-0 flex-1 flex-col gap-2.5"><input aria-label="Read-only Device value" type="range" disabled value={latest.value} min={sMin} max={sMax} className="iot-range w-full" style={{background:`linear-gradient(to right, var(--ds-primary-strong) 0%, var(--ds-primary-soft) ${sPct}%, var(--ds-card-alt) ${sPct}%)`}}/><p className="text-xs font-semibold text-[var(--ds-text)] tabular-nums" data-numeric>Current value: {latest.value} {latest.unit??source?.unit}</p><p className="text-[11px] text-[var(--ds-text-subtle)]">Read-only: no supported writable Device parameter transport.</p></div></div>}
  else if(widget.type==="metrics_over_time")content=<ChartWidget records={records} type={widget.settings.chartType}/>;
  else if(widget.type==="metric_by_devices")content=<div className="flex h-full flex-col justify-evenly gap-1.5">{fleetDevices.slice(0,10).map(item=><div key={item.id} className="flex items-center justify-between gap-2 rounded-[7px] border border-[var(--ds-border-subtle)] bg-[var(--ds-card-alt)] px-2.5 py-1.5 text-xs"><span className="flex min-w-0 items-center gap-2"><span aria-hidden className={`h-1.5 w-1.5 shrink-0 rounded-full ${item.status==="online"?"bg-[var(--ds-chart-2)] shadow-[0_0_5px_1px_var(--ds-chart-2)]":"bg-[var(--ds-chart-5)] shadow-[0_0_5px_1px_var(--ds-chart-5)]"}`}/><span className="truncate font-medium text-[var(--ds-text)]">{item.name}</span></span><span className={`shrink-0 text-[10px] font-bold uppercase tracking-[0.08em] ${item.status==="online"?"text-[var(--ds-chart-2)]":"text-[var(--ds-chart-5)]"}`}>{item.status}</span></div>)}</div>;
  else if(widget.type==="event_count_tile")content=<div className="kpi-row"><span aria-hidden className="kpi-icon text-[#1F2937]" style={{background:"linear-gradient(145deg, var(--ds-chart-3), color-mix(in oklab, var(--ds-chart-4) 70%, var(--ds-chart-3)))",boxShadow:"inset 0 1px 0 rgb(255 255 255 / .3), 0 0 22px -4px var(--ds-chart-3)"}}><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M13 2 3 14h7l-1 8 10-12h-7l1-8z"/></svg></span><div className="flex min-w-0 flex-col gap-1"><p className="truncate text-[10px] font-bold uppercase tracking-[0.2em] text-[var(--ds-text-subtle)]">Events</p><p className="kpi-value" data-numeric style={{textShadow:"0 0 18px var(--ds-chart-3)"}}>{fleetEvents.length}</p><span className="inline-flex w-fit items-center gap-1.5 rounded-full border border-[color-mix(in_oklab,var(--ds-chart-3)_50%,transparent)] bg-[var(--ds-card-alt)] px-2 py-0.5 text-[11px] font-bold text-[var(--ds-chart-3)]" style={{boxShadow:"0 0 10px -4px var(--ds-chart-3)"}}><span aria-hidden className="h-1.5 w-1.5 rounded-full bg-[var(--ds-chart-3)] shadow-[0_0_6px_1px_var(--ds-chart-3)]"/>events in range</span></div></div>;
  else if(widget.type==="latest_events")content=<div className="max-h-64 space-y-0.5 overflow-auto">{fleetEvents.slice(0,widget.settings.rowLimit??10).map(item=><div key={item.id} className="flex items-start gap-2.5 border-b border-[var(--ds-border-subtle)] px-1 py-2 text-xs last:border-0"><span aria-hidden className="mt-0.5 grid h-5 w-5 shrink-0 place-items-center rounded-[6px] text-[var(--ds-chart-3)]" style={{background:"color-mix(in oklab, var(--ds-chart-3) 14%, transparent)",boxShadow:"inset 0 0 0 1px color-mix(in oklab, var(--ds-chart-3) 40%, transparent), 0 0 10px -4px var(--ds-chart-3)"}}><svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round"><path d="M13 2 3 14h7l-1 8 10-12h-7l1-8z"/></svg></span><span className="min-w-0"><strong className="block truncate font-semibold text-[var(--ds-text)]">{item.title||item.eventType}</strong><span className="block text-[10px] text-[var(--ds-text-subtle)]">{new Date(item.occurredAt).toLocaleString()}</span></span></div>)}</div>;
  else if(["event_count_chart","events_by_organization","events_by_device","events_by_template"].includes(widget.type)) {const groups=new Map<string,number>();fleetEvents.forEach(item=>{const key=widget.type==="events_by_organization"?item.organization.name:widget.type==="events_by_device"?(item.device?.name||"Organization event"):widget.type==="events_by_template"?(item.device?.template?.name||"No template"):item.eventType;groups.set(key,(groups.get(key)||0)+1)});content=<div role="img" aria-label={widget.settings.title} className="space-y-2">{[...groups].slice(0,10).map(([label,count])=><div key={label} className="text-xs"><span className="flex justify-between text-[var(--ds-text-muted)]"><span>{label}</span><strong className="tabular-nums text-[var(--ds-chart-3)]" data-numeric style={{textShadow:"0 0 10px var(--ds-chart-3)"}}>{count}</strong></span><span className="mt-1 block h-2 rounded-full" style={{width:`${Math.max(4,count/Math.max(1,fleetEvents.length)*100)}%`,background:"linear-gradient(90deg, var(--ds-chart-4), var(--ds-chart-3))",boxShadow:"0 0 10px -1px var(--ds-chart-3)"}}/></div>)}</div>}
  else if(["events_over_time","events_breakdown_over_time"].includes(widget.type))content=<ChartWidget records={fleetEvents.slice().reverse().map((item,index)=>({id:item.id,deviceId:item.device?.id||"organization",key:item.eventType,value:index+1,unit:"events",recordedAt:item.occurredAt}))} type="line"/>;
  else if(widget.type==="activations")content=<ChartWidget records={activations.slice().reverse().map((item,index)=>({id:item.id,deviceId:item.device?.id||"provisioning",key:"activation",value:index+1,unit:"activations",recordedAt:item.completedAt||item.updatedAt}))} type="line"/>;
  const registered=hasWidgetRenderer(String(widget.type));
  const requiresSource=["metric","chart","gauge","table","status","device","switch","slider","metrics_over_time"].includes(widget.type) && widget.settings.sourceMode === undefined;
  return <DashboardWidget title={widget.settings.title || "Untitled widget"} loading={registered&&loading} error={registered?error:undefined} empty={!registered||widget.available===false||(requiresSource&&!source?.deviceId)||!content} emptyText={!registered?`Unsupported widget type: ${String(widget.type)}. An editor may remove it safely.`:widget.available===false?"Access unavailable. Protected widget data is no longer available.":requiresSource&&!source?.deviceId?"Widget not configured. Select an authorized Device source.":"No data returned for this widget."} editable={editable} onComment={onComment}>{content}</DashboardWidget>;
}
