import { useEffect, useState } from "react";
import type { Widget } from "../../types/dashboard";
import type { TelemetryRecord } from "../../types/telemetry";
import type { Device } from "../../types/device";
import { getTelemetryHistory } from "../../services/analytics.service";
import { getDevice, getDevices } from "../../services/device.service";
import { listDeviceEvents } from "../../services/operational-event.service";
import { listProvisioningSessions } from "../../services/provisioning.service";
import type {OperationalEvent} from "../../types/operational-event";
import type {ProvisioningSession} from "../../types/provisioning";
import { getGlobalOperationsOverview } from "../../services/admin.service";
import type {GlobalOperationsOverview} from "../../types/admin";
import DashboardWidget from "../dashboard/widgets/DashboardWidget";
import MetricWidget from "../dashboard/widgets/MetricWidget";
import ChartWidget from "../dashboard/widgets/ChartWidget";
import GaugeWidget from "../dashboard/widgets/GaugeWidget";
import StatusWidget from "../dashboard/widgets/StatusWidget";
import TableWidget from "../dashboard/widgets/TableWidget";
import DeviceWidget from "../dashboard/widgets/DeviceWidget";
import GeomapWidget from "../dashboard/widgets/GeomapWidget";
import ImageMapWidget from "../dashboard/widgets/ImageMapWidget";
import {hasWidgetRenderer} from "../dashboard/widgets/widgetRendererRegistry";
import {useDashboardStore} from "../../store/dashboard.store";
import { dashboardMapAssetUrl } from "../../services/dashboard.service";

export default function WidgetRenderer({ widget, editable = false, onComment, timeRange }: { widget: Widget; editable?: boolean; onComment?:()=>void; timeRange?:"1h"|"6h"|"24h"|"7d"|"30d" }) {
  const [records, setRecords] = useState<TelemetryRecord[]>([]);
  const [device, setDevice] = useState<Device | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [globalData,setGlobalData]=useState<GlobalOperationsOverview|null>(null);
  const [devices,setDevices]=useState<Device[]>([]);
  const [events,setEvents]=useState<OperationalEvent[]>([]);
  const [activations,setActivations]=useState<ProvisioningSession[]>([]);
  const source = widget.settings.datasource;
  const dashboardTimeRange=useDashboardStore(state=>state.timeRange);
  const fleetDevices = devices.filter(item => widget.settings.sourceMode === "explicit_devices" ? (widget.settings.deviceIds ?? []).includes(String(item.id)) : widget.settings.sourceMode === "template_devices" ? String(item.template?.id ?? "") === String(widget.settings.deviceTemplateId ?? "") : true);
  const fleetEvents = events.filter(item => { const id=String(item.device?.id ?? ""); if (widget.settings.sourceMode === "explicit_devices") return (widget.settings.deviceIds ?? []).includes(id); if (widget.settings.sourceMode === "template_devices") return fleetDevices.some(device=>String(device.id)===id); return true; });

  useEffect(() => {
    const deviceCollections=["device_count","device_table","geo_map","image_map","device_connection_map","metric_by_devices"];
    const eventWidgets=["event_count_tile","latest_events","event_count_chart","events_over_time","events_breakdown_over_time","events_by_organization","events_by_device","events_by_template"];
    if(deviceCollections.includes(widget.type)||eventWidgets.includes(widget.type)||widget.type==="activations") {let active=true;const timer=window.setTimeout(()=>{setLoading(true);setError("");const request=deviceCollections.includes(widget.type)?getDevices().then(value=>{if(active)setDevices(value)}):eventWidgets.includes(widget.type)?listDeviceEvents({per_page:100}).then(value=>{if(active)setEvents(value.data as OperationalEvent[])}):listProvisioningSessions({status:"completed",per_page:100}).then(value=>{if(active)setActivations(value.data)});request.catch(()=>{if(active)setError("Unable to load authorized widget data.")}).finally(()=>{if(active)setLoading(false)})},0);return()=>{active=false;window.clearTimeout(timer)};}
    if (widget.type.startsWith("global_")) {let active=true;const timer=window.setTimeout(()=>{setLoading(true);getGlobalOperationsOverview().then(value=>{if(active)setGlobalData(value)}).catch(()=>{if(active)setError("Unable to load global widget data.")}).finally(()=>{if(active)setLoading(false)})},0);return()=>{active=false;window.clearTimeout(timer)};}
    if (!source?.deviceId) return;
    let active = true;
    const timer = window.setTimeout(() => {
      setLoading(true);
      setError("");
      const request = widget.type === "device" || widget.type === "status"
        ? getDevice(source.deviceId).then((value) => { if (active) setDevice(value); })
        : source.telemetryKey
          ? getTelemetryHistory(source.telemetryKey, { deviceId: source.deviceId, range: timeRange??dashboardTimeRange??widget.settings.timeRange??"24h", interval: "hour", aggregation: "average" }).then((value) => {
              if (active) setRecords(value.points.map((point, index) => ({ id: `${point.timestamp}-${index}`, deviceId: source.deviceId, key: source.telemetryKey, value: point.value, unit: value.unit ?? "", recordedAt: point.timestamp })));
            })
          : Promise.resolve();
      request.catch(() => { if (active) setError("Unable to load widget data."); }).finally(() => { if (active) setLoading(false); });
    }, 0);
    return () => { active = false; window.clearTimeout(timer); };
  }, [source?.deviceId, source?.telemetryKey, widget.type,widget.settings.timeRange,timeRange,dashboardTimeRange]);

  const latest = records.at(-1) ?? null;
  let content: React.ReactNode = null;
  if (widget.type === "metric") content = <MetricWidget value={latest?.value ?? null} label={source?.telemetryKey} unit={latest?.unit ?? source?.unit} />;
  else if (widget.type === "chart") content = <ChartWidget records={records} type={widget.settings.chartType} />;
  else if (widget.type === "gauge" && latest) content = <GaugeWidget value={latest.value} min={widget.settings.minimum} max={widget.settings.maximum} unit={latest.unit ?? source?.unit} />;
  else if (widget.type === "table") content = <TableWidget records={records} />;
  else if (widget.type === "status" && device) content = <StatusWidget status={device.status === "online" ? "online" : device.status === "maintenance" ? "warning" : "offline"} label={device.status} />;
  else if (widget.type === "device" && device) content = <DeviceWidget device={device} />;
  else if(widget.type==="global_device_summary"&&globalData)content=<div className="grid h-full grid-cols-2 gap-2">{([["Total",globalData.devices.total],["Online",globalData.devices.online],["Offline",globalData.devices.offline],["Organizations",globalData.organizations.total]] as [string,number][]).map(([label,value])=><div key={label} className="flex flex-col items-center justify-center rounded-[8px] border border-[var(--ds-border-subtle)] bg-[var(--ds-card-alt)] p-2 text-center shadow-[inset_0_1px_1px_var(--ds-inset-shadow)]"><strong className="bg-gradient-to-br from-[var(--ds-text)] to-[var(--ds-primary-soft)] bg-clip-text text-xl font-bold text-transparent tabular-nums" data-numeric>{value}</strong><span className="text-[9.5px] font-semibold uppercase tracking-[0.12em] text-[var(--ds-text-subtle)]">{label}</span></div>)}</div>;
  else if(widget.type==="global_failure_summary"&&globalData)content=<div className="grid h-full grid-cols-2 gap-2">{([["Events",globalData.operationalWindow.errors],["Crashes",globalData.operationalWindow.crashes],["Firmware",globalData.operationalWindow.failedFirmwareDeployments],["Webhooks",globalData.operationalWindow.failedWebhookDeliveries]] as [string,number][]).map(([label,value])=><div key={label} className="flex flex-col items-center justify-center rounded-[8px] border border-[var(--ds-border-subtle)] bg-[var(--ds-card-alt)] p-2 text-center shadow-[inset_0_1px_1px_var(--ds-inset-shadow)]"><strong className="bg-gradient-to-br from-[var(--ds-text)] to-[var(--ds-accent-soft)] bg-clip-text text-xl font-bold text-transparent tabular-nums" data-numeric>{value}</strong><span className="text-[9.5px] font-semibold uppercase tracking-[0.12em] text-[var(--ds-text-subtle)]">{label}</span></div>)}</div>;
  else if(widget.type==="label")content=<p className={`break-words ${widget.settings.fontStyle==="medium"?"font-medium":widget.settings.fontStyle==="bold"||!widget.settings.fontStyle?"font-bold":widget.settings.fontStyle==="italic"?"italic":"font-normal"}`} style={{fontSize:`${widget.settings.fontSize??24}px`,lineHeight:1.2}}>{widget.settings.staticValue||"Label"} {source?.unit}</p>;
  else if(widget.type==="device_count"){const onlineCount=fleetDevices.filter(d=>d.status==="online").length;content=<div className="flex h-full flex-col justify-center gap-2"><p className="bg-gradient-to-br from-[var(--ds-text)] to-[var(--ds-primary-soft)] bg-clip-text text-[34px] font-bold leading-none tracking-tight text-transparent tabular-nums" data-numeric>{fleetDevices.length}</p><div className="flex flex-wrap items-center gap-1.5 text-[11px]"><span className="inline-flex items-center gap-1.5 rounded-full border border-[var(--ds-border-subtle)] bg-[var(--ds-card-alt)] px-2 py-0.5 font-medium text-[var(--ds-success)]"><span aria-hidden className="h-1.5 w-1.5 rounded-full bg-[var(--ds-success)] shadow-[0_0_6px_1px_var(--ds-success)]"/>{onlineCount} online</span><span className="inline-flex items-center gap-1.5 rounded-full border border-[var(--ds-border-subtle)] bg-[var(--ds-card-alt)] px-2 py-0.5 font-medium text-[var(--ds-text-muted)]"><span aria-hidden className="h-1.5 w-1.5 rounded-full bg-[var(--ds-text-subtle)]"/>{fleetDevices.length-onlineCount} offline</span></div></div>;}
  else if(widget.type==="device_table")content=fleetDevices.length?<div className="max-h-64 overflow-auto rounded-[8px] border border-[var(--ds-border-subtle)]"><table className="w-full border-collapse text-left text-xs"><thead><tr className="bg-[var(--ds-card-alt)] text-[9.5px] font-semibold uppercase tracking-[0.12em] text-[var(--ds-text-subtle)]"><th className="px-2.5 py-2">Device</th><th className="px-2.5 py-2">Status</th><th className="px-2.5 py-2">Last seen</th></tr></thead><tbody>{fleetDevices.slice(0,widget.settings.rowLimit??25).map(item=><tr key={item.id} className="border-t border-[var(--ds-border-subtle)] transition-colors hover:bg-[var(--ds-primary-surface)]"><td className="px-2.5 py-2 font-medium text-[var(--ds-text)]">{item.name}</td><td className="px-2.5 py-2"><span className="inline-flex items-center gap-1.5 text-[var(--ds-text-muted)]"><span aria-hidden className={`h-1.5 w-1.5 rounded-full ${item.status==="online"?"bg-[var(--ds-success)] shadow-[0_0_5px_1px_var(--ds-success)]":"bg-[var(--ds-text-subtle)]"}`}/>{item.status}</span></td><td className="px-2.5 py-2 text-[var(--ds-text-muted)]">{item.lastSeen?new Date(item.lastSeen).toLocaleString():"Never"}</td></tr>)}</tbody></table></div>:null;
  else if(widget.type==="device_connection_map")content=fleetDevices.length?<div role="img" aria-label="Authorized Device connection statuses" className="grid grid-cols-2 gap-2">{fleetDevices.slice(0,50).map(item=><div key={item.id} className="flex items-center gap-2 rounded-[8px] border border-[var(--ds-border-subtle)] bg-[var(--ds-card-alt)] p-2 text-xs shadow-[inset_0_1px_1px_var(--ds-inset-shadow)]"><span aria-hidden className={`h-2 w-2 shrink-0 rounded-full ${item.status==="online"?"bg-[var(--ds-success)] shadow-[0_0_6px_1px_var(--ds-success)]":"bg-[var(--ds-text-subtle)]"}`}/><span className="min-w-0"><span className="block truncate font-medium text-[var(--ds-text)]">{item.name}</span><span className="block text-[10px] uppercase tracking-[0.08em] text-[var(--ds-text-subtle)]">{item.status}</span></span></div>)}</div>:null;
  else if(widget.type==="geo_map")content=<GeomapWidget devices={fleetDevices}/>;
  else if(widget.type==="image_map")content=<ImageMapWidget devices={fleetDevices} editable={editable} onMarkersChange={markers=>useDashboardStore.getState().updateWidget(widget.id,{settings:{...widget.settings,markers}})} backgroundImageUrl={widget.settings.imageAssetId?dashboardMapAssetUrl(widget.settings.imageAssetId):undefined} markers={widget.settings.markers}/>;
  else if(widget.type==="switch"&&latest){const checked=Number(latest.value)>0;content=<div className="flex h-full flex-col items-start justify-center gap-2.5"><button type="button" role="switch" aria-checked={checked} disabled className={`relative inline-flex h-8 w-14 shrink-0 rounded-full border transition-colors ${checked?"border-transparent":"border-[var(--ds-border)] bg-[var(--ds-card-alt)] shadow-[inset_0_2px_3px_var(--ds-inset-shadow)]"}`} style={checked?{background:"linear-gradient(135deg, var(--ds-primary), var(--ds-primary-strong))",boxShadow:"inset 0 1px 2px rgb(0 0 0 / .2), 0 0 14px -2px var(--ds-primary-glow)"}:undefined}><span aria-hidden className={`absolute top-1 h-6 w-6 rounded-full bg-white transition-all ${checked?"left-7":"left-1"}`} style={{boxShadow:"0 2px 5px rgb(0 0 0 / .35), inset 0 1px 1px rgb(255 255 255 / .9)"}}/></button><p className="text-xs font-semibold text-[var(--ds-text)]">Current value: {checked?"On":"Off"}</p><p className="text-[11px] text-[var(--ds-text-subtle)]">Read-only: no supported writable Device parameter transport.</p></div>}
  else if(widget.type==="slider"&&latest){const sMin=widget.settings.minimum??0;const sMax=widget.settings.maximum??100;const sPct=Math.max(0,Math.min(100,((Number(latest.value)-sMin)/((sMax-sMin)||1))*100));content=<div className="flex h-full flex-col justify-center gap-2.5"><input aria-label="Read-only Device value" type="range" disabled value={latest.value} min={sMin} max={sMax} className="iot-range w-full" style={{background:`linear-gradient(to right, var(--ds-primary-strong) 0%, var(--ds-primary-soft) ${sPct}%, var(--ds-card-alt) ${sPct}%)`}}/><p className="text-xs font-semibold text-[var(--ds-text)] tabular-nums" data-numeric>Current value: {latest.value} {latest.unit??source?.unit}</p><p className="text-[11px] text-[var(--ds-text-subtle)]">Read-only: no supported writable Device parameter transport.</p></div>}
  else if(widget.type==="metrics_over_time")content=<ChartWidget records={records} type={widget.settings.chartType}/>;
  else if(widget.type==="metric_by_devices")content=<div className="space-y-1.5">{fleetDevices.slice(0,10).map(item=><div key={item.id} className="flex items-center justify-between gap-2 rounded-[7px] border border-[var(--ds-border-subtle)] bg-[var(--ds-card-alt)] px-2.5 py-1.5 text-xs"><span className="flex min-w-0 items-center gap-2"><span aria-hidden className={`h-1.5 w-1.5 shrink-0 rounded-full ${item.status==="online"?"bg-[var(--ds-success)] shadow-[0_0_5px_1px_var(--ds-success)]":"bg-[var(--ds-text-subtle)]"}`}/><span className="truncate font-medium text-[var(--ds-text)]">{item.name}</span></span><span className="shrink-0 text-[10px] font-semibold uppercase tracking-[0.08em] text-[var(--ds-text-muted)]">{item.status}</span></div>)}</div>;
  else if(widget.type==="event_count_tile")content=<div className="flex h-full flex-col justify-center gap-2"><p className="bg-gradient-to-br from-[var(--ds-text)] to-[var(--ds-accent-soft)] bg-clip-text text-[34px] font-bold leading-none tracking-tight text-transparent tabular-nums" data-numeric>{fleetEvents.length}</p><span className="inline-flex w-fit items-center gap-1.5 rounded-full border border-[var(--ds-accent-outline)] bg-[var(--ds-accent-surface)] px-2 py-0.5 text-[11px] font-semibold text-[var(--ds-accent)]"><span aria-hidden className="h-1.5 w-1.5 rounded-full bg-[var(--ds-accent)]"/>events in range</span></div>;
  else if(widget.type==="latest_events")content=<div className="max-h-64 space-y-0.5 overflow-auto">{fleetEvents.slice(0,widget.settings.rowLimit??10).map(item=><div key={item.id} className="flex items-start gap-2.5 border-b border-[var(--ds-border-subtle)] px-1 py-2 text-xs last:border-0"><span aria-hidden className="mt-1 h-2 w-2 shrink-0 rounded-full bg-[var(--ds-accent)] shadow-[0_0_6px_1px_var(--ds-accent-outline)]"/><span className="min-w-0"><strong className="block truncate font-semibold text-[var(--ds-text)]">{item.title||item.eventType}</strong><span className="block text-[10px] text-[var(--ds-text-subtle)]">{new Date(item.occurredAt).toLocaleString()}</span></span></div>)}</div>;
  else if(["event_count_chart","events_by_organization","events_by_device","events_by_template"].includes(widget.type)) {const groups=new Map<string,number>();fleetEvents.forEach(item=>{const key=widget.type==="events_by_organization"?item.organization.name:widget.type==="events_by_device"?(item.device?.name||"Organization event"):widget.type==="events_by_template"?(item.device?.template?.name||"No template"):item.eventType;groups.set(key,(groups.get(key)||0)+1)});content=<div role="img" aria-label={widget.settings.title} className="space-y-2">{[...groups].slice(0,10).map(([label,count])=><div key={label} className="text-xs"><span className="flex justify-between text-[var(--ds-text-muted)]"><span>{label}</span><strong className="tabular-nums text-[var(--ds-text)]" data-numeric>{count}</strong></span><span className="mt-1 block h-2 rounded-full" style={{width:`${Math.max(4,count/Math.max(1,fleetEvents.length)*100)}%`,background:"linear-gradient(90deg, var(--ds-primary-strong), var(--ds-primary-soft))",boxShadow:"0 0 8px -1px var(--ds-primary-glow)"}}/></div>)}</div>}
  else if(["events_over_time","events_breakdown_over_time"].includes(widget.type))content=<ChartWidget records={fleetEvents.slice().reverse().map((item,index)=>({id:item.id,deviceId:item.device?.id||"organization",key:item.eventType,value:index+1,unit:"events",recordedAt:item.occurredAt}))} type="line"/>;
  else if(widget.type==="activations")content=<ChartWidget records={activations.slice().reverse().map((item,index)=>({id:item.id,deviceId:item.device?.id||"provisioning",key:"activation",value:index+1,unit:"activations",recordedAt:item.completedAt||item.updatedAt}))} type="line"/>;
  const registered=hasWidgetRenderer(String(widget.type));
  const requiresSource=["metric","chart","gauge","table","status","device","switch","slider","metrics_over_time"].includes(widget.type) && widget.settings.sourceMode === undefined;
  return <DashboardWidget title={widget.settings.title || "Untitled widget"} loading={registered&&loading} error={registered?error:undefined} empty={!registered||widget.available===false||(requiresSource&&!source?.deviceId)||!content} emptyText={!registered?`Unsupported widget type: ${String(widget.type)}. An editor may remove it safely.`:widget.available===false?"Access unavailable. Protected widget data is no longer available.":requiresSource&&!source?.deviceId?"Widget not configured. Select an authorized Device source.":"No data returned for this widget."} editable={editable} onComment={onComment}>{content}</DashboardWidget>;
}
