<?php
namespace Tests\Feature;use App\Models\Device;use App\Models\DeviceAccessAssignment;use App\Models\Organization;use App\Models\User;use App\Models\UserMonitoredDevice;use Illuminate\Foundation\Testing\RefreshDatabase;use Tests\TestCase;
class AdminMonitoredDevicesTest extends TestCase{use RefreshDatabase;
 private function user(Organization $o,bool $admin=false):User{return User::factory()->create(['organization_id'=>$o->id,'role'=>'staff','platform_role'=>$admin?'platform_admin':null,'status'=>'active']);}
 private function device(Organization $o,string $name,string $status='offline'):Device{return $o->devices()->create(['name'=>$name,'external_id'=>str($name)->slug().'-'.uniqid(),'type'=>'sensor','protocol'=>'mqtt','status'=>$status]);}
 public function test_preference_api_is_platform_admin_only_regardless_of_device_access():void{$o=Organization::create(['name'=>'Org','slug'=>'monitor-auth']);$staff=$this->user($o);$admin=$this->user($o,true);$device=$this->device($o,'Pump');$this->getJson('/api/admin/monitored-devices')->assertUnauthorized();foreach(['viewer','full_access'] as $level){DeviceAccessAssignment::updateOrCreate(['device_id'=>$device->id,'user_id'=>$staff->id],['access_level'=>$level]);$this->actingAs($staff)->getJson('/api/admin/monitored-devices')->assertForbidden();$this->actingAs($staff)->postJson('/api/admin/monitored-devices',['device_id'=>$device->id])->assertForbidden();}$this->actingAs($admin)->getJson('/api/admin/monitored-devices')->assertOk();}
 public function test_admin_can_idempotently_monitor_current_organization_device_without_assignment_or_injection():void{$a=Organization::create(['name'=>'A','slug'=>'monitor-a']);$b=Organization::create(['name'=>'B','slug'=>'monitor-b']);$admin=$this->user($a,true);$other=$this->user($b,true);$foreign=$this->device($b,'Foreign','online');$this->actingAs($admin)->postJson('/api/admin/monitored-devices',['device_id'=>$foreign->id])->assertNotFound();$device=$this->device($a,'Local','online');$payload=['device_id'=>$device->id,'user_id'=>$other->id,'access_level'=>'full_access'];$this->actingAs($admin)->postJson('/api/admin/monitored-devices',$payload)->assertCreated()->assertJsonPath('monitored',true);$this->actingAs($admin)->postJson('/api/admin/monitored-devices',$payload)->assertCreated();$this->assertDatabaseCount('user_monitored_devices',1);$this->assertDatabaseHas('user_monitored_devices',['user_id'=>$admin->id,'device_id'=>$device->id]);$this->assertDatabaseCount('device_access_assignments',0);}
 public function test_multi_admin_preferences_are_private_and_independent():void{$o=Organization::create(['name'=>'Org','slug'=>'monitor-private']);$a=$this->user($o,true);$b=$this->user($o,true);$one=$this->device($o,'One');$two=$this->device($o,'Two');$three=$this->device($o,'Three');foreach([$one,$two] as $d)UserMonitoredDevice::create(['user_id'=>$a->id,'device_id'=>$d->id]);foreach([$two,$three] as $d)UserMonitoredDevice::create(['user_id'=>$b->id,'device_id'=>$d->id]);$this->actingAs($a)->getJson('/api/admin/monitored-devices')->assertJsonPath('summary.total',2)->assertJsonFragment(['name'=>'One'])->assertJsonMissing(['name'=>'Three']);$this->actingAs($b)->deleteJson("/api/admin/monitored-devices/{$one->id}")->assertNoContent();$this->assertDatabaseHas('user_monitored_devices',['user_id'=>$a->id,'device_id'=>$one->id]);$this->actingAs($a)->deleteJson("/api/admin/monitored-devices/{$two->id}")->assertNoContent();$this->assertDatabaseHas('user_monitored_devices',['user_id'=>$b->id,'device_id'=>$two->id]);}
 public function test_dashboard_summary_contains_only_personal_monitored_subset_within_admin_organization():void{$a=Organization::create(['name'=>'A','slug'=>'monitor-summary-a']);$b=Organization::create(['name'=>'B','slug'=>'monitor-summary-b']);$admin=$this->user($a,true);$online=$this->device($a,'Online','online');$offline=$this->device($a,'Offline');$hidden=$this->device($b,'Foreign','online');UserMonitoredDevice::create(['user_id'=>$admin->id,'device_id'=>$online->id]);UserMonitoredDevice::create(['user_id'=>$admin->id,'device_id'=>$offline->id]);$this->actingAs($admin)->getJson('/api/admin/monitored-devices')->assertOk()->assertJsonPath('summary.total',2)->assertJsonPath('summary.online',1)->assertJsonPath('summary.offline',1)->assertJsonFragment(['name'=>'Online'])->assertJsonFragment(['name'=>'Offline'])->assertJsonMissing(['name'=>'Foreign']);$this->actingAs($admin)->getJson('/api/admin/operations/overview')->assertJsonPath('devices.total',2)->assertJsonMissing(['name'=>$hidden->name]);}
 public function test_empty_dashboard_and_device_deletion_cascade_are_clean():void{$o=Organization::create(['name'=>'Org','slug'=>'monitor-cascade']);$admin=$this->user($o,true);$device=$this->device($o,'Gone');$this->actingAs($admin)->getJson('/api/admin/monitored-devices')->assertJsonPath('summary.total',0)->assertJsonCount(0,'devices');UserMonitoredDevice::create(['user_id'=>$admin->id,'device_id'=>$device->id]);$device->delete();$this->assertDatabaseCount('user_monitored_devices',0);$this->actingAs($admin)->getJson('/api/admin/monitored-devices')->assertJsonPath('summary.total',0);}
 public function test_removing_monitoring_does_not_revoke_global_access_and_detail_reports_state():void{$o=Organization::create(['name'=>'Org','slug'=>'monitor-separation']);$admin=$this->user($o,true);$staff=$this->user($o);$device=$this->device($o,'Pump');$assignment=DeviceAccessAssignment::create(['device_id'=>$device->id,'user_id'=>$staff->id,'access_level'=>'viewer']);UserMonitoredDevice::create(['user_id'=>$admin->id,'device_id'=>$device->id]);$this->actingAs($admin)->getJson("/api/admin/devices/{$device->id}")->assertJsonPath('data.device.isMonitored',true);$this->actingAs($admin)->deleteJson("/api/admin/monitored-devices/{$device->id}")->assertNoContent();$this->actingAs($admin)->getJson("/api/admin/devices/{$device->id}")->assertOk()->assertJsonPath('data.device.isMonitored',false);$this->assertDatabaseHas('device_access_assignments',['id'=>$assignment->id,'access_level'=>'viewer']);}
}
