<?php
namespace Tests\Feature;
use App\Exceptions\FeatureNotAvailableException;use App\Models\Dashboard;use App\Models\Device;use App\Models\Organization;use App\Models\PaymentEvent;use App\Models\Plan;use App\Models\Subscription;use App\Models\User;use App\Services\Billing\BillingEntitlementService;use App\Services\Billing\BillingVerificationService;use App\Services\Billing\VerifiedPaymentEventData;use Illuminate\Foundation\Testing\RefreshDatabase;use Tests\TestCase;
class CorePlatformTest extends TestCase{
 use RefreshDatabase;
 private function plan(string $id='free',array $overrides=[]):Plan{return Plan::create(array_merge(['id'=>$id,'name'=>ucfirst($id),'description'=>'','price'=>0,'currency'=>'USD','interval'=>'monthly','features'=>['devices.management','dashboard.customize'],'device_limit'=>1,'user_limit'=>2,'dashboard_limit'=>1,'active'=>true,'is_default'=>$id==='free'],$overrides));}
 private function member(Organization $o,string $role='owner',?string $platform=null):User{return User::factory()->create(['organization_id'=>$o->id,'role'=>$role,'platform_role'=>$platform]);}
 private function subscribed(Plan $p,string $role='owner'):array{$o=Organization::create(['name'=>'Org','slug'=>'org-'.uniqid()]);$u=$this->member($o,$role);$s=$o->subscriptions()->create(['plan_id'=>$p->id,'status'=>'active','current_period_start'=>now(),'current_period_end'=>$p->interval==='lifetime'?null:now()->addMonth()]);return [$o,$u,$s];}
 public function test_registration_creates_free_subscription():void{$this->plan();$response=$this->postJson('/api/auth/register',['name'=>'New','email'=>'new@example.com','password'=>'password123'])->assertCreated();$org=Organization::find($response->json('user.organizationId'));$this->assertSame('free',$org->subscription->plan_id);$this->assertSame('active',$org->subscription->status);}
 public function test_user_retrieves_only_own_organization():void{$a=Organization::create(['name'=>'A','slug'=>'a']);$b=Organization::create(['name'=>'B','slug'=>'b']);$u=$this->member($a);$this->actingAs($u)->getJson('/api/organization')->assertOk()->assertJson(['id'=>(string)$a->id])->assertJsonMissing(['id'=>(string)$b->id]);}
 public function test_platform_admin_can_access_admin_billing():void{$u=User::factory()->create(['platform_role'=>'platform_admin']);$this->actingAs($u)->getJson('/api/admin/billing/stats')->assertOk();}
 public function test_device_contract_scoping_and_limit():void{$p=$this->plan();[$o,$u]=$this->subscribed($p);$other=Organization::create(['name'=>'Other','slug'=>'other']);$foreign=Device::create(['organization_id'=>$other->id,'name'=>'Foreign','type'=>'sensor','external_id'=>'foreign','protocol'=>'mqtt']);$payload=['name'=>'Mine','type'=>'sensor','serialNumber'=>'mine','protocol'=>'mqtt'];$this->actingAs($u)->postJson('/api/devices',$payload)->assertCreated()->assertJsonPath('serialNumber','mine');$this->actingAs($u)->getJson('/api/devices')->assertOk()->assertJsonCount(1);$this->actingAs($u)->getJson('/api/devices/'.$foreign->id)->assertNotFound();$this->actingAs($u)->postJson('/api/devices',[...$payload,'serialNumber'=>'second'])->assertForbidden()->assertJson(['code'=>'BILLING_LIMIT_REACHED']);$id=$o->devices()->first()->id;$this->actingAs($u)->deleteJson('/api/devices/'.$id)->assertNoContent();}
 public function test_free_plan_rejects_premium_feature_and_pro_plan_allows_it():void{$free=$this->plan();[$fo]=$this->subscribed($free);$service=app(BillingEntitlementService::class);$this->assertFalse($service->hasFeature($fo,'analytics.advanced'));$this->expectException(FeatureNotAvailableException::class);$service->requireFeature($fo,'analytics.advanced');}
 public function test_premium_entitlement_and_lifetime_semantics():void{$p=$this->plan('lifetime',['interval'=>'lifetime','price'=>100,'features'=>['analytics.advanced']]);[$o]= $this->subscribed($p);$this->assertTrue(app(BillingEntitlementService::class)->hasFeature($o,'analytics.advanced'));$this->assertNull($o->subscription->current_period_end);}
 public function test_dashboard_contract_and_limit():void{$p=$this->plan();[$o,$u]=$this->subscribed($p);$payload=['name'=>'Main','description'=>'Ops','widgets'=>[]];$id=$this->actingAs($u)->postJson('/api/dashboards',$payload)->assertCreated()->json('id');$this->actingAs($u)->getJson('/api/dashboards/'.$id)->assertOk()->assertJson(['name'=>'Main','widgets'=>[]]);$this->actingAs($u)->putJson('/api/dashboards/'.$id,[...$payload,'name'=>'Updated'])->assertOk()->assertJson(['name'=>'Updated']);$this->actingAs($u)->postJson('/api/dashboards',$payload)->assertForbidden();$this->actingAs($u)->deleteJson('/api/dashboards/'.$id)->assertNoContent();$this->assertSame(0,$o->dashboards()->count());}
 public function test_verified_payment_event_is_idempotent():void{$p=$this->plan('pro',['price'=>49,'features'=>['analytics.advanced']]);$o=Organization::create(['name'=>'Pay','slug'=>'pay']);$event=new VerifiedPaymentEventData('evt-1','payment.succeeded','txn-1',(string)$o->id,$p->id,true,49,'USD','paid');$service=app(BillingVerificationService::class);$service->handle($event);$service->handle($event);$this->assertSame(1,PaymentEvent::count());$this->assertSame(1,Subscription::where('organization_id',$o->id)->count());}
 public function test_billing_mutation_requires_permission():void{$p=$this->plan();[, $viewer]=$this->subscribed($p,'viewer');$this->actingAs($viewer)->postJson('/api/billing/subscription/cancel')->assertForbidden();}
 public function test_lifetime_cannot_be_cancelled():void{$p=$this->plan('life',['interval'=>'lifetime','price'=>100]);[, $owner]=$this->subscribed($p);$this->actingAs($owner)->postJson('/api/billing/subscription/cancel')->assertStatus(422);}
 public function test_invalid_token_is_rejected():void{$this->withToken('invalid-token')->getJson('/api/organization')->assertUnauthorized();}
}
