<?php
namespace Tests\Feature;
use App\Models\{Dashboard,DashboardWidget,DeviceAccessAssignment,Organization,ResourceRevision,User};use Illuminate\Foundation\Testing\RefreshDatabase;use Illuminate\Support\Str;use Tests\TestCase;
final class DashboardCollaborationPermissionsTest extends TestCase
{
 use RefreshDatabase;
 private function fixture():array{$org=Organization::create(['name'=>'Dashboard Editors','slug'=>'dashboard-editors']);$owner=User::factory()->create(['organization_id'=>$org->id,'role'=>'staff','status'=>'active']);$editor=User::factory()->create(['organization_id'=>$org->id,'role'=>'staff','status'=>'active']);$device=$org->devices()->create(['name'=>'Restricted Source','external_id'=>'restricted-source','type'=>'sensor','protocol'=>'mqtt','status'=>'online']);DeviceAccessAssignment::create(['device_id'=>$device->id,'user_id'=>$owner->id,'access_level'=>'full_access']);$dashboard=Dashboard::create(['organization_id'=>$org->id,'owner_user_id'=>$owner->id,'name'=>'Shared Operations','scope_type'=>'personal','created_by'=>$owner->id,'updated_by'=>$owner->id]);$widget=DashboardWidget::create(['id'=>(string)Str::uuid(),'dashboard_id'=>$dashboard->id,'widget_type'=>'metric','title'=>'Pressure','layout'=>['x'=>0,'y'=>0,'w'=>3,'h'=>3],'configuration'=>['deviceId'=>$device->id,'telemetryKey'=>'pressure','unit'=>'psi'],'position'=>0]);return compact('owner','editor','device','dashboard','widget');}
 private function grant(array $f,string $permission='edit'):int{$id=$this->actingAs($f['owner'])->postJson('/api/shares',['resource_type'=>'dashboard','resource_id'=>$f['dashboard']->id,'recipient_id'=>$f['editor']->id,'permission'=>$permission])->assertCreated()->json('data.id');$this->actingAs($f['editor'])->postJson("/api/shares/{$id}/accept")->assertOk();return $id;}
 public function test_edit_collaborator_updates_canonical_dashboard_without_learning_or_erasing_restricted_source():void{$f=$this->fixture();$this->grant($f);$current=$this->actingAs($f['editor'])->getJson("/api/dashboards/{$f['dashboard']->id}")->assertOk()->assertJsonPath('canEdit',true)->assertJsonPath('canShare',false)->assertJsonPath('widgets.0.available',false)->assertJsonPath('widgets.0.settings.datasource',null)->json();$current['name']='Edited together';$current['widgets'][0]['layout']['x']=2;$saved=$this->actingAs($f['editor'])->putJson("/api/dashboards/{$f['dashboard']->id}",$current)->assertOk()->assertJsonPath('name','Edited together');$this->assertDatabaseHas('dashboard_widgets',['id'=>$f['widget']->id,'dashboard_id'=>$f['dashboard']->id]);$f['widget']->refresh();$this->assertSame((string)$f['device']->id,(string)$f['widget']->configuration['deviceId']);$this->assertSame('pressure',$f['widget']->configuration['telemetryKey']);$this->assertSame(2,$f['widget']->layout['x']);$this->assertSame(2,ResourceRevision::where(['resource_type'=>'dashboard','resource_id'=>$f['dashboard']->id])->count());$this->actingAs($f['editor'])->postJson('/api/shares',['resource_type'=>'dashboard','resource_id'=>$f['dashboard']->id,'recipient_id'=>$f['owner']->id,'permission'=>'view'])->assertNotFound();}
 public function test_stale_editor_save_is_rejected_and_owner_can_downgrade_immediately():void{$f=$this->fixture();$share=$this->grant($f);$stale=$this->actingAs($f['editor'])->getJson("/api/dashboards/{$f['dashboard']->id}")->assertOk()->json();$owner=$this->actingAs($f['owner'])->getJson("/api/dashboards/{$f['dashboard']->id}")->json();$owner['name']='Owner change';$this->actingAs($f['owner'])->putJson("/api/dashboards/{$f['dashboard']->id}",$owner)->assertOk();$stale['name']='Stale edit';$this->actingAs($f['editor'])->putJson("/api/dashboards/{$f['dashboard']->id}",$stale)->assertStatus(409)->assertJsonPath('code','revision_conflict');$this->actingAs($f['owner'])->patchJson("/api/shares/{$share}/permission",['permission'=>'view'])->assertOk()->assertJsonPath('data.final_permission','view');$this->actingAs($f['editor'])->putJson("/api/dashboards/{$f['dashboard']->id}",$owner)->assertNotFound();$this->actingAs($f['editor'])->getJson("/api/dashboards/{$f['dashboard']->id}")->assertOk()->assertJsonPath('canEdit',false);}
}