<?php
namespace Tests\Feature;
use App\Models\{CollaborationThread,Dashboard,DashboardWidget,Device,DeviceAccessAssignment,Notification,Organization,User};
use Illuminate\Foundation\Testing\RefreshDatabase;use Illuminate\Support\Str;use Tests\TestCase;
final class DashboardCommentsTest extends TestCase{
use RefreshDatabase;
private function context():array{$o=Organization::create(['name'=>'Dashboard Comments','slug'=>'dashboard-comments']);$owner=User::factory()->create(['organization_id'=>$o->id,'role'=>'staff','status'=>'active']);$viewer=User::factory()->create(['organization_id'=>$o->id,'role'=>'staff','status'=>'active']);$d=Device::create(['organization_id'=>$o->id,'name'=>'Pump','external_id'=>'comment-pump','type'=>'sensor','protocol'=>'mqtt']);foreach([$owner,$viewer] as $u)DeviceAccessAssignment::create(['device_id'=>$d->id,'user_id'=>$u->id,'access_level'=>$u->is($owner)?'full_access':'viewer']);$dash=Dashboard::create(['organization_id'=>$o->id,'device_id'=>$d->id,'name'=>'Pump Dashboard','scope_type'=>'device']);$w=DashboardWidget::create(['id'=>(string)Str::uuid(),'dashboard_id'=>$dash->id,'widget_type'=>'metric','title'=>'Pressure','layout'=>['x'=>0,'y'=>0,'w'=>3,'h'=>3],'configuration'=>[],'position'=>0]);return[$owner,$viewer,$d,$dash,$w];}
public function test_viewer_can_create_and_filter_root_and_stable_widget_threads():void{[$owner,$viewer,$d,,$w]=$this->context();$root=$this->actingAs($viewer)->postJson("/api/collaboration/device/{$d->id}/threads",['anchor_type'=>'resource','body'=>'Dashboard discussion'])->assertCreated()->json('id');$widget=$this->actingAs($viewer)->postJson("/api/collaboration/device/{$d->id}/threads",['anchor_type'=>'dashboard_widget','anchor_key'=>$w->id,'body'=>'Widget discussion'])->assertCreated()->assertJsonPath('anchor.key',$w->id)->json('id');$this->actingAs($viewer)->getJson("/api/collaboration/device/{$d->id}/threads?anchor_type=resource")->assertOk()->assertJsonCount(1,'data')->assertJsonPath('data.0.id',(string)$root);$this->actingAs($viewer)->getJson("/api/collaboration/device/{$d->id}/threads?anchor_type=dashboard_widget&anchor_key={$w->id}")->assertOk()->assertJsonCount(1,'data')->assertJsonPath('data.0.id',(string)$widget);$this->actingAs($viewer)->patchJson("/api/devices/{$d->id}",['name'=>'No'])->assertForbidden();}
public function test_widget_move_rename_and_removal_preserve_thread_but_removed_anchor_cannot_be_reused():void{[$owner,$viewer,$d,,$w]=$this->context();$id=$this->actingAs($viewer)->postJson("/api/collaboration/device/{$d->id}/threads",['anchor_type'=>'dashboard_widget','anchor_key'=>$w->id,'body'=>'Keep history'])->json('id');$w->update(['title'=>'Renamed','layout'=>['x'=>4,'y'=>2,'w'=>6,'h'=>4]]);$this->actingAs($viewer)->getJson("/api/collaboration/threads/$id")->assertOk()->assertJsonPath('anchor.key',$w->id);$widgetId=$w->id;$w->delete();$this->assertDatabaseHas('collaboration_threads',['id'=>$id,'anchor_key'=>$widgetId]);$this->actingAs($viewer)->getJson("/api/collaboration/threads/$id")->assertOk();$this->actingAs($viewer)->postJson("/api/collaboration/device/{$d->id}/threads",['anchor_type'=>'dashboard_widget','anchor_key'=>$widgetId,'body'=>'Cannot resurrect'])->assertUnprocessable();}
public function test_widget_mention_deep_link_is_exact_and_revocation_removes_it():void{[$owner,$viewer,$d,,$w]=$this->context();$this->actingAs($owner)->postJson("/api/collaboration/device/{$d->id}/threads",['anchor_type'=>'dashboard_widget','anchor_key'=>$w->id,'body'=>'Please inspect','mention_ids'=>[$viewer->id]])->assertCreated();$notice=Notification::where('user_id',$viewer->id)->where('type','comment.mentioned')->firstOrFail();$this->actingAs($viewer)->getJson('/api/notifications')->assertOk()->assertJsonPath('data.0.deepLink',"/app/devices/{$d->id}?tab=dashboard&thread={$notice->data['thread_id']}&widget={$w->id}");DeviceAccessAssignment::where(['device_id'=>$d->id,'user_id'=>$viewer->id])->delete();$this->actingAs($viewer)->getJson('/api/notifications')->assertOk()->assertJsonPath('data.0.deepLink',null)->assertJsonCount(0,'data.0.actions');}
}