<?php

namespace Tests\Feature;

use App\Models\{DashboardWidget,Device,DeviceAccessAssignment,Organization,User};
use App\Services\Dashboard\DashboardWidgetRegistry;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Str;
use Tests\TestCase;

final class DashboardWidgetLibraryTest extends TestCase
{
 use RefreshDatabase;
 private function context():array{$org=Organization::create(['name'=>'Widgets','slug'=>'widgets']);$user=User::factory()->create(['organization_id'=>$org->id,'role'=>'staff','status'=>'active']);$device=$org->devices()->create(['name'=>'Pump','external_id'=>'widget-pump','type'=>'sensor','protocol'=>'mqtt','status'=>'online']);DeviceAccessAssignment::create(['user_id'=>$user->id,'device_id'=>$device->id,'access_level'=>'full_access']);return[$org,$user,$device];}
 private function widget(Device $device,string $type='metric',?string $id=null):array{$settings=['title'=>'Temperature','datasource'=>['deviceId'=>(string)$device->id,'telemetryKey'=>'temperature','unit'=>'C'],'timeRange'=>'24h'];if($type==='gauge'){$settings['minimum']=0;$settings['maximum']=100;}return['id'=>$id??(string)Str::uuid(),'type'=>$type,'settings'=>$settings,'layout'=>['x'=>0,'y'=>0,'w'=>$type==='gauge'?3:3,'h'=>3]];}
 public function test_registry_definitions_are_complete_contextual_and_safe():void{[,,$device]=$this->context();$registry=app(DashboardWidgetRegistry::class);$personal=$registry->definitions('personal');$deviceTypes=array_column($registry->definitions('device'),'type');$global=array_column($registry->definitions('admin_global'),'type');$required=['switch','slider','label','device_count','device_table','geo_map','image_map','device_connection_map','metrics_over_time','metric_by_devices','event_count_tile','latest_events','event_count_chart','events_over_time','events_breakdown_over_time','events_by_organization','events_by_device','events_by_template','activations'];foreach($required as$type)$this->assertContains($type,array_column($personal,'type'));$this->assertCount(19,$required);$this->assertNotContains('activations',$deviceTypes);$this->assertSame(['global_device_summary','global_failure_summary'],$global);foreach([...$personal,...$registry->definitions('admin_global')] as $definition){$this->assertNotEmpty($definition['description']);$this->assertNotEmpty($definition['category']);$this->assertNotEmpty($definition['dataContract']);$this->assertSame(1,$definition['configSchemaVersion']);$this->assertGreaterThanOrEqual($definition['minWidth'],$definition['defaultLayout']['w']);}$this->expectException(\Illuminate\Validation\ValidationException::class);$registry->definitions('App\\Models\\Dashboard');}
 public function test_frontend_renderer_registry_has_exact_backend_parity():void{$backend=[];foreach(DashboardWidgetRegistry::CONTEXTS as $context)$backend=array_merge($backend,array_column(app(DashboardWidgetRegistry::class)->definitions($context),'type'));$backend=array_values(array_unique($backend));sort($backend);$source=file_get_contents(dirname(base_path()).'/frontend/src/components/dashboard/widgets/widgetRendererRegistry.ts');preg_match_all('/"([a-z_]+)"/',$source,$types);$frontend=array_values(array_unique($types[1]));sort($frontend);$this->assertSame($backend,$frontend);}
 public function test_type_is_immutable_and_foreign_widget_id_cannot_be_reused():void{[$org,$user,$device]=$this->context();$dashboard=$this->actingAs($user)->getJson('/api/dashboards/default')->json();$widget=$this->widget($device);$payload=['name'=>'Mine','widgets'=>[$widget]];$this->actingAs($user)->putJson("/api/dashboards/{$dashboard['id']}",$payload)->assertOk();$changed=$widget;$changed['type']='gauge';$changed['settings']['minimum']=0;$changed['settings']['maximum']=100;$this->actingAs($user)->putJson("/api/dashboards/{$dashboard['id']}",['name'=>'Mine','widgets'=>[$changed]])->assertUnprocessable();$other=User::factory()->create(['organization_id'=>$org->id,'role'=>'staff','status'=>'active']);DeviceAccessAssignment::create(['user_id'=>$other->id,'device_id'=>$device->id,'access_level'=>'viewer']);$otherDashboard=$this->actingAs($other)->getJson('/api/dashboards/default')->json();$this->actingAs($other)->putJson("/api/dashboards/{$otherDashboard['id']}",['name'=>'Other','widgets'=>[$widget]])->assertNotFound();}
 public function test_registered_layout_bounds_duplicate_ids_and_unsafe_settings_are_rejected():void{[, $user,$device]=$this->context();$dashboard=$this->actingAs($user)->getJson('/api/dashboards/default')->json();$gauge=$this->widget($device,'gauge');$gauge['layout']['w']=2;$this->actingAs($user)->putJson("/api/dashboards/{$dashboard['id']}",['name'=>'Mine','widgets'=>[$gauge]])->assertUnprocessable();$metric=$this->widget($device);$this->actingAs($user)->putJson("/api/dashboards/{$dashboard['id']}",['name'=>'Mine','widgets'=>[$metric,$metric]])->assertUnprocessable();$metric['settings']['renderer']='evil';$this->actingAs($user)->putJson("/api/dashboards/{$dashboard['id']}",['name'=>'Mine','widgets'=>[$metric]])->assertUnprocessable();}
 public function test_device_context_rejects_global_widget_and_foreign_source_without_mutation():void{[$org,$user,$device]=$this->context();$foreign=$org->devices()->create(['name'=>'Other','external_id'=>'other-widget','type'=>'sensor','protocol'=>'mqtt']);$current=$this->actingAs($user)->getJson("/api/devices/{$device->id}/dashboard")->json();$global=['id'=>(string)Str::uuid(),'type'=>'global_device_summary','settings'=>['title'=>'Global'],'layout'=>['x'=>0,'y'=>0,'w'=>6,'h'=>3]];$this->actingAs($user)->patchJson("/api/devices/{$device->id}/dashboard",['name'=>'Device','layoutVersion'=>$current['layoutVersion'],'widgets'=>[$global]])->assertUnprocessable();$widget=$this->widget($foreign);$this->actingAs($user)->patchJson("/api/devices/{$device->id}/dashboard",['name'=>'Device','layoutVersion'=>$current['layoutVersion'],'widgets'=>[$widget]])->assertUnprocessable();$this->assertDatabaseCount('dashboard_widgets',0);}
}
