<?php
namespace Tests\Feature;
use App\Models\Device;use App\Models\DeviceAccessAssignment;use App\Models\DeviceTemplate;use App\Models\Organization;use App\Models\User;use Illuminate\Foundation\Testing\RefreshDatabase;use Tests\TestCase;
class FleetTest extends TestCase { use RefreshDatabase;
 private function user(Organization $org,bool $admin=false):User{return User::factory()->create(['organization_id'=>$org->id,'role'=>'staff','platform_role'=>$admin?'platform_admin':null,'status'=>'active']);}
 private function device(Organization $org,string $name,string $status='offline',?DeviceTemplate $template=null):Device{return $org->devices()->create(['name'=>$name,'external_id'=>str($name)->slug().uniqid(),'status'=>$status,'type'=>'sensor','protocol'=>'mqtt','device_template_id'=>$template?->id]);}
 private function assign(User $user,Device $device,string $level):void{DeviceAccessAssignment::create(['user_id'=>$user->id,'device_id'=>$device->id,'access_level'=>$level]);}
 public function test_staff_fleet_is_assignment_scoped_and_summary_does_not_leak_hidden_devices():void{$org=Organization::create(['name'=>'Org','slug'=>'fleet-scope']);$other=Organization::create(['name'=>'Other','slug'=>'fleet-other']);$user=$this->user($org);$viewer=$this->device($org,'Viewer Device','online');$full=$this->device($org,'Full Device','offline');$hidden=$this->device($org,'Hidden Device','offline');$foreign=$this->device($other,'Foreign Device','online');$this->assign($user,$viewer,'viewer');$this->assign($user,$full,'full_access');$this->getJson('/api/fleet/devices')->assertUnauthorized();$response=$this->actingAs($user)->getJson('/api/fleet/devices')->assertOk()->assertJsonPath('meta.total',2)->assertJsonPath('summary.visibleDevices',2)->assertJsonPath('summary.online',1)->assertJsonPath('summary.offline',1)->assertJsonPath('summary.viewer',1)->assertJsonPath('summary.fullAccess',1);$ids=collect($response->json('data'))->pluck('id');$this->assertTrue($ids->contains((string)$viewer->id));$this->assertTrue($ids->contains((string)$full->id));$this->assertFalse($ids->contains((string)$hidden->id));$this->assertFalse($ids->contains((string)$foreign->id));}
 public function test_filters_search_template_and_access_are_server_side_and_non_leaking():void{$org=Organization::create(['name'=>'Org','slug'=>'fleet-filters']);$user=$this->user($org);$template=$org->deviceTemplates()->create(['name'=>'Pump Schema','created_by'=>$user->id]);$viewer=$this->device($org,'Cold Sensor','online');$full=$this->device($org,'Main Pump','offline',$template);$hidden=$this->device($org,'Unique Hidden Pump','offline',$template);$this->assign($user,$viewer,'viewer');$this->assign($user,$full,'full_access');$this->actingAs($user)->getJson('/api/fleet/devices?status=offline&access_level=full_access&device_template_id='.$template->id.'&search=Main')->assertOk()->assertJsonPath('meta.total',1)->assertJsonPath('data.0.id',(string)$full->id)->assertJsonPath('summary.visibleDevices',1)->assertJsonPath('summary.templatesRepresented',1);$this->actingAs($user)->getJson('/api/fleet/devices?search=Unique%20Hidden')->assertOk()->assertJsonPath('meta.total',0)->assertJsonPath('summary.visibleDevices',0);$this->actingAs($user)->getJson('/api/fleet/devices?access_level=viewer')->assertOk()->assertJsonPath('meta.total',1)->assertJsonPath('data.0.id',(string)$viewer->id);$this->actingAs($user)->getJson('/api/fleet/devices?device_template_id=999999')->assertOk()->assertJsonPath('meta.total',0);}
 public function test_pagination_sorting_and_filter_allowlists_are_enforced():void{$org=Organization::create(['name'=>'Org','slug'=>'fleet-page']);$user=$this->user($org);for($i=1;$i<=30;$i++){$device=$this->device($org,sprintf('Device %02d',$i));$this->assign($user,$device,$i%2?'viewer':'full_access');}$this->actingAs($user)->getJson('/api/fleet/devices?per_page=25&page=2&sort=name&direction=asc')->assertOk()->assertJsonCount(5,'data')->assertJsonPath('meta.total',30)->assertJsonPath('meta.current_page',2);foreach(['per_page=500','sort=raw_sql','direction=sideways','status=critical','access_level=operator'] as $query)$this->actingAs($user)->getJson('/api/fleet/devices?'.$query)->assertUnprocessable();}
 public function test_platform_admin_app_fleet_stays_in_operational_organization_context():void{$a=Organization::create(['name'=>'A','slug'=>'fleet-admin-a']);$b=Organization::create(['name'=>'B','slug'=>'fleet-admin-b']);$admin=$this->user($a,true);$own=$this->device($a,'Own');$this->device($b,'Foreign');$this->actingAs($admin)->getJson('/api/fleet/devices')->assertOk()->assertJsonPath('meta.total',1)->assertJsonPath('data.0.id',(string)$own->id)->assertJsonPath('data.0.access.label','Admin')->assertJsonPath('data.0.access.level',null);}
 public function test_fleet_selection_adds_no_persistence_or_mutation_endpoint():void{$org=Organization::create(['name'=>'Org','slug'=>'fleet-selection']);$user=$this->user($org);$device=$this->device($org,'Device');$this->assign($user,$device,'full_access');$this->actingAs($user)->postJson('/api/fleet/devices',['device_ids'=>[$device->id]])->assertMethodNotAllowed();$this->assertDatabaseCount('device_access_assignments',1);}
}
