<?php
namespace Tests\Feature;
use App\Models\{Notification,Organization,ResourceShareRequest,User};use Illuminate\Foundation\Testing\RefreshDatabase;use Tests\TestCase;
final class NotificationStateTest extends TestCase
{
 use RefreshDatabase;
 private function user(Organization$o):User{return User::factory()->create(['organization_id'=>$o->id,'status'=>'active']);}
 private function notification(User$u,array$values=[]):Notification{return Notification::create(['organization_id'=>$u->organization_id,'user_id'=>$u->id,'type'=>'device.created','category'=>'updates','title'=>'Notice','message'=>'Notice','severity'=>'info',...$values]);}
 public function test_read_and_unread_are_idempotent_and_recipient_only():void{$o=Organization::create(['name'=>'State','slug'=>'state']);$u=$this->user($o);$other=$this->user($o);$n=$this->notification($u);$this->actingAs($other)->postJson("/api/notifications/{$n->id}/read")->assertNotFound();$first=$this->actingAs($u)->postJson("/api/notifications/{$n->id}/read")->assertOk()->json('data.readAt');$this->actingAs($u)->postJson("/api/notifications/{$n->id}/read")->assertOk()->assertJsonPath('data.readAt',$first);$this->actingAs($u)->postJson("/api/notifications/{$n->id}/unread")->assertOk()->assertJsonPath('data.isRead',false);}
 public function test_dismiss_preserves_unread_and_restore_only_clears_dismissal():void{$o=Organization::create(['name'=>'Dismiss','slug'=>'dismiss']);$u=$this->user($o);$n=$this->notification($u);$this->actingAs($u)->postJson("/api/notifications/{$n->id}/dismiss")->assertNoContent();$this->assertDatabaseHas('notifications',['id'=>$n->id,'read_at'=>null]);$this->actingAs($u)->postJson("/api/notifications/{$n->id}/restore")->assertOk()->assertJsonPath('data.isRead',false)->assertJsonPath('data.isDismissed',false);}
 public function test_dismissed_history_is_paginated_and_excluded_from_active_and_bell():void{$o=Organization::create(['name'=>'History','slug'=>'history']);$u=$this->user($o);$active=$this->notification($u,['title'=>'Active']);$dismissed=$this->notification($u,['title'=>'Dismissed','dismissed_at'=>now()]);$this->actingAs($u)->getJson('/api/notifications')->assertOk()->assertJsonCount(1,'data')->assertJsonPath('data.0.id',(string)$active->id);$this->actingAs($u)->getJson('/api/notifications?filter=dismissed')->assertOk()->assertJsonCount(1,'data')->assertJsonPath('data.0.id',(string)$dismissed->id);$this->actingAs($u)->getJson('/api/notifications/unread-count')->assertOk()->assertJsonPath('count',1);}
 public function test_mark_all_read_updates_only_active_current_recipient_rows():void{$o=Organization::create(['name'=>'Bulk','slug'=>'bulk']);$u=$this->user($o);$other=$this->user($o);$active=$this->notification($u);$dismissed=$this->notification($u,['dismissed_at'=>now()]);$foreign=$this->notification($other);$this->actingAs($u)->postJson('/api/notifications/read-all')->assertOk()->assertJsonPath('updated',1);$this->assertNotNull($active->refresh()->read_at);$this->assertNull($dismissed->refresh()->read_at);$this->assertNull($foreign->refresh()->read_at);}
 public function test_read_and_dismiss_do_not_change_pending_share_workflow_or_live_actions():void{$o=Organization::create(['name'=>'Workflow','slug'=>'workflow']);$sender=$this->user($o);$u=$this->user($o);$share=ResourceShareRequest::create(['resource_type'=>'location','resource_id'=>10,'sender_user_id'=>$sender->id,'recipient_user_id'=>$u->id,'requested_permission'=>'view','status'=>'pending_recipient','active_key'=>'location:10:'.$u->id]);$n=Notification::create(['organization_id'=>$o->id,'user_id'=>$u->id,'type'=>'access.requested','category'=>'requests','resource_type'=>'location','resource_id'=>10,'data'=>['share_request_id'=>$share->id],'title'=>'Share','message'=>'Share','severity'=>'info']);$this->actingAs($u)->postJson("/api/notifications/{$n->id}/read")->assertOk()->assertJsonPath('data.actionStatus','required');$this->actingAs($u)->postJson("/api/notifications/{$n->id}/dismiss")->assertNoContent();$this->assertSame('pending_recipient',$share->refresh()->status);}
 public function test_read_dismiss_restore_do_not_reorder_original_delivery():void{$o=Organization::create(['name'=>'Order','slug'=>'order']);$u=$this->user($o);$old=$this->notification($u,['created_at'=>now()->subHour(),'updated_at'=>now()->subHour()]);$new=$this->notification($u);$this->actingAs($u)->postJson("/api/notifications/{$old->id}/read")->assertOk();$this->actingAs($u)->getJson('/api/notifications')->assertJsonPath('data.0.id',(string)$new->id);$this->actingAs($u)->postJson("/api/notifications/{$old->id}/dismiss")->assertNoContent();$this->actingAs($u)->postJson("/api/notifications/{$old->id}/restore")->assertOk();$this->actingAs($u)->getJson('/api/notifications')->assertJsonPath('data.0.id',(string)$new->id);}
}
