<?php
namespace Tests\Feature;
use App\Models\Notification;use App\Models\Organization;use App\Models\User;use Illuminate\Foundation\Testing\RefreshDatabase;use Tests\TestCase;
final class NotificationPreferenceTest extends TestCase
{
 use RefreshDatabase;
 private function user(Organization $organization):User{return User::factory()->create(['organization_id'=>$organization->id,'role'=>'staff','status'=>'active']);}
 public function test_preferences_are_current_user_only_sparse_and_registry_driven():void{$organization=Organization::create(['name'=>'Preferences','slug'=>'preferences']);$user=$this->user($organization);$other=$this->user($organization);$this->actingAs($user)->getJson('/api/profile/notifications')->assertOk()->assertJsonPath('scope','account')->assertJsonPath('channels.0.key','in_app');$this->actingAs($user)->patchJson('/api/profile/notifications',['categories'=>['updates'=>false],'user_id'=>$other->id])->assertUnprocessable();$this->actingAs($user)->patchJson('/api/profile/notifications',['categories'=>['updates'=>false]])->assertOk();$this->assertFalse($user->refresh()->notification_settings['categories']['updates']);$this->assertNull($other->refresh()->notification_settings);}
 public function test_optional_delivery_is_suppressed_without_changing_history():void{$organization=Organization::create(['name'=>'Optional','slug'=>'optional']);$user=$this->user($organization);Notification::create(['organization_id'=>$organization->id,'user_id'=>$user->id,'type'=>'revision.available','category'=>'updates','title'=>'Old','message'=>'Old','severity'=>'info']);$this->actingAs($user)->patchJson('/api/profile/notifications',['rules'=>['revision.available'=>false]])->assertOk();Notification::create(['organization_id'=>$organization->id,'user_id'=>$user->id,'type'=>'revision.available','category'=>'updates','title'=>'New','message'=>'New','severity'=>'info']);$this->assertDatabaseCount('notifications',1);$this->assertDatabaseHas('notifications',['title'=>'Old']);}
 public function test_mandatory_delivery_cannot_be_disabled():void{$organization=Organization::create(['name'=>'Mandatory','slug'=>'mandatory']);$user=$this->user($organization);$this->actingAs($user)->patchJson('/api/profile/notifications',['categories'=>['updates'=>false],'rules'=>['device.access_revoked'=>false]])->assertUnprocessable();$this->actingAs($user)->patchJson('/api/profile/notifications',['categories'=>['updates'=>false]])->assertOk();Notification::create(['organization_id'=>$organization->id,'user_id'=>$user->id,'type'=>'device.access_revoked','category'=>'updates','title'=>'Revoked','message'=>'Revoked','severity'=>'info']);$this->assertDatabaseHas('notifications',['user_id'=>$user->id,'type'=>'device.access_revoked']);}
 public function test_explicit_reminder_bypasses_optional_update_preference():void{$organization=Organization::create(['name'=>'Reminder','slug'=>'reminder-pref']);$user=$this->user($organization);$this->actingAs($user)->patchJson('/api/profile/notifications',['rules'=>['revision.available'=>false]])->assertOk();Notification::create(['organization_id'=>$organization->id,'user_id'=>$user->id,'type'=>'revision.available','category'=>'updates','data'=>['reminder'=>true],'title'=>'Reminder','message'=>'Reminder','severity'=>'info']);$this->assertDatabaseHas('notifications',['user_id'=>$user->id,'title'=>'Reminder']);}
 public function test_reset_restores_registry_defaults_without_backfill():void{$organization=Organization::create(['name'=>'Reset','slug'=>'reset-pref']);$user=$this->user($organization);$this->actingAs($user)->patchJson('/api/profile/notifications',['categories'=>['mentions'=>false]])->assertOk();$this->actingAs($user)->deleteJson('/api/profile/notifications')->assertOk()->assertJsonPath('categories.3.override',null);$this->assertNull($user->refresh()->notification_settings);$this->assertDatabaseCount('notifications',0);}
}
