<?php
namespace Tests\Feature;
use App\Models\Device;use App\Models\DeviceAccessAssignment;use App\Models\OperationalEvent;use App\Models\Organization;use App\Models\User;use App\Services\Automation\AutomationDefinitionService;use App\Services\Automation\AutomationExecutionService;use Illuminate\Foundation\Testing\RefreshDatabase;use Tests\TestCase;
class OperationalEventTest extends TestCase { use RefreshDatabase;
 private function user(Organization $org,string $level='staff',bool $admin=false):User{return User::factory()->create(['organization_id'=>$org->id,'role'=>$level,'platform_role'=>$admin?'platform_admin':null,'status'=>'active']);}
 private function device(Organization $org,string $name):Device{return $org->devices()->create(['name'=>$name,'external_id'=>str($name)->slug().uniqid(),'type'=>'sensor','protocol'=>'mqtt']);}
 private function assign(User $user,Device $device,string $level):void{DeviceAccessAssignment::create(['user_id'=>$user->id,'device_id'=>$device->id,'access_level'=>$level]);}
 private function event(Organization $org,?Device $device,string $message):OperationalEvent{return OperationalEvent::create(['organization_id'=>$org->id,'device_id'=>$device?->id,'device_bound'=>$device!==null,'source'=>'automation','event_type'=>'automation_execution_failed','severity'=>'error','title'=>'Automation failed','message'=>$message,'context'=>['reason'=>'action_failed'],'occurred_at'=>now()]);}
 public function test_staff_event_scope_allows_viewer_and_full_access_without_count_search_or_filter_leaks():void{$org=Organization::create(['name'=>'Org','slug'=>'event-scope']);$viewer=$this->user($org);$full=$this->user($org);$assigned=$this->device($org,'Assigned');$hidden=$this->device($org,'Hidden');$this->assign($viewer,$assigned,'viewer');$this->assign($full,$assigned,'full_access');$visible=$this->event($org,$assigned,'Visible occurrence');$this->event($org,$hidden,'Unique hidden secret text');$this->getJson('/api/operational-events')->assertUnauthorized();foreach([$viewer,$full] as $user)$this->actingAs($user)->getJson('/api/operational-events')->assertOk()->assertJsonPath('meta.total',1)->assertJsonPath('data.0.id',(string)$visible->id);$this->actingAs($viewer)->getJson('/api/operational-events?search=Unique%20hidden')->assertOk()->assertJsonPath('meta.total',0);$this->actingAs($viewer)->getJson("/api/operational-events?device_id={$hidden->id}")->assertOk()->assertJsonPath('meta.total',0);$this->actingAs($viewer)->getJson("/api/operational-events/{$visible->id}")->assertOk();}
 public function test_cross_org_and_admin_organization_boundaries_are_explicit():void{$a=Organization::create(['name'=>'A','slug'=>'event-a']);$b=Organization::create(['name'=>'B','slug'=>'event-b']);$staff=$this->user($a);$admin=$this->user($a,'staff',true);$ownDevice=$this->device($a,'Own');$own=$this->event($a,$ownDevice,'Own event');$device=$this->device($b,'Foreign');$foreign=$this->event($b,$device,'Foreign event');$this->assign($staff,$ownDevice,'viewer');$this->actingAs($staff)->getJson("/api/operational-events/{$foreign->id}")->assertNotFound();$this->actingAs($staff)->getJson('/api/admin/operational-events')->assertForbidden();$this->actingAs($admin)->getJson('/api/admin/operational-events')->assertOk()->assertJsonPath('meta.total',1)->assertJsonPath('data.0.id',(string)$own->id);$this->actingAs($admin)->getJson("/api/admin/operational-events/{$foreign->id}")->assertNotFound();}
 public function test_failed_automation_execution_creates_one_real_sanitized_event():void{$org=Organization::create(['name'=>'Org','slug'=>'event-automation']);$user=$this->user($org,'owner');$definition=['name'=>'Failure test','enabled'=>true,'trigger'=>['type'=>'manual'],'conditions'=>['logic'=>'AND','conditions'=>[]],'actions'=>[['type'=>'notification','payload'=>['message'=>'Test']]]];$automation=app(AutomationDefinitionService::class)->create($org,$user,$definition);$automation->actions()->first()->update(['type'=>'unsupported_runtime_action']);$automation->unsetRelation('actions');app(\App\Services\ResourceRevisionService::class)->recordAutomation($automation,$user,'Synthetic failure fixture');$execution=app(AutomationExecutionService::class)->execute($automation,'manual',['token'=>'should-never-appear']);$this->assertSame('failed',$execution->status);$this->assertDatabaseHas('operational_events',['organization_id'=>$org->id,'automation_id'=>$automation->id,'automation_execution_id'=>$execution->id,'event_type'=>'automation_execution_failed','severity'=>'error']);$this->assertSame(1,OperationalEvent::count());}
 public function test_api_sanitizes_context_paths_secrets_and_message_content():void{$org=Organization::create(['name'=>'Org','slug'=>'event-sanitize']);$user=$this->user($org);$event=OperationalEvent::create(['organization_id'=>$org->id,'device_bound'=>false,'source'=>'automation','event_type'=>'automation_execution_failed','severity'=>'error','title'=>'Failure','message'=>'token=abc C:\\private\\vendor\\trace.php','context'=>['api_key'=>'secret','detail'=>'Bearer xyz /var/app/vendor/file.php'],'occurred_at'=>now()]);$json=$this->actingAs($user)->getJson("/api/operational-events/{$event->id}")->assertOk()->json();$encoded=json_encode($json);$this->assertStringNotContainsString('abc',$encoded);$this->assertStringNotContainsString('xyz',$encoded);$this->assertStringNotContainsString('vendor',$encoded);$this->assertStringContainsString('[REDACTED]',$encoded);}
 public function test_events_are_immutable_and_device_automation_deletion_preserves_admin_history():void{$org=Organization::create(['name'=>'Org','slug'=>'event-delete']);$user=$this->user($org);$admin=$this->user($org,'staff',true);$device=$this->device($org,'Pump');$event=$this->event($org,$device,'Historical event');$this->actingAs($user)->postJson('/api/operational-events',['message'=>'Fake'])->assertMethodNotAllowed();$this->actingAs($user)->patchJson("/api/operational-events/{$event->id}",['message'=>'Changed'])->assertMethodNotAllowed();$this->actingAs($user)->deleteJson("/api/operational-events/{$event->id}")->assertMethodNotAllowed();$device->delete();$this->assertDatabaseHas('operational_events',['id'=>$event->id,'device_id'=>null,'device_bound'=>true]);$this->actingAs($user)->getJson("/api/operational-events/{$event->id}")->assertNotFound();$this->actingAs($admin)->getJson("/api/admin/operational-events/{$event->id}")->assertOk();}
 public function test_automation_deletion_sets_reference_null_without_deleting_history():void{$org=Organization::create(['name'=>'Org','slug'=>'event-automation-delete']);$user=$this->user($org,'owner');$automation=$org->automations()->create(['name'=>'Delete me','enabled'=>false,'status'=>'draft','created_by'=>$user->id,'updated_by'=>$user->id]);$event=OperationalEvent::create(['organization_id'=>$org->id,'device_bound'=>false,'automation_id'=>$automation->id,'source'=>'automation','event_type'=>'automation_execution_failed','severity'=>'error','message'=>'Historical failure','occurred_at'=>now()]);$automation->delete();$this->assertDatabaseHas('operational_events',['id'=>$event->id,'automation_id'=>null]);}
}
