<?php
namespace Tests\Feature;
use App\Models\{CollaborationComment,CollaborationThread,Device,DeviceAccessAssignment,Organization,ResourceRevision,ResourceShareRequest,User};use App\Services\{ResourceRevisionSectionResolver,ResourceRevisionService,ResourceSectionRegistry};use Illuminate\Foundation\Testing\RefreshDatabase;use Illuminate\Validation\ValidationException;use Tests\TestCase;
final class Phase69SectionActivityTest extends TestCase{use RefreshDatabase;
 private function context():array{$o=Organization::create(['name'=>'Sections','slug'=>'sections']);$u=User::factory()->create(['organization_id'=>$o->id,'role'=>'staff','status'=>'active']);$d=Device::create(['organization_id'=>$o->id,'created_by'=>$u->id,'name'=>'Pump','external_id'=>'sections-pump','type'=>'sensor','protocol'=>'mqtt']);DeviceAccessAssignment::create(['user_id'=>$u->id,'device_id'=>$d->id,'access_level'=>'full_access']);return[$o,$u,$d];}
 private function revision(Device$d,User$u,int$n,array$sections,?ResourceRevision$parent=null):ResourceRevision{return ResourceRevision::create(['resource_type'=>'device','resource_id'=>$d->id,'revision_number'=>$n,'parent_revision_id'=>$parent?->id,'created_by'=>$u->id,'change_summary'=>'server summary','snapshot_schema_version'=>1,'snapshot'=>['metadata'=>['name'=>$d->name],'dashboard'=>null,'parameters'=>[]],'changed_sections'=>$sections,'checksum'=>hash('sha256',$d->id.':'.$n),'created_at'=>now()->addSeconds($n)]);}
 public function test_registry_labels_order_aliases_and_rejects_unknown_or_fqcn():void{$r=app(ResourceSectionRegistry::class);$this->assertSame(['metadata','dashboard','parameters'],$r->normalize('device',['parameters','metadata','metadata','device_dashboard']));$this->assertSame('Parameters',$r->section('device','parameters')['label']);foreach(['unknown',Device::class]as$key){try{$r->validate('device',$key);$this->fail('Invalid section accepted');}catch(ValidationException){$this->addToAssertionCount(1);}}$this->assertArrayNotHasKey('blueprint',$r->metadata());}
 public function test_dashboard_structural_resolver_returns_one_deterministic_multi_section_classification():void{$r=app(ResourceRevisionSectionResolver::class);$before=['metadata'=>['name'=>'A'],'dashboard'=>['widgets'=>[['id'=>'w1','type'=>'metric','title'=>'Old','layout'=>['x'=>0,'y'=>0,'w'=>2,'h'=>2],'configuration'=>['deviceId'=>'1','telemetryKey'=>'temp','chartType'=>'line']]]],'parameters'=>[]];$after=$before;$after['metadata']['name']='B';$after['dashboard']['widgets'][0]['title']='New';$after['dashboard']['widgets'][0]['layout']['x']=2;$after['dashboard']['widgets'][0]['configuration']['telemetryKey']='pressure';$this->assertSame(['metadata','layout','widgets','sources'],$r->resolve('dashboard',$before,$after));}
 public function test_activity_filters_same_revision_without_duplicate_rows():void{[, $u,$d]=$this->context();$base=$this->revision($d,$u,1,['metadata','dashboard','parameters']);$revision=$this->revision($d,$u,2,['parameters','metadata','metadata'],$base);$all=$this->actingAs($u)->getJson('/api/activity?resource_type=device')->assertOk();$event=collect($all->json('data'))->firstWhere('id','revision:'.$revision->id);$this->assertSame(['metadata','parameters'],$event['sectionKeys']);$this->assertCount(1,collect($all->json('data'))->where('id','revision:'.$revision->id));foreach(['metadata','parameters']as$section)$this->actingAs($u)->getJson("/api/activity?resource_type=device&section=$section")->assertOk()->assertJsonCount(1,'data')->assertJsonPath('data.0.id','revision:'.$revision->id);$this->actingAs($u)->getJson('/api/activity?section=parameters')->assertUnprocessable();$this->actingAs($u)->getJson('/api/activity?resource_type=dashboard&section=parameters')->assertUnprocessable();}
 public function test_comment_anchor_mapping_is_coarse_historical_and_body_independent():void{[, $u,$d]=$this->context();foreach([['parameter','parameters'],['dashboard_widget','dashboard']]as[$anchor,$section]){$t=CollaborationThread::create(['resource_type'=>'device','resource_id'=>$d->id,'anchor_type'=>$anchor,'anchor_key'=>'deleted-anchor','created_by'=>$u->id]);CollaborationComment::create(['thread_id'=>$t->id,'body'=>'metadata sources arbitrary keywords','created_by'=>$u->id]);$this->actingAs($u)->getJson("/api/collaboration/resources/device/$d->id/activity?section=$section")->assertOk()->assertJsonFragment(['sectionKeys'=>[$section]]);} $root=CollaborationThread::create(['resource_type'=>'device','resource_id'=>$d->id,'anchor_type'=>'resource','created_by'=>$u->id]);CollaborationComment::create(['thread_id'=>$root->id,'body'=>'parameters dashboard','created_by'=>$u->id]);$event=collect($this->actingAs($u)->getJson("/api/collaboration/resources/device/$d->id/activity")->json('data'))->firstWhere('metadata.threadId',(string)$root->id);$this->assertSame([],$event['sectionKeys']);}
 public function test_governance_events_remain_resource_level():void{[, $u,$d]=$this->context();ResourceShareRequest::create(['resource_type'=>'device','resource_id'=>$d->id,'sender_user_id'=>$u->id,'recipient_user_id'=>$u->id,'requested_permission'=>'viewer','status'=>'pending_recipient']);$event=collect($this->actingAs($u)->getJson('/api/activity?resource_type=device&category=sharing')->assertOk()->json('data'))->first();$this->assertSame([],$event['sectionKeys']);}
 public function test_client_changed_sections_and_active_tab_cannot_override_server_attribution():void{[, $u,$d]=$this->context();app(ResourceRevisionService::class)->recordDevice($d,$u,'baseline');$this->actingAs($u)->patchJson("/api/devices/$d->id",['name'=>'Renamed','changed_sections'=>['publication'],'tab'=>'parameters'])->assertOk();$latest=ResourceRevision::where(['resource_type'=>'device','resource_id'=>$d->id])->latest('revision_number')->firstOrFail();$this->assertSame(['metadata'],$latest->changed_sections);}
}