<?php
namespace Tests\Feature;
use App\Models\{CollaborationComment,CollaborationThread,Device,DeviceAccessAssignment,Organization,ResourceRevision,User};use App\Services\{CollaborationIdentitySummary,ResourceAttributionRegistry};use Illuminate\Foundation\Testing\RefreshDatabase;use Illuminate\Validation\ValidationException;use Tests\TestCase;
final class Phase70CreatorContributorIdentityTest extends TestCase{use RefreshDatabase;
 private function context():array{$org=Organization::create(['name'=>'Identity','slug'=>'identity']);$creator=User::factory()->create(['organization_id'=>$org->id,'role'=>'staff','status'=>'active','name'=>'Creator']);$contributor=User::factory()->create(['organization_id'=>$org->id,'role'=>'staff','status'=>'active','name'=>'Contributor']);$viewer=User::factory()->create(['organization_id'=>$org->id,'role'=>'staff','status'=>'active','name'=>'Viewer']);$device=Device::create(['organization_id'=>$org->id,'created_by'=>$creator->id,'name'=>'Pump','external_id'=>'identity-pump','type'=>'sensor','protocol'=>'mqtt']);foreach([$creator,$contributor,$viewer]as$user)DeviceAccessAssignment::create(['user_id'=>$user->id,'device_id'=>$device->id,'access_level'=>'viewer']);return[$org,$creator,$contributor,$viewer,$device];}
 private function revision(Device$device,User$user,int$number):ResourceRevision{return ResourceRevision::create(['resource_type'=>'device','resource_id'=>$device->id,'revision_number'=>$number,'created_by'=>$user->id,'change_summary'=>'Canonical configuration updated','snapshot_schema_version'=>1,'snapshot'=>['metadata'=>['name'=>$device->name]],'changed_sections'=>['metadata'],'checksum'=>hash('sha256',"$device->id:$number"),'created_at'=>now()->addSeconds($number)]);}
 public function test_creator_and_distinct_meaningful_revision_contributors_are_factual():void{[, $creator,$contributor,$viewer,$device]=$this->context();$this->revision($device,$creator,1);$this->revision($device,$contributor,2);$this->revision($device,$contributor,3);$response=$this->actingAs($viewer)->getJson("/api/collaboration/resources/device/$device->id/attribution")->assertOk()->assertJsonPath('creator.displayName','Creator')->assertJsonPath('creator.state','active')->assertJsonCount(1,'contributors')->assertJsonPath('contributors.0.displayName','Contributor')->assertJsonPath('contributorSemantics','meaningful_configuration_revision_authors');$this->assertArrayNotHasKey('email',$response->json('creator'));$this->assertArrayNotHasKey('permission',$response->json('contributors.0'));}
 public function test_commenter_is_not_configuration_contributor():void{[, $creator,,$viewer,$device]=$this->context();$this->revision($device,$creator,1);$thread=CollaborationThread::create(['resource_type'=>'device','resource_id'=>$device->id,'anchor_type'=>'resource','created_by'=>$viewer->id]);CollaborationComment::create(['thread_id'=>$thread->id,'body'=>'Discussion only','created_by'=>$viewer->id]);$this->actingAs($viewer)->getJson("/api/collaboration/resources/device/$device->id/attribution")->assertOk()->assertJsonCount(0,'contributors');}
 public function test_historical_creator_or_contributor_status_never_authorizes_resource():void{[, $creator,$contributor,,$device]=$this->context();$this->revision($device,$creator,1);$this->revision($device,$contributor,2);DeviceAccessAssignment::where('device_id',$device->id)->whereIn('user_id',[$creator->id,$contributor->id])->delete();$this->actingAs($creator)->getJson("/api/collaboration/resources/device/$device->id/attribution")->assertNotFound();$this->actingAs($contributor)->getJson("/api/collaboration/resources/device/$device->id/attribution")->assertNotFound();}
 public function test_inactive_historical_identity_is_minimal_and_registry_rejects_unknown_type():void{[,,$contributor,$viewer,$device]=$this->context();$this->revision($device,$contributor,2);$contributor->update(['status'=>'inactive']);$this->actingAs($viewer)->getJson("/api/collaboration/resources/device/$device->id/attribution")->assertOk()->assertJsonPath('contributors.0.state','inactive')->assertJsonMissingPath('contributors.0.email');try{app(ResourceAttributionRegistry::class)->creatorColumn('App\\Models\\Device');$this->fail('Arbitrary type accepted');}catch(ValidationException){$this->addToAssertionCount(1);}}
}