<?php
namespace Tests\Feature;
use App\Models\{AutomationExecution,CollaborationComment,CollaborationThread,Device,DeviceAccessAssignment,OperationalEvent,Organization,ResourceRevision,User};use App\Services\CollaborationActivityRegistry;use Illuminate\Foundation\Testing\RefreshDatabase;use Illuminate\Validation\ValidationException;use Tests\TestCase;
final class Phase68CollaborationActivityTest extends TestCase{use RefreshDatabase;
 private function setupUser():array{$o=Organization::create(['name'=>'Activity Org','slug'=>'activity-org']);$u=User::factory()->create(['organization_id'=>$o->id,'role'=>'staff','status'=>'active']);$d=Device::create(['organization_id'=>$o->id,'created_by'=>$u->id,'name'=>'Pump','external_id'=>'activity-pump','type'=>'sensor','protocol'=>'mqtt']);DeviceAccessAssignment::create(['user_id'=>$u->id,'device_id'=>$d->id,'access_level'=>'viewer']);return[$o,$u,$d];}
 public function test_registry_is_allowlisted_and_rejects_fqcn_and_unknown_filters(){ $r=app(CollaborationActivityRegistry::class);$this->assertSame('changes',$r->event('resource.revised')['category']);$this->expectException(ValidationException::class);$r->validateFilters(['resource_type'=>Device::class]);}
 public function test_revision_comment_and_exact_thread_transition_are_safe_resource_level_events(){[, $u,$d]=$this->setupUser();$rev=ResourceRevision::create(['resource_type'=>'device','resource_id'=>$d->id,'revision_number'=>1,'created_by'=>$u->id,'change_summary'=>'secret body ignored','snapshot_schema_version'=>1,'snapshot'=>['password'=>'never-return'],'changed_sections'=>['parameters'],'checksum'=>str_repeat('a',64),'created_at'=>now()->subMinute()]);$thread=CollaborationThread::create(['resource_type'=>'device','resource_id'=>$d->id,'created_by'=>$u->id]);$comment=CollaborationComment::create(['thread_id'=>$thread->id,'body'=>'private comment body','created_by'=>$u->id]);$thread->transitions()->create(['from_status'=>'open','to_status'=>'resolved','actor_id'=>$u->id,'created_at'=>now()]);$res=$this->actingAs($u)->getJson('/api/activity')->assertOk();$this->assertEqualsCanonicalizing(['resource.revised','comment.created','comment.resolved'],collect($res->json('data'))->pluck('eventType')->all());$json=$res->getContent();$this->assertStringNotContainsString('private comment body',$json);$this->assertStringNotContainsString('password',$json);$this->assertSame((string)$rev->id,collect($res->json('data'))->firstWhere('eventType','resource.revised')['metadata']['revisionId']);}
 public function test_current_authorization_removes_historical_events_after_revoke(){[, $u,$d]=$this->setupUser();ResourceRevision::create(['resource_type'=>'device','resource_id'=>$d->id,'revision_number'=>1,'created_by'=>$u->id,'change_summary'=>'Updated','snapshot_schema_version'=>1,'snapshot'=>[],'changed_sections'=>[],'checksum'=>str_repeat('b',64),'created_at'=>now()]);$this->actingAs($u)->getJson('/api/activity')->assertJsonCount(1,'data');DeviceAccessAssignment::where(['user_id'=>$u->id,'device_id'=>$d->id])->delete();$this->actingAs($u)->getJson('/api/activity')->assertOk()->assertJsonCount(0,'data');$this->actingAs($u)->getJson("/api/collaboration/resources/device/{$d->id}/activity")->assertOk()->assertJsonCount(0,'data');}
 public function test_runtime_and_notification_state_are_not_activity_sources(){[$o,$u,$d]=$this->setupUser();OperationalEvent::create(['organization_id'=>$o->id,'device_id'=>$d->id,'event_type'=>'heartbeat','severity'=>'info','title'=>'Runtime','message'=>'Runtime','source'=>'device','occurred_at'=>now()]);$this->actingAs($u)->getJson('/api/activity')->assertOk()->assertJsonCount(0,'data');$routes=collect(app('router')->getRoutes()->getRoutes())->filter(fn($r)=>str_contains($r->uri(),'activity'));$this->assertTrue($routes->every(fn($r)=>in_array('GET',$r->methods(),true)));$this->assertFalse($routes->contains(fn($r)=>str_contains($r->uri(),'read')||str_contains($r->uri(),'dismiss')));}
 public function test_filters_are_server_validated_and_metadata_contains_only_real_registry_keys(){[, $u]=$this->setupUser();$this->actingAs($u)->getJson('/api/activity?category=telemetry')->assertUnprocessable();$this->actingAs($u)->getJson('/api/activity?resource_type=App%5CModels%5CDevice')->assertUnprocessable();$this->actingAs($u)->getJson('/api/activity/metadata')->assertOk()->assertJsonPath('categories.0','changes')->assertJsonPath('categories.1','comments')->assertJsonMissing(['automation_execution']);}
}