<?php
namespace Tests\Feature;
use App\Models\Device;use App\Models\DeviceAccessAssignment;use App\Models\Organization;use App\Models\ResourceDraft;use App\Models\ResourceRevision;use App\Models\User;use App\Services\ResourceRevisionStateService;use Illuminate\Foundation\Testing\RefreshDatabase;use Illuminate\Support\Str;use Tests\TestCase;
class ResourceDraftConflictTest extends TestCase{use RefreshDatabase;
 public function test_second_dashboard_editor_gets_structured_conflict_without_mutation():void{[$d,$a,$b,$base]=$this->context();$payload=$this->dashboard($base->id,'First');$this->actingAs($a)->patchJson("/api/devices/$d->id/dashboard",$payload)->assertOk();$latest=ResourceRevision::where('resource_id',$d->id)->latest('revision_number')->first();$count=ResourceRevision::count();$this->actingAs($b)->patchJson("/api/devices/$d->id/dashboard",$this->dashboard($base->id,'Stale'))->assertConflict()->assertJsonPath('code','revision_conflict')->assertJsonPath('submittedBaseRevision.id',(string)$base->id)->assertJsonPath('latestRevision.id',(string)$latest->id)->assertJsonPath('canSaveDraft',true);$this->assertSame($count,ResourceRevision::count());$this->assertDatabaseHas('dashboards',['device_id'=>$d->id,'name'=>'First']);}
 public function test_parameter_stale_save_is_atomic():void{[$d,$a,$b,$base]=$this->context();$this->actingAs($a)->postJson("/api/devices/$d->id/parameters",['name'=>'Temperature','key'=>'temperature','data_type'=>'number','baseRevisionId'=>$base->id])->assertCreated();$count=ResourceRevision::count();$this->actingAs($b)->postJson("/api/devices/$d->id/parameters",['name'=>'Pressure','key'=>'pressure','data_type'=>'number','baseRevisionId'=>$base->id])->assertConflict()->assertJsonPath('code','revision_conflict');$this->assertSame($count,ResourceRevision::count());$this->assertDatabaseMissing('device_parameters',['device_id'=>$d->id,'key'=>'pressure']);}
 public function test_personal_draft_is_idempotent_private_safe_and_does_not_pull():void{[$d,$a,$b,$base]=$this->context();$url="/api/collaboration/resources/device/$d->id/draft";$snapshot=$base->snapshot;$snapshot['metadata']['authorization']='secret';$snapshot['telemetry']=['value'=>10];$before=ResourceRevision::count();$this->actingAs($a)->putJson($url,['base_revision_id'=>$base->id,'snapshot'=>$snapshot,'user_id'=>$b->id])->assertUnprocessable();$this->actingAs($a)->putJson($url,['base_revision_id'=>$base->id,'snapshot'=>$snapshot])->assertOk()->assertJsonMissing(['authorization'=>'secret'])->assertJsonMissing(['value'=>10]);$this->actingAs($a)->putJson($url,['base_revision_id'=>$base->id,'snapshot'=>$snapshot])->assertOk();$this->assertDatabaseCount('resource_drafts',1);$this->assertSame($before,ResourceRevision::count());$this->actingAs($b)->getJson($url)->assertOk()->assertJsonPath('draft',null);}
 public function test_viewer_revocation_and_foreign_base_do_not_grant_draft_access():void{[$d,$a,$b,$base,$org]=$this->context();DeviceAccessAssignment::where(['device_id'=>$d->id,'user_id'=>$b->id])->update(['access_level'=>'viewer']);$this->actingAs($b)->putJson("/api/collaboration/resources/device/$d->id/draft",['base_revision_id'=>$base->id,'snapshot'=>$base->snapshot])->assertNotFound();$other=Device::create(['organization_id'=>$org->id,'name'=>'Other','type'=>'sensor','serial_number'=>'OTHER39','protocol'=>'mqtt']);$foreign=ResourceRevision::create(['resource_type'=>'device','resource_id'=>$other->id,'revision_number'=>1,'snapshot_schema_version'=>1,'snapshot'=>$base->snapshot,'changed_sections'=>['metadata'],'checksum'=>Str::random(64),'created_at'=>now()]);$this->actingAs($a)->putJson("/api/collaboration/resources/device/$d->id/draft",['base_revision_id'=>$foreign->id,'snapshot'=>$base->snapshot])->assertUnprocessable();DeviceAccessAssignment::where(['device_id'=>$d->id,'user_id'=>$a->id])->delete();$this->actingAs($a)->getJson("/api/collaboration/resources/device/$d->id/draft")->assertNotFound();}
 private function context():array{$org=Organization::create(['name'=>'Plant','slug'=>'plant']);$a=$this->user($org,'a39@test');$b=$this->user($org,'b39@test');$id=$this->actingAs($a)->postJson('/api/devices',['name'=>'Pump','type'=>'sensor','serialNumber'=>'P39','protocol'=>'mqtt'])->assertCreated()->json('id');$d=Device::findOrFail($id);DeviceAccessAssignment::create(['device_id'=>$id,'user_id'=>$b->id,'access_level'=>'full_access']);$base=ResourceRevision::where('resource_id',$id)->firstOrFail();app(ResourceRevisionStateService::class)->initializeGrant($b,$d);return[$d,$a,$b,$base,$org];}
 private function dashboard(int $base,string $name):array{return ['name'=>$name,'description'=>null,'layoutVersion'=>1,'baseRevisionId'=>$base,'widgets'=>[['id'=>(string)Str::uuid(),'type'=>'status','settings'=>['title'=>'Status','datasource'=>['deviceId'=>'1','telemetryKey'=>'']],'layout'=>['x'=>0,'y'=>0,'w'=>3,'h'=>3]]]];}
 private function user(Organization $o,string $email):User{return User::factory()->create(['organization_id'=>$o->id,'email'=>$email,'role'=>'staff','status'=>'active']);}}
