<?php
namespace Tests\Feature;
use App\Models\{Dashboard,Device,DeviceAccessAssignment,Organization,ResourceCollaborator,ResourceShareRequest,User};use Illuminate\Foundation\Testing\RefreshDatabase;use Tests\TestCase;
final class SharingAuthorizationHardeningTest extends TestCase
{
 use RefreshDatabase;
 private function user(Organization$o):User{return User::factory()->create(['organization_id'=>$o->id,'role'=>'staff','status'=>'active']);}
 private function deviceFixture():array{$o=Organization::create(['name'=>'Hardened','slug'=>'hardened']);$sender=$this->user($o);$recipient=$this->user($o);$admin=User::factory()->create(['organization_id'=>$o->id,'role'=>'staff','platform_role'=>'platform_admin','status'=>'active']);$device=Device::create(['organization_id'=>$o->id,'name'=>'Pump','type'=>'sensor','external_id'=>'hardened-pump','protocol'=>'mqtt']);$assignment=DeviceAccessAssignment::create(['device_id'=>$device->id,'user_id'=>$sender->id,'access_level'=>'full_access']);return compact('o','sender','recipient','admin','device','assignment');}
 public function test_device_recipient_acceptance_revalidates_current_sender_authority():void{extract($this->deviceFixture());$id=$this->actingAs($sender)->postJson('/api/shares',['resource_type'=>'device','resource_id'=>$device->id,'recipient_id'=>$recipient->id,'permission'=>'viewer'])->assertCreated()->json('data.id');$assignment->delete();$this->actingAs($recipient)->postJson("/api/shares/{$id}/accept")->assertNotFound();$this->assertDatabaseMissing('device_access_assignments',['device_id'=>$device->id,'user_id'=>$recipient->id]);$this->assertDatabaseHas('resource_share_requests',['id'=>$id,'status'=>'pending_recipient']);}
 public function test_device_admin_approval_revalidates_sender_after_recipient_acceptance():void{extract($this->deviceFixture());$id=$this->actingAs($sender)->postJson('/api/shares',['resource_type'=>'device','resource_id'=>$device->id,'recipient_id'=>$recipient->id,'permission'=>'full_access'])->assertCreated()->json('data.id');$this->actingAs($recipient)->postJson("/api/shares/{$id}/accept")->assertOk();$this->actingAs($admin)->getJson('/api/admin/access-requests')->assertOk()->assertJsonPath('data.0.resource.name','Pump')->assertJsonPath('data.0.recipient.email',$recipient->email);$assignment->delete();$this->actingAs($admin)->postJson("/api/admin/access-requests/{$id}/approve",['permission'=>'viewer'])->assertNotFound();$this->assertDatabaseMissing('device_access_assignments',['device_id'=>$device->id,'user_id'=>$recipient->id]);}
 public function test_document_acceptance_revalidates_current_organization_membership():void{$o=Organization::create(['name'=>'Docs','slug'=>'docs-hard']);$foreign=Organization::create(['name'=>'Foreign','slug'=>'foreign-hard']);$owner=$this->user($o);$recipient=$this->user($o);$dashboard=Dashboard::create(['organization_id'=>$o->id,'owner_user_id'=>$owner->id,'name'=>'Operations','scope_type'=>'personal','created_by'=>$owner->id,'updated_by'=>$owner->id]);$id=$this->actingAs($owner)->postJson('/api/shares',['resource_type'=>'dashboard','resource_id'=>$dashboard->id,'recipient_id'=>$recipient->id,'permission'=>'view'])->assertCreated()->json('data.id');$recipient->update(['organization_id'=>$foreign->id]);$this->actingAs($recipient)->postJson("/api/shares/{$id}/accept")->assertUnprocessable();$this->assertDatabaseMissing('resource_collaborators',['resource_type'=>'dashboard','resource_id'=>$dashboard->id,'user_id'=>$recipient->id]);}
 public function test_stale_weaker_document_request_preserves_stronger_grant():void{$o=Organization::create(['name'=>'Strong','slug'=>'strong-hard']);$owner=$this->user($o);$recipient=$this->user($o);$dashboard=Dashboard::create(['organization_id'=>$o->id,'owner_user_id'=>$owner->id,'name'=>'Operations','scope_type'=>'personal','created_by'=>$owner->id,'updated_by'=>$owner->id]);$id=$this->actingAs($owner)->postJson('/api/shares',['resource_type'=>'dashboard','resource_id'=>$dashboard->id,'recipient_id'=>$recipient->id,'permission'=>'view'])->assertCreated()->json('data.id');ResourceCollaborator::create(['resource_type'=>'dashboard','resource_id'=>$dashboard->id,'user_id'=>$recipient->id,'permission'=>'edit','granted_by'=>$owner->id]);$this->actingAs($recipient)->postJson("/api/shares/{$id}/accept")->assertOk()->assertJsonPath('data.final_permission','edit');$this->assertDatabaseHas('resource_collaborators',['resource_type'=>'dashboard','resource_id'=>$dashboard->id,'user_id'=>$recipient->id,'permission'=>'edit']);}
 public function test_creator_contributor_share_and_notification_records_never_replace_grant():void{$o=Organization::create(['name'=>'No bypass','slug'=>'no-bypass']);$owner=$this->user($o);$other=$this->user($o);$dashboard=Dashboard::create(['organization_id'=>$o->id,'owner_user_id'=>$owner->id,'name'=>'Private','scope_type'=>'personal','created_by'=>$owner->id,'updated_by'=>$owner->id]);ResourceShareRequest::create(['resource_type'=>'dashboard','resource_id'=>$dashboard->id,'sender_user_id'=>$owner->id,'recipient_user_id'=>$other->id,'requested_permission'=>'view','status'=>'pending_recipient','active_key'=>"dashboard:{$dashboard->id}:{$other->id}"]);$this->actingAs($other)->getJson("/api/dashboards/{$dashboard->id}")->assertNotFound();}
}
