import {useCallback,useEffect,useMemo,useState} from "react";
import {Link} from "react-router-dom";
import {ExternalLink,Plus} from "lucide-react";
import {getDevices} from "../../services/device.service";
import type {Device} from "../../types/device";
import usePermission from "../../hooks/usePermission";
import DeviceCard from "../../components/device/cards/DeviceCard";
import DeviceStatus from "../../components/device/status/DeviceStatus";
import {BodyText,Button,DataTable,EmptyState,ErrorState,Input,LoadingState,PageTitle,Select} from "../../components/ui";

export default function Devices(){
 const [devices,setDevices]=useState<Device[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [query,setQuery]=useState("");const [status,setStatus]=useState("all");const {can}=usePermission();
 const load=useCallback(async()=>{setLoading(true);setError("");try{setDevices(await getDevices());}catch{setError("Unable to load devices.");}finally{setLoading(false);}},[]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load]);
 const filtered=useMemo(()=>devices.filter(device=>(status==="all"||(status==="unknown"?!device.status:device.status===status))&&`${device.name} ${device.type} ${device.serialNumber}`.toLowerCase().includes(query.toLowerCase())),[devices,query,status]);
 return <div className="space-y-5"><header className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><PageTitle>Devices</PageTitle><BodyText className="mt-1">Manage connected devices and inspect operational state.</BodyText></div>{can("device.manage")&&<Link to="/app/devices/add"><Button leadingIcon={<Plus size={15}/>}>Add device</Button></Link>}</header><div className="grid gap-3 sm:grid-cols-[1fr_180px]"><Input aria-label="Search devices" placeholder="Search devices" value={query} onChange={event=>setQuery(event.target.value)}/><Select aria-label="Filter by status" value={status} onChange={event=>setStatus(event.target.value)}><option value="all">All states</option><option value="online">Online</option><option value="offline">Offline</option><option value="maintenance">Maintenance</option><option value="inactive">Inactive</option><option value="unknown">Unknown</option></Select></div>{loading?<LoadingState label="Loading devices..."/>:error?<ErrorState description={error} retry={load}/>:devices.length===0?<EmptyState title="No devices connected" description="Register a device to start receiving telemetry." action={can("device.manage")?<Link to="/app/devices/add"><Button size="small">Add device</Button></Link>:undefined}/>:<><div className="hidden md:block"><DataTable rows={filtered} getRowKey={device=>device.id??device.serialNumber} caption="Assigned devices" empty="No devices match this search." columns={[{key:"name",header:"Device",render:device=><div><p className="font-medium text-[var(--ds-text)]">{device.name}</p><p className="text-[11px] text-[var(--ds-text-subtle)]">{device.serialNumber}</p></div>},{key:"type",header:"Type",render:device=>device.type},{key:"status",header:"Status",render:device=><DeviceStatus status={device.status}/>},{key:"seen",header:"Last seen",render:device=>device.lastSeen?new Date(device.lastSeen).toLocaleString():"Unavailable"},{key:"connection",header:"Connection",render:device=><span className="uppercase">{device.protocol||"Unknown"}</span>},{key:"action",header:"",align:"right",render:device=><Link to={`/app/devices/${device.id}`}><Button size="compact" variant="ghost" aria-label={`Open ${device.name}`}><ExternalLink size={14}/></Button></Link>}]} /></div><div className="grid gap-3 md:hidden">{filtered.map(device=><DeviceCard key={device.id} device={device}/>)}</div></>}</div>;
}
