import {useCallback,useEffect,useState} from "react";
import {Check,Clipboard,Code2,Cpu,Plus,Settings} from "lucide-react";
import {Link,useNavigate,useParams} from "react-router-dom";
import DashboardWorkspace from "../../components/dashboard/DashboardWorkspace";
import LifecycleBanner from "../../components/lifecycle/LifecycleBanner";
import {Badge,Button,Card,CardContent,CardHeader,EmptyState,ErrorState,Input,LoadingState,Modal,PageTitle,Select,Textarea} from "../../components/ui";
import type {DeviceParameterDataType,DeviceParameterSemantic,DeviceTemplate,DeviceTemplateParameter} from "../../types/device";
import {addTemplateParameter,createTemplateDevice,deleteTemplateParameter,getDeviceTemplate,getTemplateDashboard,updateDeviceTemplate,updateTemplateDashboard,updateTemplateParameter} from "../../services/device-template.service";
import TemplateDefinitionsPanel from "../../components/device/TemplateDefinitionsPanel";

const hardware=["sensor","gateway","esp32","esp8266","raspberry_pi","arduino","industrial_controller"];
const connections=["mqtt","https","wifi","ethernet","cellular","lorawan","bluetooth"];
const sections=["general","semantic","units","history","expiration","sync","automations","visibility","notes","api-reference"] as const;
const blank={name:"",key:"",dataType:"number" as DeviceParameterDataType,unit:"",description:"",semantic:"" as DeviceParameterSemantic|"",min:"",max:"",step:"",precision:"",maxLength:"",defaultValue:"",options:"",trueLabel:"On",falseLabel:"Off"};
const presets=[{name:"Temperature",key:"temperature",dataType:"number" as const,unit:"°C",semantic:"temperature" as const,min:"-40",max:"125"},{name:"Humidity",key:"humidity",dataType:"number" as const,unit:"%",semantic:"humidity" as const,min:"0",max:"100"},{name:"Power",key:"power",dataType:"number" as const,unit:"W",semantic:"power" as const,min:"0",max:""},{name:"Motion",key:"motion",dataType:"boolean" as const,unit:"",semantic:"motion" as const,min:"",max:""}];

export default function DeviceTemplateDetail(){
 const {id="",section="home"}=useParams();const navigate=useNavigate();const [item,setItem]=useState<DeviceTemplate|null>(null);const [baseline,setBaseline]=useState<DeviceTemplate|null>(null);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState("");const [settingsOpen,setSettingsOpen]=useState(false);const [streamOpen,setStreamOpen]=useState(false);const [deviceOpen,setDeviceOpen]=useState(false);const [editing,setEditing]=useState<DeviceTemplateParameter|null>(null);const [streamSection,setStreamSection]=useState<(typeof sections)[number]>("general");const [parameter,setParameter]=useState(blank);const [deviceName,setDeviceName]=useState("");const [copied,setCopied]=useState(false);
 const load=useCallback(async()=>{setLoading(true);try{const value=await getDeviceTemplate(id);setItem(value);setBaseline(structuredClone(value));setError("")}catch{setError("Device template could not be loaded.")}finally{setLoading(false)}},[id]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
 const canEdit=item?.capabilities?.canEdit===true;
 const openStream=(value?:DeviceTemplateParameter)=>{setEditing(value??null);const c=value?.configuration??{};setParameter(value?{name:value.name,key:value.key,dataType:value.dataType,unit:value.unit??"",description:value.description??"",semantic:value.semantic??"",min:String(c.min??""),max:String(c.max??""),step:String(c.step??""),precision:String(c.precision??""),maxLength:String(c.maxLength??""),defaultValue:String(c.default??""),options:c.options?.join("\n")??"",trueLabel:c.trueLabel??"On",falseLabel:c.falseLabel??"Off"}:{...blank});setStreamSection("general");setStreamOpen(true)};
 const saveSettings=async()=>{if(!item)return;setSaving(true);try{const value=await updateDeviceTemplate(id,{name:item.name.trim(),description:item.description,device_type:item.deviceType??"sensor",protocol:item.protocol??"mqtt"});setItem(value);setBaseline(structuredClone(value));setSettingsOpen(false)}catch{setError("Template settings could not be saved.")}finally{setSaving(false)}};
 const saveStream=async()=>{setSaving(true);try{const configuration=parameter.dataType==="enum"?{options:parameter.options.split("\n").map(v=>v.trim()).filter(Boolean),default:parameter.defaultValue||undefined}:parameter.dataType==="boolean"?{default:parameter.defaultValue==="true"?true:parameter.defaultValue==="false"?false:undefined,trueLabel:parameter.trueLabel,falseLabel:parameter.falseLabel}:parameter.dataType==="string"?{maxLength:parameter.maxLength?Number(parameter.maxLength):undefined,default:parameter.defaultValue||undefined}:{min:parameter.min?Number(parameter.min):undefined,max:parameter.max?Number(parameter.max):undefined,step:parameter.step?Number(parameter.step):undefined,precision:parameter.precision?Number(parameter.precision):undefined,default:parameter.defaultValue?Number(parameter.defaultValue):undefined};const payload={name:parameter.name.trim(),key:parameter.key.trim(),data_type:parameter.dataType,unit:parameter.unit.trim()||null,description:parameter.description.trim()||null,semantic:parameter.semantic||null,configuration};const value=editing?await updateTemplateParameter(id,editing.id,payload):await addTemplateParameter(id,payload);setItem(value);setBaseline(structuredClone(value));setStreamOpen(false)}catch{setError("Datastream was rejected. Use a unique lowercase key and valid values.")}finally{setSaving(false)}};
 const removeStream=async(value:DeviceTemplateParameter)=>{if(!confirm(`Remove ${value.name}?`))return;await deleteTemplateParameter(id,value.id);await load()};
 const addDevice=async()=>{setSaving(true);try{await createTemplateDevice(id,deviceName.trim());setDeviceOpen(false);setDeviceName("");await load()}catch{setError("Device could not be created.")}finally{setSaving(false)}};
 const copy=async()=>{if(!item)return;await navigator.clipboard.writeText(`IOT_TEMPLATE_ID="${item.id}"\nIOT_TEMPLATE_NAME="${item.name.replaceAll('"','')}"`);setCopied(true);window.setTimeout(()=>setCopied(false),1500)};
 if(loading)return <LoadingState label="Loading Template workspace..."/>;if(error&&!item)return <ErrorState description={error} retry={load}/>;if(!item)return null;if(section==="metadata")return <div className="mx-auto max-w-7xl space-y-5"><PageTitle>{item.name} Metadata</PageTitle><TemplateDefinitionsPanel templateId={id} kind="metadata" items={item.metadataDefinitions??[]} onSaved={()=>void load()}/></div>;if(section==="events")return <div className="mx-auto max-w-7xl space-y-5"><PageTitle>{item.name} Events</PageTitle><TemplateDefinitionsPanel templateId={id} kind="events" items={item.eventDefinitions??[]} onSaved={()=>void load()}/></div>;
 const configured=Boolean(item.name&&item.deviceType&&item.protocol);const streams=(item.parameters?.length??0)>0;const dashboardConfigured=item.dashboardConfigured;const devices=item.deviceCount>0;
 const go=(target:string)=>navigate(`/app/developer/templates/${id}/${target}`);
 return <div className="mx-auto max-w-7xl space-y-5">
  <header className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><div className="grid h-14 w-14 place-items-center rounded-lg border bg-[var(--ds-surface-raised)]"><Cpu/></div><div><PageTitle>{item.name}</PageTitle><p className="text-xs text-[var(--ds-text-muted)]">Template ID: <span className="font-mono">{item.id}</span></p></div></div><div className="flex gap-2"><Link className="inline-flex h-9 items-center rounded-md border px-3 text-sm" to={`/app/developer/templates/${id}/lifecycle`}>Lifecycle</Link>{canEdit&&<Button leadingIcon={<Settings size={14}/>} variant="outline" onClick={()=>setSettingsOpen(true)}>Settings</Button>}</div></header>
  <nav aria-label="Template workspace" className="flex gap-1 overflow-x-auto border-b">{[["home","Home"],["datastreams","Datastreams"],["metadata","Metadata"],["events","Events"],["dashboard","Web Dashboard"]].map(([key,label])=><Link key={key} className={`whitespace-nowrap border-b-2 px-4 py-3 text-sm ${section===key?"border-[var(--ds-primary)] text-[var(--ds-primary)]":"border-transparent text-[var(--ds-text-muted)]"}`} to={`/app/developer/templates/${id}/${key}`}>{label}</Link>)}</nav>
  {error&&<ErrorState description={error}/>} 
  {section==="home"&&<div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_340px]"><Card><CardHeader title="What's next?" description="Complete the canonical Template setup."/><CardContent className="space-y-2">{[[configured,"Configure template","home"],[streams,"Set up Datastreams","datastreams"],[dashboardConfigured,"Set up the Web Dashboard","dashboard"],[devices,"Add first Device","device"]].map(([done,label,target])=><button key={String(label)} type="button" onClick={()=>target==="device"?setDeviceOpen(true):target==="home"?setSettingsOpen(true):go(String(target))} className="flex w-full items-center gap-3 rounded-lg border p-3 text-left hover:bg-[var(--ds-surface-raised)]"><span className={`grid h-6 w-6 place-items-center rounded-full border ${done?"border-emerald-500 bg-emerald-500 text-white":""}`}>{done&&<Check size={14}/>}</span><span>{label}</span></button>)}</CardContent></Card><div className="space-y-4"><Card><CardHeader title="Template settings"/><CardContent><p className="font-medium">{item.deviceType}</p><p className="text-sm text-[var(--ds-text-muted)]">{item.protocol}</p>{item.description&&<p className="mt-3 text-sm">{item.description}</p>}</CardContent></Card><Card><CardHeader title="Firmware configuration" description="Non-secret identity for Device firmware."/><CardContent><pre className="overflow-auto rounded bg-[var(--ds-surface)] p-3 text-xs">{`IOT_TEMPLATE_ID="${item.id}"\nIOT_TEMPLATE_NAME="${item.name}"`}</pre><Button className="mt-3" size="small" variant="outline" leadingIcon={<Clipboard size={14}/>} onClick={()=>void copy()}>{copied?"Copied":"Copy configuration"}</Button><p aria-live="polite" className="sr-only">{copied?"Configuration copied":""}</p></CardContent></Card></div></div>}
  {section==="datastreams"&&<Card><CardHeader title="Datastreams" description="Canonical Template parameters define values a Device sends, receives, or exposes." action={canEdit?<Button size="small" leadingIcon={<Plus size={14}/>} onClick={()=>openStream()}>Create new</Button>:undefined}/>{!item.parameters?.length?<EmptyState title="No Datastreams yet" description="Create the first typed data definition for Devices using this Template." action={canEdit?<Button onClick={()=>openStream()}>Create new</Button>:undefined}/>:<div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead><tr><th className="p-3">Name</th><th>Identifier</th><th>Type</th><th>Unit</th>{canEdit&&<th>Actions</th>}</tr></thead><tbody>{item.parameters.map(value=><tr className="border-t" key={value.id}><td className="p-3 font-medium">{value.name}</td><td className="font-mono text-xs">{value.key}</td><td><Badge>{value.dataType}</Badge></td><td>{value.unit||"—"}</td>{canEdit&&<td><Button size="compact" variant="outline" onClick={()=>openStream(value)}>Edit</Button> <Button size="compact" variant="danger" onClick={()=>void removeStream(value)}>Remove</Button></td>}</tr>)}</tbody></table></div>}</Card>}
  {section==="dashboard"&&<DashboardWorkspace load={()=>getTemplateDashboard(id)} save={dashboard=>updateTemplateDashboard(id,dashboard)} canEdit={canEdit} resourceId={id} fallback={<EmptyState title="No widgets yet" description="Customize this Template's Web Dashboard using the shared Widget Box."/>}/>} 
  {section==="lifecycle"&&<LifecycleBanner type="device_template" id={id}/>} 
  <Modal open={settingsOpen} onClose={()=>{setItem(baseline?structuredClone(baseline):item);setSettingsOpen(false)}} title="Template settings" description="Edit the canonical Template configuration." footer={<><Button variant="ghost" onClick={()=>{setItem(baseline?structuredClone(baseline):item);setSettingsOpen(false)}}>Cancel</Button><Button loading={saving} onClick={()=>void saveSettings()}>Save</Button></>}><div className="space-y-3"><div className="rounded border border-dashed p-5 text-center text-sm text-[var(--ds-text-muted)]">Template image upload is unavailable because no protected image domain exists. The default icon remains active.</div><Input label="Name" maxLength={50} helperText={`${item.name.length} / 50`} value={item.name} onChange={event=>setItem(value=>value&&({...value,name:event.target.value}))}/><Select label="Hardware" value={item.deviceType??"sensor"} onChange={event=>setItem(value=>value&&({...value,deviceType:event.target.value}))}>{hardware.map(value=><option key={value}>{value}</option>)}</Select><Select label="Connection type" value={item.protocol??"mqtt"} onChange={event=>setItem(value=>value&&({...value,protocol:event.target.value}))}>{connections.map(value=><option key={value}>{value}</option>)}</Select><Textarea label="Description" maxLength={128} helperText={`${item.description?.length??0} / 128`} value={item.description??""} onChange={event=>setItem(value=>value&&({...value,description:event.target.value||null}))}/></div></Modal>
  <Modal open={deviceOpen} onClose={()=>setDeviceOpen(false)} title="Add first Device" description="The Template and Organization are derived from this workspace." footer={<><Button variant="ghost" onClick={()=>setDeviceOpen(false)}>Cancel</Button><Button disabled={!deviceName.trim()} loading={saving} onClick={()=>void addDevice()}>Create</Button></>}><Input label="Device name" required maxLength={50} helperText={`${deviceName.length} / 50`} value={deviceName} onChange={event=>setDeviceName(event.target.value)}/></Modal>
  <Modal open={streamOpen} onClose={()=>setStreamOpen(false)} title={editing?"Edit Datastream":"New Datastream"} footer={<><Button variant="ghost" onClick={()=>setStreamOpen(false)}>Cancel</Button><Button disabled={!parameter.name.trim()||!parameter.key.trim()} loading={saving} onClick={()=>void saveStream()}>Save</Button></>}>
   <div className="grid min-h-96 gap-4 sm:grid-cols-[150px_1fr]"><nav aria-label="Datastream sections" className="space-y-1">{sections.map(value=><button key={value} type="button" onClick={()=>setStreamSection(value)} className={`block w-full rounded px-3 py-2 text-left text-xs capitalize ${streamSection===value?"bg-[var(--ds-primary)] text-white":""}`}>{value.replace("-"," ")}</button>)}</nav><div>
    {streamSection==="general"&&<div className="space-y-3">{!editing&&<div><p className="mb-2 text-xs font-medium">Start with a preset</p><div className="flex flex-wrap gap-2">{presets.map(preset=><Button key={preset.key} size="compact" variant="outline" onClick={()=>setParameter(value=>({...value,...preset}))}>{preset.name}</Button>)}</div></div>}<Input label="Datastream name" required value={parameter.name} onChange={event=>setParameter(value=>({...value,name:event.target.value}))}/><Input label="Identifier" required readOnly={!!editing} helperText="Lowercase letters, numbers, and underscores. Immutable after creation." value={parameter.key} onChange={event=>setParameter(value=>({...value,key:event.target.value}))}/><Select label="Data type" disabled={!!editing} value={parameter.dataType} onChange={event=>setParameter(value=>({...value,dataType:event.target.value as DeviceParameterDataType,min:"",max:"",step:"",precision:"",maxLength:"",defaultValue:"",options:""}))}><option value="number">Number</option><option value="integer">Integer</option><option value="string">String</option><option value="boolean">Boolean</option><option value="enum">Enum</option></Select></div>}
    {streamSection==="semantic"&&<Select label="Semantic meaning" value={parameter.semantic} onChange={event=>setParameter(value=>({...value,semantic:event.target.value as DeviceParameterSemantic|""}))}><option value="">None</option>{["temperature","humidity","pressure","voltage","current","power","battery","motion","state","signal","level"].map(value=><option key={value}>{value}</option>)}</Select>}
    {streamSection==="units"&&<Input label="Unit" helperText="Presentation metadata used consistently by widgets and telemetry views." value={parameter.unit} onChange={event=>setParameter(value=>({...value,unit:event.target.value}))}/>} 
    {streamSection==="sync"&&<div className="space-y-3">{["number","integer"].includes(parameter.dataType)&&<><div className="grid grid-cols-2 gap-3"><Input label="Minimum" type="number" value={parameter.min} onChange={event=>setParameter(value=>({...value,min:event.target.value}))}/><Input label="Maximum" type="number" value={parameter.max} onChange={event=>setParameter(value=>({...value,max:event.target.value}))}/><Input label="Step" type="number" value={parameter.step} onChange={event=>setParameter(value=>({...value,step:event.target.value}))}/><Input label="Precision" type="number" value={parameter.precision} onChange={event=>setParameter(value=>({...value,precision:event.target.value}))}/></div><Input label="Default" type="number" value={parameter.defaultValue} onChange={event=>setParameter(value=>({...value,defaultValue:event.target.value}))}/></>}{parameter.dataType==="string"&&<><Input label="Maximum length" type="number" value={parameter.maxLength} onChange={event=>setParameter(value=>({...value,maxLength:event.target.value}))}/><Input label="Default" value={parameter.defaultValue} onChange={event=>setParameter(value=>({...value,defaultValue:event.target.value}))}/></>}{parameter.dataType==="boolean"&&<><Select label="Default" value={parameter.defaultValue} onChange={event=>setParameter(value=>({...value,defaultValue:event.target.value}))}><option value="">None</option><option value="true">True</option><option value="false">False</option></Select><div className="grid grid-cols-2 gap-3"><Input label="True label" value={parameter.trueLabel} onChange={event=>setParameter(value=>({...value,trueLabel:event.target.value}))}/><Input label="False label" value={parameter.falseLabel} onChange={event=>setParameter(value=>({...value,falseLabel:event.target.value}))}/></div></>}{parameter.dataType==="enum"&&<><Textarea label="Allowed values" helperText="One unique value per line." value={parameter.options} onChange={event=>setParameter(value=>({...value,options:event.target.value}))}/><Input label="Default" value={parameter.defaultValue} onChange={event=>setParameter(value=>({...value,defaultValue:event.target.value}))}/></>}</div>}
    {streamSection==="notes"&&<Textarea label="Notes" maxLength={500} value={parameter.description} onChange={event=>setParameter(value=>({...value,description:event.target.value}))}/>} {streamSection==="api-reference"&&<div className="space-y-3"><p className="text-sm">Telemetry ingestion validates this key and value against the saved definition. No credential is shown here.</p><pre className="overflow-auto rounded bg-[var(--ds-surface)] p-3 text-xs">{`POST /api/device-runtime/telemetry\n{ "key": "${parameter.key||"metric_key"}", "value": 42 }`}</pre></div>} {!["general","semantic","units","sync","notes","api-reference"].includes(streamSection)&&<div className="rounded border p-4 text-sm text-[var(--ds-text-muted)]"><Code2 className="mb-2"/>{streamSection==="history"?"Telemetry retention is system-owned and bounded.":streamSection==="automations"?"Use the canonical Automation workspace to reference this key.":"No independent Datastream setting is supported."}</div>}
   </div></div>
  </Modal>
 </div>
}
