<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration{public function up():void{
 Schema::table('plans',fn(Blueprint $t)=>$t->unsignedInteger('automation_limit')->default(0));
 Schema::create('automations',function(Blueprint $t){$t->id();$t->foreignId('organization_id')->constrained()->cascadeOnDelete();$t->string('name');$t->text('description')->nullable();$t->string('status')->default('draft');$t->boolean('enabled')->default(false);$t->unsignedInteger('version')->default(1);$t->foreignId('created_by')->constrained('users');$t->foreignId('updated_by')->constrained('users');$t->timestamp('last_executed_at')->nullable();$t->timestamps();$t->index(['organization_id','enabled']);});
 Schema::create('automation_triggers',function(Blueprint $t){$t->id();$t->foreignId('automation_id')->constrained()->cascadeOnDelete();$t->string('type')->index();$t->json('configuration');$t->timestamps();});
 Schema::create('automation_conditions',function(Blueprint $t){$t->id();$t->foreignId('automation_id')->constrained()->cascadeOnDelete();$t->string('logic')->default('AND');$t->unsignedInteger('position')->default(0);$t->json('configuration');$t->timestamps();});
 Schema::create('automation_actions',function(Blueprint $t){$t->id();$t->foreignId('automation_id')->constrained()->cascadeOnDelete();$t->string('type');$t->unsignedInteger('position')->default(0);$t->boolean('continue_on_failure')->default(false);$t->json('configuration');$t->timestamps();});
 Schema::create('automation_schedules',function(Blueprint $t){$t->id();$t->foreignId('automation_id')->constrained()->cascadeOnDelete();$t->string('type');$t->json('configuration');$t->boolean('enabled')->default(true);$t->timestamp('last_run_at')->nullable();$t->timestamp('next_run_at')->nullable()->index();$t->timestamps();});
 Schema::create('automation_executions',function(Blueprint $t){$t->id();$t->uuid('correlation_id')->unique();$t->foreignId('automation_id')->constrained()->cascadeOnDelete();$t->foreignId('organization_id')->constrained()->cascadeOnDelete();$t->string('trigger_type');$t->json('trigger_data')->nullable();$t->string('status')->index();$t->timestamp('started_at')->nullable();$t->timestamp('completed_at')->nullable();$t->text('error_message')->nullable();$t->json('result_summary')->nullable();$t->timestamps();$t->index(['organization_id','created_at']);});
 Schema::create('automation_execution_logs',function(Blueprint $t){$t->id();$t->foreignId('automation_execution_id')->constrained()->cascadeOnDelete();$t->foreignId('automation_action_id')->nullable()->constrained()->nullOnDelete();$t->string('level');$t->string('message');$t->json('context')->nullable();$t->timestamp('executed_at');$t->timestamps();});
 Schema::create('automation_templates',function(Blueprint $t){$t->id();$t->foreignId('organization_id')->nullable()->constrained()->cascadeOnDelete();$t->string('name');$t->text('description')->nullable();$t->string('category');$t->json('definition');$t->boolean('active')->default(true);$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();});
 Schema::create('notifications',function(Blueprint $t){$t->id();$t->foreignId('organization_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->string('title');$t->text('message');$t->string('severity')->default('info');$t->timestamp('read_at')->nullable();$t->timestamps();});
 }public function down():void{Schema::dropIfExists('notifications');Schema::dropIfExists('automation_templates');Schema::dropIfExists('automation_execution_logs');Schema::dropIfExists('automation_executions');Schema::dropIfExists('automation_schedules');Schema::dropIfExists('automation_actions');Schema::dropIfExists('automation_conditions');Schema::dropIfExists('automation_triggers');Schema::dropIfExists('automations');Schema::table('plans',fn(Blueprint $t)=>$t->dropColumn('automation_limit'));}};
