<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration{public function up():void{
Schema::create('collaboration_threads',function(Blueprint $t){$t->id();$t->string('resource_type');$t->unsignedBigInteger('resource_id');$t->string('anchor_type')->default('resource');$t->string('anchor_key')->nullable();$t->unsignedBigInteger('anchor_revision_id')->nullable();$t->string('status')->default('open');$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->foreignId('resolved_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('resolved_at')->nullable();$t->timestamps();$t->index(['resource_type','resource_id','status']);});
Schema::create('collaboration_comments',function(Blueprint $t){$t->id();$t->foreignId('thread_id')->constrained('collaboration_threads')->cascadeOnDelete();$t->foreignId('parent_comment_id')->nullable()->constrained('collaboration_comments')->nullOnDelete();$t->text('body');$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('edited_at')->nullable();$t->timestamps();$t->index(['thread_id','created_at']);});
Schema::create('comment_mentions',function(Blueprint $t){$t->id();$t->foreignId('comment_id')->constrained('collaboration_comments')->cascadeOnDelete();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->timestamps();$t->unique(['comment_id','user_id']);});
Schema::create('comment_acknowledgments',function(Blueprint $t){$t->id();$t->foreignId('thread_id')->constrained('collaboration_threads')->cascadeOnDelete();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->timestamp('acknowledged_at');$t->timestamps();$t->unique(['thread_id','user_id']);});
Schema::create('collaboration_thread_transitions',function(Blueprint $t){$t->id();$t->foreignId('thread_id')->constrained('collaboration_threads')->cascadeOnDelete();$t->string('from_status');$t->string('to_status');$t->foreignId('actor_id')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('created_at');$t->index(['thread_id','created_at']);});
}public function down():void{Schema::dropIfExists('collaboration_thread_transitions');Schema::dropIfExists('comment_acknowledgments');Schema::dropIfExists('comment_mentions');Schema::dropIfExists('collaboration_comments');Schema::dropIfExists('collaboration_threads');}};
