import {useMemo,useState} from "react";
import {Activity,MapPin,Search} from "lucide-react";
import type {DashboardWidgetDefinition,WidgetSettings,WidgetType} from "../../../types/dashboard";
import {useDashboardStore} from "../../../store/dashboard.store";
import {Card,CardContent,EmptyState,Input,SectionTitle,Select} from "../../ui";
import {CORE_WIDGET_RENDERER_TYPES} from "../widgets/widgetRendererRegistry";

const chartTypes:WidgetType[]=["metrics_over_time","metric_by_devices","chart","events_over_time","events_breakdown_over_time","activations"];
function WidgetPreview({type}:{type:WidgetType}){
 if(chartTypes.includes(type))return <svg viewBox="0 0 220 82" className="h-20 w-full" aria-hidden><path d="M8 67H214M8 45H214M8 23H214" stroke="currentColor" className="text-[var(--ds-border)]"/><polyline points="8,63 38,48 65,55 94,25 122,42 151,17 180,31 212,12" fill="none" stroke="var(--ds-primary)" strokeWidth="3"/><text x="8" y="80" fill="currentColor" className="text-[8px] text-[var(--ds-text-muted)]">9:00</text><text x="98" y="80" fill="currentColor" className="text-[8px] text-[var(--ds-text-muted)]">12:00</text><text x="190" y="80" fill="currentColor" className="text-[8px] text-[var(--ds-text-muted)]">Now</text></svg>;
 if(["geo_map","image_map","device_connection_map"].includes(type))return <div className="relative h-20 overflow-hidden rounded bg-[radial-gradient(circle_at_25%_35%,rgba(59,130,246,.3),transparent_24%),radial-gradient(circle_at_72%_62%,rgba(16,185,129,.22),transparent_28%)]"><div className="absolute inset-0 opacity-40 [background-image:linear-gradient(var(--ds-border)_1px,transparent_1px),linear-gradient(90deg,var(--ds-border)_1px,transparent_1px)] [background-size:28px_28px]"/><MapPin className="absolute left-[28%] top-[24%] text-emerald-400" size={18}/><MapPin className="absolute left-[68%] top-[52%] text-blue-400" size={18}/><span className="absolute bottom-1 left-2 text-[8px]">Sample facility map</span></div>;
 if(type==="switch")return <div className="flex h-16 items-center"><span className="h-7 w-12 rounded-full bg-emerald-500 p-1"><span className="ml-auto block h-5 w-5 rounded-full bg-white"/></span><span className="ml-3 text-xs">Online</span></div>;
 if(type==="slider"||type==="gauge")return <div className="flex h-16 items-center gap-3"><div className="h-2 flex-1 rounded bg-[var(--ds-border)]"><div className="h-2 w-[64%] rounded bg-[var(--ds-primary)]"/></div><strong className="text-lg">64%</strong></div>;
 if(type.includes("table"))return <div className="h-20 space-y-1 pt-1 text-[9px]"><div className="grid grid-cols-3 border-b pb-1 font-semibold"><span>Device</span><span>Value</span><span>Status</span></div>{["Controller","Sensor","Gateway"].map((name,index)=><div key={name} className="grid grid-cols-3"><span>{name}</span><span>{24+index*13}</span><span className="text-emerald-400">online</span></div>)}</div>;
 if(["event_count_chart","events_by_organization","events_by_device","events_by_template"].includes(type))return <div className="flex h-20 flex-col justify-center gap-2">{[82,58,36].map((width,index)=><div key={width} className="flex items-center gap-2 text-[9px]"><span className="w-8">Item {index+1}</span><span className="h-2 rounded bg-[var(--ds-primary)]" style={{width:`${width}%`}}/><strong>{width}</strong></div>)}</div>;
 if(type==="latest_events")return <div className="h-20 space-y-2 pt-1 text-[9px]"><p><strong>Device connected</strong><span className="block text-[var(--ds-text-muted)]">Just now</span></p><p><strong>Telemetry received</strong><span className="block text-[var(--ds-text-muted)]">2 min ago</span></p></div>;
 return <div className="flex h-16 items-center justify-center text-center"><strong className="text-3xl tabular-nums">{type==="label"?"Status OK":"24"}</strong></div>;
}

export default function WidgetLibrary({definitions,deviceId}:{definitions:DashboardWidgetDefinition[];deviceId?:string}) {
 const add=useDashboardStore(s=>s.addWidget),widgets=useDashboardStore(s=>s.widgets),[search,setSearch]=useState(""),[category,setCategory]=useState("");
 const palette=definitions.filter(d=>d.scope==="admin_global"||(CORE_WIDGET_RENDERER_TYPES as readonly string[]).includes(d.type));
 const categories=useMemo(()=>Array.from(new Set(palette.map(d=>d.category))).sort(),[palette]);
 const visible=palette.filter(d=>(!category||d.category===category)&&`${d.label} ${d.description} ${d.category}`.toLowerCase().includes(search.toLowerCase()));
 const create=(item:DashboardWidgetDefinition)=>{const settings={...item.defaultSettings,title:item.defaultSettings.title??item.label} as WidgetSettings;if(item.requiresDevice)settings.datasource={deviceId:deviceId??"",telemetryKey:""};const bottom=widgets.reduce((max,w)=>Math.max(max,w.layout.y+w.layout.h),0);add({id:crypto.randomUUID(),type:item.type,settings,layout:{...item.defaultLayout,x:0,y:bottom}})};
 return <Card><CardContent><SectionTitle>Widget Box</SectionTitle><p className="mt-1 text-[10px] text-[var(--ds-text-subtle)]">Preview a widget, then click or drag it onto the Dashboard.</p><div className="mt-3 space-y-2"><Input label="Search widgets" leadingIcon={<Search size={14}/>} value={search} onChange={e=>setSearch(e.target.value)}/>{categories.length>1&&<Select label="Category" value={category} onChange={e=>setCategory(e.target.value)}><option value="">All categories</option>{categories.map(value=><option key={value}>{value}</option>)}</Select>}<div className="max-h-[65vh] space-y-5 overflow-y-auto pr-1">{visible.length?categories.filter(group=>!category||group===category).map(group=><section key={group} aria-labelledby={`widget-group-${group}`}><h3 id={`widget-group-${group}`} className="mb-2 text-xs font-semibold">{group}</h3><div className="space-y-3">{visible.filter(item=>item.category===group).map(item=><button type="button" draggable key={item.type} aria-label={`Add ${item.label} widget`} onDragStart={e=>e.dataTransfer.setData("application/x-dashboard-widget",item.type)} onClick={()=>create(item)} className="block w-full overflow-hidden rounded-[8px] border border-[var(--ds-border-subtle)] bg-[var(--ds-surface-raised)] text-left hover:border-[var(--ds-primary)] focus-visible:ring-2 focus-visible:ring-[var(--ds-focus)]"><span className="flex items-start gap-2 border-b border-[var(--ds-border-subtle)] p-2"><Activity size={15} aria-hidden className="mt-0.5 shrink-0 text-[var(--ds-primary)]"/><span><span className="block text-xs font-medium">{item.label}</span><span className="block text-[10px] text-[var(--ds-text-subtle)]">{item.description}</span></span></span><span className="block px-2 py-1"><WidgetPreview type={item.type}/></span></button>)}</div></section>):<EmptyState title="No widgets match" description="Adjust the Widget Box search or category."/>}</div></div></CardContent></Card>;
}
