<?php
namespace App\Http\Controllers;
use App\Collaboration\{CollaborationResourceReference,CollaborationResourceRegistry};use App\Models\{Automation,ResourcePublicationState,ResourcePublicationVersion};use App\Services\{AutomationPublicationService,ReviewHistoryService};use Illuminate\Http\Request;
final class AutomationPublicationController extends Controller{
 public function __construct(private CollaborationResourceRegistry $registry,private AutomationPublicationService $service,private ReviewHistoryService $history){}
 public function state(Request $r,string $automation){$a=$this->registry->resolve($r->user(),new CollaborationResourceReference('automation',$automation),'view')->resource;return response()->json(['data'=>$this->service->state($a)]);}public function submit(Request $r,string $automation){$a=Automation::findOrFail($automation);$d=$r->validate(['revision_id'=>'nullable|integer|min:1']);return response()->json(['data'=>$this->service->submissionData($this->service->submit($r->user(),$a,isset($d['revision_id'])?(int)$d['revision_id']:null))],201);}public function history(Request $r,string $automation){return response()->json($this->history->forResource($r->user(),'automation',$automation,(int)$r->input('per_page',20)));}
 public function catalog(Request $r){abort_unless($r->user()->organization_id,403);$states=ResourcePublicationState::where('resource_type','automation')->whereNotNull('current_publication_version_id')->whereIn('resource_id',Automation::where('organization_id',$r->user()->organization_id)->select('id'))->with('currentVersion.revision')->paginate(25);return response()->json($states->through(fn($s)=>$this->item($s)));}public function published(Request $r,string $automation){abort_unless($r->user()->organization_id,403);$state=ResourcePublicationState::where(['resource_type'=>'automation','resource_id'=>$automation])->whereNotNull('current_publication_version_id')->whereIn('resource_id',Automation::where('organization_id',$r->user()->organization_id)->select('id'))->with('currentVersion.revision')->firstOrFail();return response()->json(['data'=>$this->item($state,true)]);}
 private function item($state,bool $snapshot=false):array{$v=$state->currentVersion;$r=$v->revision;$s=$r->snapshot;return ['id'=>(string)$state->resource_id,'name'=>data_get($s,'metadata.name'),'description'=>data_get($s,'metadata.description'),'trigger'=>['type'=>data_get($s,'trigger.type'),'deviceId'=>data_get($s,'trigger.deviceId')],'actionTypes'=>collect($s['actions']??[])->pluck('type')->values(),'currentVersion'=>['id'=>(string)$v->id,'number'=>$v->publication_number,'publishedAt'=>$v->published_at?->toISOString()],'approvedRevision'=>['id'=>(string)$r->id,'number'=>$r->revision_number],'capabilities'=>['canViewPublished'=>true,'canEdit'=>false,'canExecute'=>false],'snapshot'=>$snapshot?$s:null];}
}
