<?php
namespace App\Http\Controllers;
use App\Collaboration\{CollaborationResourceReference,CollaborationResourceRegistry};use App\Models\{Dashboard,ResourcePublicationState,ResourcePublicationVersion,ResourceRevision};use App\Services\Dashboard\{DashboardPublicationService,DashboardWidgetRegistry};use App\Services\{ResourceLifecycleService,ReviewHistoryService};use Illuminate\Http\Request;
final class DashboardPublicationController extends Controller
{
 public function __construct(private CollaborationResourceRegistry $registry,private DashboardPublicationService $service,private DashboardWidgetRegistry $widgets,private ReviewHistoryService $history){}
 public function state(Request $r,string $dashboard){$d=$this->registry->resolve($r->user(),new CollaborationResourceReference('dashboard',$dashboard),'view')->resource;return ['data'=>$this->service->state($d)];}
 public function submit(Request $r,string $dashboard){$d=Dashboard::findOrFail($dashboard);$data=$r->validate(['revision_id'=>['required','integer','min:1']]);return response()->json(['data'=>$this->service->submissionData($this->service->submit($r->user(),$d,(int)$data['revision_id']))],201);}
 public function history(Request $r,string $dashboard){return response()->json($this->history->forResource($r->user(),'dashboard',$dashboard,(int)$r->input('per_page',20)));}
 public function catalog(Request $r){abort_unless($r->user()->status==='active'&&$r->user()->organization_id,403);$ids=Dashboard::where(['organization_id'=>$r->user()->organization_id,'scope_type'=>'personal'])->select('id');$states=ResourcePublicationState::where('resource_type','dashboard')->whereNotNull('current_publication_version_id')->whereIn('resource_id',$ids)->with('currentVersion.revision')->paginate(min((int)$r->input('per_page',25),50));return response()->json($states->through(fn($state)=>$this->item($r,$state,false)));}
 public function published(Request $r,string $dashboard){return ['data'=>$this->item($r,$this->publishedState($r,$dashboard),true)];}
 public function versions(Request $r,string $dashboard){$state=$this->publishedState($r,$dashboard);return response()->json(ResourcePublicationVersion::where(['resource_type'=>'dashboard','resource_id'=>$state->resource_id])->with(['revision:id,revision_number','publisher:id,name'])->latest('publication_number')->paginate(min((int)$r->input('per_page',20),50)));}
 private function publishedState(Request $r,string $id):ResourcePublicationState{abort_unless($r->user()->status==='active'&&$r->user()->organization_id,403);$dashboard=Dashboard::where(['id'=>$id,'organization_id'=>$r->user()->organization_id,'scope_type'=>'personal'])->firstOrFail();app(ResourceLifecycleService::class)->assertActive('dashboard',$dashboard->id,'This published Dashboard is unavailable.');return ResourcePublicationState::where(['resource_type'=>'dashboard','resource_id'=>$dashboard->id])->whereNotNull('current_publication_version_id')->with('currentVersion.revision')->firstOrFail();}
 private function item(Request $r,ResourcePublicationState $state,bool $include):array{$version=$state->currentVersion;$revision=$version->revision;$snapshot=$revision->snapshot;$dashboard=Dashboard::findOrFail($state->resource_id);$rendered=[];foreach($snapshot['dashboard']['widgets']??[] as $widget){$available=true;$configuration=$widget['configuration']??[];try{$this->widgets->validate($r->user(),'personal',['id'=>$widget['id'],'type'=>$widget['type'],'title'=>$widget['title']??null,'layout'=>$widget['layout'],'configuration'=>$configuration]);}catch(\Throwable){$available=false;}$rendered[]=['id'=>(string)$widget['id'],'type'=>$widget['type'],'settings'=>['title'=>$widget['title']??null,'datasource'=>$available&&isset($configuration['deviceId'])?['deviceId'=>(string)$configuration['deviceId'],'telemetryKey'=>$configuration['telemetryKey']??'','unit'=>$configuration['unit']??null]:null,'timeRange'=>$configuration['timeRange']??null,'chartType'=>$configuration['chartType']??null,'minimum'=>$configuration['minimum']??null,'maximum'=>$configuration['maximum']??null],'layout'=>$widget['layout'],'available'=>$available];}return ['id'=>(string)$dashboard->id,'name'=>$snapshot['metadata']['name']??$dashboard->name,'description'=>$snapshot['metadata']['description']??null,'scope'=>'published','canEdit'=>false,'canShare'=>false,'widgets'=>$include?$rendered:[],'widgetCount'=>count($rendered),'widgetDefinitions'=>$include?$this->widgets->definitions('personal'):[],'currentPublicationVersion'=>['id'=>(string)$version->id,'number'=>$version->publication_number,'publishedAt'=>$version->published_at?->toISOString()],'publishedRevision'=>['id'=>(string)$revision->id,'number'=>$revision->revision_number]];}
}