<?php
namespace App\Http\Controllers;use App\Http\Resources\DeviceCredentialResource;use App\Models\Device;use App\Models\DeviceCredential;use App\Services\Admin\DeviceAccessService;use App\Services\DeviceCredentialService;use Illuminate\Http\Request;use Illuminate\Validation\Rule;
class DeviceCredentialController extends Controller { public function __construct(private DeviceAccessService $access,private DeviceCredentialService $service){}
 public function all(Request $r){$this->permission($r);$ids=$this->access->accessibleDevices($r->user())->whereHas('accessAssignments',fn($q)=>$q->where('user_id',$r->user()->id)->where('access_level','full_access'))->pluck('id');return DeviceCredentialResource::collection(DeviceCredential::with(['device:id,name,external_id','creator:id,name'])->whereIn('device_id',$ids)->latest()->paginate(25));}
 public function index(Request $r,string $device){$d=$this->managed($r,$device);return DeviceCredentialResource::collection($d->credentials()->with(['device:id,name,external_id','creator:id,name'])->latest()->get());}
 public function store(Request $r,string $device){$d=$this->managed($r,$device);$data=$this->validateInput($r);[$credential,$token]=$this->service->create($r->user(),$d,$data);return response()->json(['data'=>(new DeviceCredentialResource($credential))->resolve($r),'token'=>$token],201);}
 public function revoke(Request $r,string $device,string $credential){$d=$this->managed($r,$device);$c=$d->credentials()->findOrFail($credential);return new DeviceCredentialResource($this->service->revoke($c));}
 private function managed(Request $r,string $id):Device{$this->permission($r);return $this->access->findManageableDeviceOrFail($r->user(),$id);}private function permission(Request $r):void{abort_unless($r->user()->organization&&$r->user()->hasOrganizationPermission('device.manage'),403);}private function validateInput(Request $r):array{return $r->validate(['name'=>'required|string|max:120','scopes'=>'nullable|array|min:1','scopes.*'=>['required','string','distinct',Rule::in(DeviceCredential::SCOPES)],'expires_at'=>'nullable|date|after:now']);}
}
