<?php
namespace App\Http\Controllers;
use App\Http\Resources\DeviceResource;use App\Models\Device;use App\Services\Admin\DeviceAccessService;use App\Services\DeviceCreationService;use App\Services\ResourceLifecycleService;use App\Services\ResourceRevisionService;use App\Services\SafeResourceSaveService;use Illuminate\Http\Request;
class DeviceController extends Controller
{
 public function __construct(private DeviceAccessService $access,private DeviceCreationService $creation,private ResourceRevisionService $revisions,private SafeResourceSaveService $saves,private ResourceLifecycleService $lifecycle){}
 public function index(Request $r){$this->view($r);return $this->access->accessibleDevices($r->user())->get()->map(fn($d)=>$this->resource($d,$r));}
 public function show(Request $r,string $device){$this->view($r);return $this->resource($this->access->findViewableDeviceOrFail($r->user(),$device),$r);}
 public function store(Request $r){$org=$this->createAccess($r);$data=$r->validate(['name'=>'required|string|max:255','type'=>'required|string|max:100','serialNumber'=>'required|string|max:255|unique:devices,external_id','protocol'=>'required|string|max:50','location_id'=>'nullable|integer','location'=>'prohibited','macAddress'=>'nullable|string|max:50','template_id'=>'nullable|integer','organization_id'=>'prohibited','created_by'=>'prohibited','assigned_by'=>'prohibited','access_level'=>'prohibited','status'=>'prohibited']);$d=$this->creation->create($r->user(),$org,$data);return response()->json($this->resource($d,$r),201);}
 public function update(Request $r,string $device){$this->view($r);$d=$this->access->findManageableDeviceOrFail($r->user(),$device);$data=$r->validate(['name'=>'sometimes|required|string|max:255','type'=>'sometimes|required|string|max:100','protocol'=>'sometimes|required|string|max:50','location_id'=>'nullable|integer','location'=>'prohibited','macAddress'=>'nullable|string|max:50','baseRevisionId'=>'nullable|integer']);$base=$data['baseRevisionId']??null;unset($data['baseRevisionId']);$saved=$this->saves->execute($r->user(),'device',Device::class,$d->id,$base,fn($actor,$locked)=>abort_unless($this->access->hasFullDeviceAccess($actor,$locked),404),fn($locked)=>$this->lifecycle->assertActive('device',$locked->id,'Disabled or Archived Devices are read-only.'),function(Device $locked)use($data){$location=array_key_exists('location_id',$data)?app(\App\Services\LocationService::class)->assertAssignable($locked->organization,$data['location_id']===null?null:(int)$data['location_id']):$locked->canonicalLocation;$locked->update(['name'=>$data['name']??$locked->name,'type'=>$data['type']??$locked->type,'protocol'=>$data['protocol']??$locked->protocol,'location_id'=>array_key_exists('location_id',$data)?$location?->id:$locked->location_id,'location'=>null,'mac_address'=>array_key_exists('macAddress',$data)?$data['macAddress']:$locked->mac_address]);return $locked;},fn($locked,$actor)=>$this->revisions->recordDevice($locked,$actor,'Device metadata updated'),$base!==null,$r->header('Idempotency-Key'),$data);return $this->resource($saved,$r);}
 public function destroy(Request $r,string $device){$this->view($r);$this->access->findManageableDeviceOrFail($r->user(),$device);abort(405,'Use the Admin lifecycle Disable or Archive action; ordinary hard delete is unavailable.');}
 private function view(Request $r){abort_unless($r->user()->organization&&$r->user()->hasOrganizationPermission('device.view'),403);}
 private function createAccess(Request $r){abort_unless($r->user()->organization&&$r->user()->status==='active'&&$r->user()->hasOrganizationPermission('device.view'),403);return $r->user()->organization;}
 private function resource(Device $d,Request $r):array{return (new DeviceResource($d))->resolve($r);}
}
