<?php
namespace App\Http\Controllers;
use App\Http\Resources\FirmwareDeploymentResource;use App\Models\FirmwareArtifact;use App\Models\FirmwareDeployment;use App\Services\FirmwareDeploymentService;use Illuminate\Http\Request;use Illuminate\Validation\Rule;
class FirmwareDeploymentController extends Controller { public function __construct(private FirmwareDeploymentService $service){}
 public function index(Request $r){$org=$this->org($r,'device.view');$f=$r->validate(['status'=>['nullable',Rule::in(FirmwareDeployment::STATUSES)],'artifact_id'=>'nullable|integer','device_id'=>'nullable|integer','per_page'=>['nullable','integer',Rule::in([25,50,100])]]);$q=$org->firmwareDeployments()->with(['artifact:id,name,version','creator:id,name','targets.device:id,name,external_id'])->when($f['status']??null,fn($x,$v)=>$x->where('status',$v))->when($f['artifact_id']??null,fn($x,$v)=>$x->where('firmware_artifact_id',$v))->when($f['device_id']??null,fn($x,$v)=>$x->whereHas('targets',fn($t)=>$t->where('device_id',$v)))->latest();return FirmwareDeploymentResource::collection($q->paginate($f['per_page']??25)->withQueryString());}
 public function store(Request $r){$org=$this->org($r,'device.manage');$data=$r->validate(['firmware_artifact_id'=>'required|integer','device_ids'=>'required|array|min:1|max:100','device_ids.*'=>'required|integer|distinct']);$artifact=$org->firmwareArtifacts()->findOrFail($data['firmware_artifact_id']);return (new FirmwareDeploymentResource($this->service->create($r->user(),$artifact,$data['device_ids'])))->response()->setStatusCode(201);}
 public function show(Request $r,string $deployment){$this->org($r,'device.view');$d=$r->user()->organization->firmwareDeployments()->findOrFail($deployment);return new FirmwareDeploymentResource($this->service->detail($d));}
 private function org(Request $r,string $permission){abort_unless($r->user()->organization&&$r->user()->hasOrganizationPermission($permission),403);return $r->user()->organization;}
}
