<?php
namespace App\Http\Controllers;
use App\Http\Resources\NotificationResource;use App\Models\Notification;use App\Notifications\NotificationActionResolver;use App\Services\NotificationQueryService;use Illuminate\Http\Request;use Illuminate\Validation\Rule;
final class NotificationController extends Controller
{
 public function __construct(private NotificationActionResolver $actions,private NotificationQueryService $notifications){}
 public function index(Request$request){$filters=$request->validate(['filter'=>['nullable',Rule::in(['all','unread','action_required','dismissed'])],'category'=>['nullable',Rule::in(['updates','requests','approvals','mentions','system'])],'per_page'=>['nullable','integer',Rule::in([10,20,50])]]);$filter=$filters['filter']??'all';$query=$this->notifications->owned($request->user())->with(['actor:id,name','organization:id,name'])->when($filter==='dismissed',fn($q)=>$q->whereNotNull('dismissed_at'),fn($q)=>$q->whereNull('dismissed_at'))->when($filter==='unread',fn($q)=>$q->whereNull('read_at'))->when($filters['category']??null,fn($q,$category)=>$q->where('category',$category))->latest('created_at')->latest('id');if($filter==='action_required'){$items=$query->get()->filter(fn(Notification$item)=>$this->actions->resolve($item,$request->user())['actionRequired'])->values();$perPage=$filters['per_page']??20;$page=max(1,(int)$request->query('page',1));$slice=$items->slice(($page-1)*$perPage,$perPage)->values();$paginator=new \Illuminate\Pagination\LengthAwarePaginator($slice,$items->count(),$perPage,$page,['path'=>$request->url(),'query'=>$request->query()]);return NotificationResource::collection($paginator);}return NotificationResource::collection($query->paginate($filters['per_page']??20));}
 public function recent(Request$request){return NotificationResource::collection($this->notifications->recent($request->user()));}
 public function unreadCount(Request$request){return['count'=>$this->notifications->unreadCount($request->user())];}
 public function markRead(Request$request,string$notification){$item=$this->notifications->findOwned($request->user(),$notification);if(!$item->read_at)$item->update(['read_at'=>now()]);return new NotificationResource($item->load(['actor:id,name','organization:id,name']));}
 public function markUnread(Request$request,string$notification){$item=$this->notifications->findOwned($request->user(),$notification);if($item->read_at)$item->update(['read_at'=>null]);return new NotificationResource($item->load(['actor:id,name','organization:id,name']));}
 public function markAllRead(Request$request){$count=$this->notifications->activeUnread($request->user())->update(['read_at'=>now()]);return['updated'=>$count];}
 public function dismiss(Request$request,string$notification){$item=$this->notifications->findOwned($request->user(),$notification);if(!$item->dismissed_at)$item->update(['dismissed_at'=>now()]);return response()->noContent();}
 public function restore(Request$request,string$notification){$item=$this->notifications->findOwned($request->user(),$notification);if($item->dismissed_at)$item->update(['dismissed_at'=>null]);return new NotificationResource($item->load(['actor:id,name','organization:id,name']));}
}
