<?php
namespace App\Http\Controllers;
use App\Collaboration\{CollaborationResourceReference,CollaborationResourceRegistry};use App\Models\{Report,ResourcePublicationState,ResourcePublicationVersion};use App\Services\{ReportAccessService,ReportGenerationService,ReportPublicationService,ReviewHistoryService};use Illuminate\Http\Request;
final class ReportPublicationController extends Controller{
 public function __construct(private CollaborationResourceRegistry $registry,private ReportPublicationService $service,private ReviewHistoryService $history,private ReportAccessService $access,private ReportGenerationService $runs){}
 public function state(Request $r,string $report){$model=$this->registry->resolve($r->user(),new CollaborationResourceReference('report',$report),'view')->resource;return response()->json(['data'=>$this->service->state($model)]);}public function submit(Request $r,string $report){$model=Report::findOrFail($report);$d=$r->validate(['revision_id'=>'nullable|integer|min:1']);return response()->json(['data'=>$this->service->submissionData($this->service->submit($r->user(),$model,isset($d['revision_id'])?(int)$d['revision_id']:null))],201);}public function history(Request $r,string $report){return response()->json($this->history->forResource($r->user(),'report',$report,(int)$r->input('per_page',20)));}
 public function catalog(Request $r){abort_unless($r->user()->organization_id||$r->user()->isPlatformAdmin(),403);$ids=Report::query()->when(!$r->user()->isPlatformAdmin(),fn($q)=>$q->where('organization_id',$r->user()->organization_id))->select('id');$states=ResourcePublicationState::where('resource_type','report')->whereNotNull('current_publication_version_id')->whereIn('resource_id',$ids)->with('currentVersion.revision')->paginate((int)$r->input('per_page',25));return response()->json($states->through(fn($s)=>$this->item($r,$s)));}
 public function published(Request $r,string $report){$state=$this->publishedState($r,$report);return response()->json(['data'=>$this->item($r,$state,true)]);}
 public function versions(Request $r,string $report){$state=$this->publishedState($r,$report);return response()->json(ResourcePublicationVersion::where(['resource_type'=>'report','resource_id'=>$state->resource_id])->with(['revision:id,revision_number','publisher:id,name'])->latest('publication_number')->paginate((int)$r->input('per_page',20)));}
 public function run(Request $r,string $report){$state=$this->publishedState($r,$report);return response()->json(['data'=>$this->runs->requestPublished($state->currentVersion,$r->user())->load('requester:id,name')],202);}
 private function publishedState(Request $r,string $id):ResourcePublicationState{$report=Report::query()->when(!$r->user()->isPlatformAdmin(),fn($q)=>$q->where('organization_id',$r->user()->organization_id))->findOrFail($id);app(\App\Services\ResourceLifecycleService::class)->assertActive('report',$report->id,'This published Report is unavailable.');return ResourcePublicationState::where(['resource_type'=>'report','resource_id'=>$report->id])->whereNotNull('current_publication_version_id')->with('currentVersion.revision')->firstOrFail();}
 private function item(Request $request,$state,bool $snapshot=false):array{$version=$state->currentVersion;$revision=$version->revision;$s=$revision->snapshot;$report=Report::findOrFail($state->resource_id);$canRun=$this->access->canRunPublished($request->user(),$version);return ['id'=>(string)$report->id,'name'=>data_get($s,'metadata.name'),'description'=>data_get($s,'metadata.description'),'reportType'=>data_get($s,'metadata.reportType'),'configuration'=>$this->redact($request,$s['configuration']??[]),'currentVersion'=>['id'=>(string)$version->id,'number'=>$version->publication_number,'publishedAt'=>$version->published_at?->toISOString()],'approvedRevision'=>['id'=>(string)$revision->id,'number'=>$revision->revision_number],'capabilities'=>['canViewPublished'=>true,'canEdit'=>false,'canRun'=>$canRun],'snapshot'=>$snapshot?['metadata'=>$s['metadata']??[],'configuration'=>$this->redact($request,$s['configuration']??[])]:null];}
 private function redact(Request $r,array $config):array{try{app(\App\Services\ReportConfigurationService::class)->assertCurrentAccess($r->user(),$config);return $config;}catch(\Throwable){return ['restrictedSources'=>true,'deviceCount'=>count($config['device_ids']??[])];}}
}
