import { Link, useNavigate } from "react-router-dom";
import { Bell, CreditCard, LockKeyhole, LogOut, Palette, UserRound } from "lucide-react";
import { Button, Card, CardContent, CardHeader } from "../../components/ui";
import { SettingsHeader, SettingsLayout } from "../../components/settings/layout/SettingsLayout";
import { useAuth } from "../../context/AuthContext";
import { useBilling } from "../../context/BillingContext";

const sections=[{to:"/app/profile",title:"Profile",description:"Update your name and email.",icon:UserRound},{to:"/app/security",title:"Security",description:"Change your account password.",icon:LockKeyhole},{to:"/app/preferences",title:"Preferences",description:"Choose your interface theme.",icon:Palette},{to:"/app/notifications/settings",title:"Notifications",description:"Control account notification delivery.",icon:Bell}];
export default function SettingsHome(){const {user,logout}=useAuth();const {subscription,loading}=useBilling();const navigate=useNavigate();async function signOut(){await logout();navigate("/login",{replace:true});}return <SettingsLayout><SettingsHeader title="Account overview" description="Your personal account controls and service shortcuts."/><div className="grid gap-3 sm:grid-cols-2">{sections.map(({to,title,description,icon:Icon})=><Link to={to} key={to}><Card variant="interactive" className="h-full"><CardContent><Icon size={18} className="text-[var(--ds-primary)]"/><h3 className="mt-3 text-sm font-semibold text-[var(--ds-text)]">{title}</h3><p className="mt-1 text-xs text-[var(--ds-text-muted)]">{description}</p></CardContent></Card></Link>)}</div><Card><CardHeader title="Account summary"/><CardContent className="grid gap-4 text-sm sm:grid-cols-2"><div><p className="text-xs text-[var(--ds-text-muted)]">Signed in as</p><p className="mt-1 font-medium text-[var(--ds-text)]">{user?.name}</p><p className="text-xs text-[var(--ds-text-muted)]">{user?.email}</p></div><div><p className="text-xs text-[var(--ds-text-muted)]">Subscription</p><p className="mt-1 font-medium capitalize text-[var(--ds-text)]">{loading?"Loading...":subscription?.status??"Unavailable"}</p><Link to="/app/billing" className="mt-1 inline-flex items-center gap-1 text-xs text-[var(--ds-primary)]"><CreditCard size={13}/>Manage billing</Link></div></CardContent></Card><Card><CardHeader title="Account actions" description="End your current authenticated session."/><CardContent><Button variant="outline" leadingIcon={<LogOut size={15}/>} onClick={()=>void signOut()}>Log out</Button><p className="mt-3 text-xs text-[var(--ds-text-subtle)]">Account deactivation and deletion are not currently supported.</p></CardContent></Card></SettingsLayout>}
