<?php
namespace App\Services\Automation;
use App\Models\Organization;use App\Models\User;use App\Services\Admin\DeviceAccessService;use Illuminate\Support\Facades\Validator;use Illuminate\Validation\ValidationException;
class AutomationDefinitionValidator{
 public function __construct(private DeviceAccessService $deviceAccess){}
 public function validate(array $input,Organization $organization,bool $partial=false,?User $actor=null,bool $requiresManagement=false):array{
  $sometimes=$partial?'sometimes|':'';
  $v=Validator::make($input,['name'=>$sometimes.'required|string|max:255','description'=>'nullable|string|max:2000','enabled'=>'sometimes|boolean','trigger'=>$sometimes.'required|array','trigger.type'=>$sometimes.'required|in:telemetry,device_status,schedule,manual','trigger.deviceId'=>'nullable|integer','trigger.field'=>'nullable|string|max:100','conditions'=>$sometimes.'required|array','conditions.logic'=>$sometimes.'required|in:AND,OR','conditions.conditions'=>$sometimes.'array|max:20','conditions.conditions.*.field'=>'required|string|max:100','conditions.conditions.*.operator'=>'required|in:>,<,=,>=,<=,!=,contains,starts_with,ends_with,exists','conditions.conditions.*.value'=>'nullable','actions'=>$sometimes.'required|array|min:1|max:10','actions.*.type'=>'required|in:notification','actions.*.target'=>'nullable|string|max:255','actions.*.payload'=>'nullable|array','actions.*.payload.message'=>'required|string|max:2000','actions.*.continueOnFailure'=>'sometimes|boolean','schedule'=>'nullable|array','schedule.type'=>'required_with:schedule|in:once,daily,weekly,interval','schedule.time'=>'nullable|date_format:H:i','schedule.day'=>'nullable|in:Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday','schedule.intervalMinutes'=>'nullable|integer|min:1|max:10080','schedule.at'=>'nullable|date|after:now','schedule.enabled'=>'sometimes|boolean']);
  $v->after(function($v)use($input,$organization){$trigger=$input['trigger']??[];if(isset($trigger['deviceId'])&&!$organization->devices()->whereKey($trigger['deviceId'])->exists())$v->errors()->add('trigger.deviceId','The selected device is invalid.');if(($trigger['type']??null)==='schedule'&&!isset($input['schedule']))$v->errors()->add('schedule','A schedule trigger requires schedule configuration.');$s=$input['schedule']??null;if($s){if(($s['type']??null)==='once'&&!isset($s['at']))$v->errors()->add('schedule.at','A one-time schedule requires a future date.');if(($s['type']??null)==='daily'&&!isset($s['time']))$v->errors()->add('schedule.time','A daily schedule requires a time.');if(($s['type']??null)==='weekly'&&(!isset($s['day'])||!isset($s['time'])))$v->errors()->add('schedule.day','A weekly schedule requires a day and time.');if(($s['type']??null)==='interval'&&!isset($s['intervalMinutes']))$v->errors()->add('schedule.intervalMinutes','An interval schedule requires minutes.');}});
  if($v->fails())throw new ValidationException($v);$data=$v->validated();if($actor&&isset($data['trigger']['deviceId'])){$device=$requiresManagement?$this->deviceAccess->findManageableDeviceOrFail($actor,$data['trigger']['deviceId']):$this->deviceAccess->findViewableDeviceOrFail($actor,$data['trigger']['deviceId']);}return $data;
 }
 public function requiresAdvanced(array $definition):bool{return (($definition['conditions']['logic']??'AND')==='OR')||count($definition['actions']??[])>1||isset($definition['schedule'])||(($definition['trigger']['type']??null)==='schedule');}
}
