<?php
namespace App\Services\Automation;
use App\Collaboration\AutomationCollaborationAuthorizer;use App\Models\Automation;use App\Models\Organization;use App\Models\User;use App\Models\ResourceCollaborator;use App\Services\ResourceLifecycleService;use App\Services\SafeResourceSaveService;use Illuminate\Support\Facades\DB;
class AutomationDefinitionService{
 public function __construct(private AutomationDefinitionValidator $validator,private AutomationScheduleService $schedules,private SafeResourceSaveService $saves,private AutomationCollaborationAuthorizer $authorizer,private ResourceLifecycleService $lifecycle){}
 public function create(Organization $org,User $user,array $input):Automation{return DB::transaction(function()use($org,$user,$input){$data=$this->validator->validate($input,$org);$a=$org->automations()->create(['name'=>$data['name'],'description'=>$data['description']??null,'enabled'=>$data['enabled']??false,'status'=>($data['enabled']??false)?'active':'draft','created_by'=>$user->id,'updated_by'=>$user->id]);$this->replace($a,$data);ResourceCollaborator::updateOrCreate(['resource_type'=>'automation','resource_id'=>$a->id,'user_id'=>$user->id],['permission'=>'edit','granted_by'=>$user->id]);app(\App\Services\ResourceRevisionService::class)->recordAutomation($a,$user,'Automation created');return $a->load($this->relations());});}
 public function update(Automation $a,User $user,array $data,int|string|null $baseRevisionId=null,?string $idempotencyKey=null,?array $command=null):Automation{return $this->saves->execute($user,'automation',Automation::class,$a->id,$baseRevisionId,fn(User $actor,Automation $locked)=>abort_unless($this->authorizer->canEdit($actor,$locked),404),fn(Automation $locked)=>$this->lifecycle->assertActive('automation',$locked->id,'Disabled or Archived Automations cannot be edited.'),function(Automation $locked)use($user,$data){$current=$this->definition($locked);$definitionChanged=array_diff_key($current,['enabled'=>true])!==array_diff_key($data,['enabled'=>true]);$locked->update(['name'=>$data['name'],'description'=>$data['description']??null,'enabled'=>$data['enabled']??$locked->enabled,'status'=>($data['enabled']??$locked->enabled)?'active':'draft','version'=>$definitionChanged?$locked->version+1:$locked->version,'updated_by'=>$user->id]);$this->replace($locked,$data);return $locked;},fn(Automation $locked,User $actor)=>app(\App\Services\ResourceRevisionService::class)->recordAutomation($locked,$actor,'Automation definition updated'),true,$idempotencyKey,$command??$data); }
 public function definition(Automation $a):array{$a->loadMissing($this->relations());return ['name'=>$a->name,'description'=>$a->description,'enabled'=>$a->enabled,'trigger'=>['type'=>$a->triggers->first()?->type,...($a->triggers->first()?->configuration??[])],'conditions'=>['logic'=>$a->conditions->first()?->logic??'AND','conditions'=>$a->conditions->pluck('configuration')->all()],'actions'=>$a->actions->map(fn($x)=>['type'=>$x->type,...$x->configuration,'continueOnFailure'=>$x->continue_on_failure])->all(),'schedule'=>$a->schedules->first()?->configuration ? ['type'=>$a->schedules->first()->type,'enabled'=>$a->schedules->first()->enabled,...$a->schedules->first()->configuration] : null];}
 private function replace(Automation $a,array $d):void{$a->triggers()->delete();$trigger=$d['trigger'];$a->triggers()->create(['type'=>$trigger['type'],'configuration'=>array_diff_key($trigger,['type'=>true])]);$a->conditions()->delete();foreach($d['conditions']['conditions']??[] as $i=>$c)$a->conditions()->create(['logic'=>$d['conditions']['logic'],'position'=>$i,'configuration'=>$c]);$a->actions()->delete();foreach($d['actions'] as $i=>$x)$a->actions()->create(['type'=>$x['type'],'position'=>$i,'continue_on_failure'=>$x['continueOnFailure']??false,'configuration'=>array_diff_key($x,['type'=>true,'continueOnFailure'=>true])]);$a->schedules()->delete();if(isset($d['schedule'])){$s=$d['schedule'];$a->schedules()->create(['type'=>$s['type'],'enabled'=>$s['enabled']??true,'configuration'=>array_diff_key($s,['type'=>true,'enabled'=>true]),'next_run_at'=>$this->schedules->nextRun($s)]);}}
 private function relations():array{return ['organization','triggers','conditions','actions','schedules'];}
}
