import {useEffect,useState} from "react";
import {FileInput,Plus} from "lucide-react";
import {applyDeviceTemplate,listDeviceTemplates} from "../../../services/device-template.service";
import {createDeviceParameter,deleteDeviceParameter,listDeviceParameters,updateDeviceParameter} from "../../../services/device-parameter.service";
import type {DeviceParameter,DeviceParameterDataType,DeviceTemplate} from "../../../types/device";
import {Badge,Button,Card,CardHeader,EmptyState,ErrorState,Input,Modal,Select,Skeleton,Textarea} from "../../ui";

export default function DeviceParametersPanel({deviceId,canManage,admin=false}:{deviceId:string;canManage:boolean;admin?:boolean}){
 const [items,setItems]=useState<DeviceParameter[]>([]),[templates,setTemplates]=useState<DeviceTemplate[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[refresh,setRefresh]=useState(0),[open,setOpen]=useState(false),[applyOpen,setApplyOpen]=useState(false),[templateId,setTemplateId]=useState(""),[editing,setEditing]=useState<DeviceParameter|null>(null),[saving,setSaving]=useState(false);
 const [form,setForm]=useState({name:"",key:"",dataType:"number" as DeviceParameterDataType,unit:"",description:""});
 useEffect(()=>{let active=true;listDeviceParameters(deviceId,admin).then(v=>{if(active)setItems(v)}).catch(()=>{if(active)setError("Device parameters could not be loaded.")}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[deviceId,admin,refresh]);
 const start=(p?:DeviceParameter)=>{setEditing(p??null);setForm(p?{name:p.name,key:p.key,dataType:p.dataType,unit:p.unit??"",description:p.description??""}:{name:"",key:"",dataType:"number",unit:"",description:""});setOpen(true)};
 const startApply=async()=>{setError("");try{const data=(await listDeviceTemplates()).data;setTemplates(data);setTemplateId(data[0]?.id??"");setApplyOpen(true)}catch{setError("Templates could not be loaded.")}};
 const apply=async()=>{setSaving(true);try{await applyDeviceTemplate(deviceId,templateId,admin);setApplyOpen(false);setRefresh(v=>v+1)}catch{setError("Template could not be applied. Remove conflicting parameter keys or choose another template.")}finally{setSaving(false)}};
 const save=async()=>{setSaving(true);try{if(editing)await updateDeviceParameter(deviceId,editing.id,{name:form.name,unit:form.unit||null,description:form.description||null},admin);else await createDeviceParameter(deviceId,{name:form.name,key:form.key,data_type:form.dataType,unit:form.unit||null,description:form.description||null,configuration:form.dataType==="enum"?{options:["value"]}:{}},admin);setOpen(false);setRefresh(v=>v+1)}catch{setError("Parameter could not be saved. Check the field values.")}finally{setSaving(false)}};
 const remove=async(p:DeviceParameter)=>{if(!confirm(`Delete parameter definition?\nHistorical telemetry for ${p.name} will be preserved.`))return;await deleteDeviceParameter(deviceId,p.id,admin);setRefresh(v=>v+1)};
 const display=(value:DeviceParameter["latestValue"])=>value===null||value===undefined?"No data":typeof value==="boolean"?(value?"True":"False"):String(value);
 return <Card><CardHeader title="Parameters" description="Definitions come from the Device schema; values are the latest authorized telemetry." action={canManage?<span className="flex gap-2">{!admin&&<Button size="small" variant="outline" leadingIcon={<FileInput size={14}/>} onClick={()=>void startApply()}>Apply Template</Button>}<Button size="small" leadingIcon={<Plus size={14}/>} onClick={()=>start()}>Add Parameter</Button></span>:undefined}/>{error&&<ErrorState description={error}/>} {loading?<Skeleton className="m-4 h-40"/>:items.length===0?<EmptyState title="No parameters defined for this device." description={canManage?"Define a parameter or apply a reusable Template.":undefined} action={canManage?<Button size="small" onClick={()=>start()}>Add Parameter</Button>:undefined}/>:<div className="overflow-x-auto"><table className="w-full min-w-[820px] text-left text-xs"><thead><tr className="text-[var(--ds-text-muted)]"><th className="p-3">Definition</th><th>Type</th><th>Unit</th><th>Latest value</th><th>Last update</th>{canManage&&<th className="text-right">Actions</th>}</tr></thead><tbody>{items.map(p=><tr key={p.id} className="border-t"><td className="p-3"><p className="font-medium">{p.name}</p><p className="font-mono text-[var(--ds-text-muted)]">{p.key}</p></td><td><Badge>{p.dataType}</Badge></td><td>{p.unit??"—"}</td><td className={p.latestValue===null||p.latestValue===undefined?"text-[var(--ds-text-muted)]":"font-medium"}>{display(p.latestValue)}</td><td>{p.latestRecordedAt?new Date(p.latestRecordedAt).toLocaleString():"—"}</td>{canManage&&<td className="text-right"><Button size="compact" variant="outline" onClick={()=>start(p)}>Edit</Button> <Button size="compact" variant="danger" onClick={()=>void remove(p)}>Delete</Button></td>}</tr>)}</tbody></table></div>}
 <Modal open={open} onClose={()=>setOpen(false)} title={editing?"Edit Parameter":"Add Parameter"} description={editing?"The key and data type are immutable.":"For reusable schemas, prefer adding the definition to the Device Template."} footer={<><Button variant="ghost" onClick={()=>setOpen(false)}>Cancel</Button><Button loading={saving} onClick={()=>void save()}>{editing?"Save":"Add Parameter"}</Button></>}><div className="space-y-3"><Input label="Name" required value={form.name} onChange={e=>setForm(v=>({...v,name:e.target.value}))}/><Input label="Key" required readOnly={!!editing} value={form.key} onChange={e=>setForm(v=>({...v,key:e.target.value}))}/><Select label="Data Type" disabled={!!editing} value={form.dataType} onChange={e=>setForm(v=>({...v,dataType:e.target.value as DeviceParameterDataType}))}><option value="number">Number</option><option value="integer">Integer</option><option value="string">String</option><option value="boolean">Boolean</option><option value="enum">Enum</option></Select><Input label="Unit" value={form.unit} onChange={e=>setForm(v=>({...v,unit:e.target.value}))}/><Textarea label="Description" value={form.description} onChange={e=>setForm(v=>({...v,description:e.target.value}))}/></div></Modal>
 <Modal open={applyOpen} onClose={()=>setApplyOpen(false)} title="Apply Device Template" description="All definitions are copied atomically. Existing telemetry is preserved." footer={<><Button variant="ghost" onClick={()=>setApplyOpen(false)}>Cancel</Button><Button loading={saving} disabled={!templateId} onClick={()=>void apply()}>Apply Template</Button></>}><Select label="Template" value={templateId} onChange={e=>setTemplateId(e.target.value)}>{templates.length===0?<option value="">No Templates available</option>:templates.map(t=><option key={t.id} value={t.id}>{t.name} ({t.parameterCount} parameters)</option>)}</Select></Modal>
 </Card>;
}
