import {expect,test,type Page} from "./fixtures/test";
import {databaseRow} from "./support/database";

const token="10303|phase103-admin1-token";
async function authenticate(page:Page){await page.addInitScript(value=>localStorage.setItem("iot_token",value),token)}

test("authorized user completes the Template onboarding workspace",async({page,isolatedBackend})=>{
 test.setTimeout(120_000);await authenticate(page);await page.goto("/app/developer/templates");
 await page.getByRole("button",{name:"Create template"}).click();
 await page.getByLabel("Name").fill("Browser Air Template");
 await page.getByLabel("Hardware").selectOption("esp32");await page.getByLabel("Connection type").selectOption("wifi");
 await page.getByLabel("Description").fill("Browser-created safe Template");const templateCreate=page.waitForResponse(r=>r.url().endsWith("/api/device-templates")&&r.request().method()==="POST");await page.getByRole("button",{name:"Create",exact:true}).click();expect((await templateCreate).status()).toBe(201);
 await expect(page).toHaveURL(/\/app\/developer\/templates\/\d+\/home$/);await expect(page.getByText(/Template ID:/)).toBeVisible();
 const templateId=page.url().match(/templates\/(\d+)/)![1];expect(databaseRow(isolatedBackend.databasePath,"select name, device_type, protocol, organization_id from device_templates where id = ?",[templateId])).toMatchObject({name:"Browser Air Template",device_type:"esp32",protocol:"wifi"});
 await page.getByRole("button",{name:"Settings"}).click();await page.getByLabel("Description").fill("Persisted Template settings");await page.getByRole("button",{name:"Save",exact:true}).click();await page.reload();await expect(page.getByText("Persisted Template settings")).toBeVisible();
 await page.getByRole("link",{name:"Datastreams"}).click();await expect(page.getByText("No Datastreams yet")).toBeVisible();await page.getByRole("button",{name:"Create new"}).first().click();await page.getByLabel("Datastream name").fill("Temperature");await page.getByLabel("Identifier").fill("temperature");await page.getByRole("button",{name:"Units"}).click();await page.getByLabel("Unit").fill("°C");await page.getByRole("button",{name:"Save",exact:true}).click();await page.reload();await expect(page.getByText("temperature",{exact:true})).toBeVisible();
 await page.getByRole("link",{name:"Web Dashboard"}).click();await page.getByRole("button",{name:"Customize Dashboard"}).click();await page.getByRole("button",{name:"Add Label widget"}).click();const dashboardSave=page.waitForResponse(response=>response.url().includes("/device-templates/")&&response.url().endsWith("/dashboard")&&response.request().method()==="PATCH");await page.getByRole("button",{name:"Save Dashboard"}).click();expect((await dashboardSave).status()).toBe(200);const dashboardReload=page.waitForResponse(response=>response.url().includes("/device-templates/")&&response.url().endsWith("/dashboard")&&response.request().method()==="GET");await page.reload();expect((await dashboardReload).status()).toBe(200);await expect(page.getByText("Label",{exact:true}).first()).toBeVisible();
 await page.getByRole("link",{name:"Metadata"}).click();await page.getByLabel("Name").fill("Installation zone");await page.getByLabel("Key").fill("installation_zone");const metadataSave=page.waitForResponse(r=>r.url().endsWith(`/api/device-templates/${templateId}/metadata`)&&r.request().method()==="POST");await page.getByRole("button",{name:"Create",exact:true}).click();expect((await metadataSave).status()).toBe(200);await expect(page.getByText(/Installation zone/)).toBeVisible();expect(databaseRow(isolatedBackend.databasePath,"select name, key, data_type from device_template_metadata_definitions where device_template_id = ? and key = ?",[templateId,"installation_zone"])).toMatchObject({name:"Installation zone",key:"installation_zone",data_type:"string"});await page.reload();await expect(page.getByText(/Installation zone/)).toBeVisible();
 await page.goto(`/app/developer/templates/${templateId}/events`);await page.getByLabel("Name").fill("Overheat warning");await page.getByLabel("Code").fill("overheat_warning");await page.getByLabel("Severity").selectOption("warning");const eventSave=page.waitForResponse(r=>r.url().endsWith(`/api/device-templates/${templateId}/events`)&&r.request().method()==="POST");await page.getByRole("button",{name:"Create",exact:true}).click();expect((await eventSave).status()).toBe(200);await expect(page.getByText(/Overheat warning/)).toBeVisible();expect(databaseRow(isolatedBackend.databasePath,"select name, code, severity from device_template_event_definitions where device_template_id = ? and code = ?",[templateId,"overheat_warning"])).toMatchObject({name:"Overheat warning",code:"overheat_warning",severity:"warning"});await page.reload();await expect(page.getByText(/Overheat warning/)).toBeVisible();
 const fresh=await page.request.get(`http://127.0.0.1:18000/api/device-templates/${templateId}`,{headers:{Authorization:`Bearer ${token}`,Accept:"application/json"}});expect(fresh.status()).toBe(200);expect((await fresh.json()).data).toMatchObject({id:String(templateId),name:"Browser Air Template"});
 await page.goto(`/app/developer/templates/${templateId}/home`);await page.getByRole("button",{name:"Add first Device"}).click();await page.getByLabel("Device name").fill("Browser Air Node");await page.getByRole("button",{name:"Create",exact:true}).click();await page.reload();
 await expect(page.getByRole("button",{name:"Set up Datastreams"}).locator("span").first()).toHaveClass(/bg-emerald-500/);await expect(page.getByRole("button",{name:"Set up the Web Dashboard"}).locator("span").first()).toHaveClass(/bg-emerald-500/);await expect(page.getByRole("button",{name:"Add first Device"}).locator("span").first()).toHaveClass(/bg-emerald-500/);
 await page.goto(page.url().replace("/home","/datastreams"));await expect(page.getByText("temperature",{exact:true})).toBeVisible();
});
