import {useEffect,useState,type FormEvent} from "react";
import {Plus,RefreshCw} from "lucide-react";
import {Link,useSearchParams} from "react-router-dom";
import AdminPageHeader from "../../components/admin/layout/AdminPageHeader";
import DeviceAccessModal from "../../components/admin/device-access/DeviceAccessModal";
import {Badge,Button,Card,CardContent,DataTable,ErrorState,Input,Select,Skeleton,type DataTableColumn} from "../../components/ui";
import {deleteDeviceAccessAssignment,getAdminOrganizations,listDeviceAccessAssignments} from "../../services/admin.service";
import type {AdminOrganization,DeviceAccessAssignment,DeviceAccessListResponse} from "../../types/admin";

export default function AdminDeviceAccess(){
 const [params,setParams]=useSearchParams();const query=params.toString();const [result,setResult]=useState<DeviceAccessListResponse|null>(null);const [organizations,setOrganizations]=useState<AdminOrganization[]>([]);const [search,setSearch]=useState(params.get("search")??"");const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [refresh,setRefresh]=useState(0);const [open,setOpen]=useState(false);const [editing,setEditing]=useState<DeviceAccessAssignment|null>(null);
 useEffect(()=>{let current=true;Promise.all([listDeviceAccessAssignments(Object.fromEntries(new URLSearchParams(query))),getAdminOrganizations()]).then(([data,orgs])=>{if(current){setResult(data);setOrganizations(orgs);}}).catch(()=>{if(current)setError("Device access assignments could not be loaded.");}).finally(()=>{if(current)setLoading(false);});return()=>{current=false;};},[query,refresh]);
 const reload=()=>{setLoading(true);setError("");setRefresh(v=>v+1);};
 const setFilter=(key:string,value:string)=>{const next=new URLSearchParams(params);if(value)next.set(key,value);else next.delete(key);if(key!=="page")next.delete("page");setLoading(true);setError("");setParams(next);};
 const submit=(event:FormEvent)=>{event.preventDefault();setFilter("search",search.trim());};
 const remove=async(item:DeviceAccessAssignment)=>{if(!window.confirm(`Remove device access?\n${item.device.name} will no longer be available to ${item.user.name}.`))return;try{await deleteDeviceAccessAssignment(item.id);reload();}catch{setError("Assignment could not be removed.");}};
 const columns:DataTableColumn<DeviceAccessAssignment>[]=[{key:"staff",header:"Staff",render:i=><div><Link to={`/admin/users/${i.user.id}`} className="font-medium text-[var(--ds-text)] hover:text-[var(--ds-primary)]">{i.user.name}</Link><div className="text-[11px]">{i.user.email}</div></div>},{key:"device",header:"Device",render:i=><div><Link to={`/admin/devices/${i.device.id}`} className="font-medium text-[var(--ds-text)] hover:text-[var(--ds-primary)]">{i.device.name}</Link><div className="text-[11px]">{i.device.identifier??"—"}</div></div>},{key:"org",header:"Organization",render:i=>i.device.organizationName},{key:"level",header:"Access",render:i=><Badge tone={i.accessLevel==="full_access"?"success":"info"}>{i.accessLevel==="full_access"?"Full Access":"Viewer"}</Badge>},{key:"by",header:"Assigned By",render:i=>i.assignedBy?.name??"System"},{key:"at",header:"Assigned At",render:i=>new Date(i.createdAt).toLocaleString()},{key:"actions",header:"Actions",align:"right",render:i=><div className="flex flex-wrap justify-end gap-2"><Button size="compact" variant="outline" onClick={()=>{setEditing(i);setOpen(true);}}>{i.capabilities.canUpgrade?"Upgrade to Full Access":"Downgrade to Viewer"}</Button><Button size="compact" variant="danger" onClick={()=>void remove(i)}>Revoke Access</Button></div>}];
 const page=result?.meta.current_page??1;
 return <div className="space-y-5"><AdminPageHeader title="Device Access" description="Manage Staff, Device, and access-level assignments." action={<div className="flex gap-2"><Button variant="outline" size="small" leadingIcon={<RefreshCw size={14}/>} loading={loading} onClick={reload}>Refresh</Button><Button size="small" leadingIcon={<Plus size={14}/>} onClick={()=>{setEditing(null);setOpen(true);}}>Assign Device</Button></div>}/><Card><CardContent><form onSubmit={submit} className="grid gap-3 sm:grid-cols-2 lg:grid-cols-[1fr_200px_170px_120px_auto]"><Input aria-label="Search assignments" placeholder="Staff, email, device, identifier, organization" value={search} onChange={e=>setSearch(e.target.value)}/><Select aria-label="Filter organization" value={params.get("organization_id")??""} onChange={e=>setFilter("organization_id",e.target.value)}><option value="">All organizations</option>{organizations.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</Select><Select aria-label="Filter access" value={params.get("access_level")??""} onChange={e=>setFilter("access_level",e.target.value)}><option value="">All access</option><option value="viewer">Viewer</option><option value="full_access">Full Access</option></Select><Select aria-label="Rows per page" value={params.get("per_page")??"25"} onChange={e=>setFilter("per_page",e.target.value)}><option value="25">25</option><option value="50">50</option><option value="100">100</option></Select><Button type="submit">Search</Button></form></CardContent></Card>{error?<Card><ErrorState description={error} retry={reload}/></Card>:loading&&!result?<Skeleton className="h-96"/>:result&&<><DataTable rows={result.data} columns={columns} getRowKey={i=>i.id} caption="Device access assignments" empty="No assignments match the selected filters."/><div className="flex items-center justify-between text-xs text-[var(--ds-text-muted)]"><span>{result.meta.total} assignments · page {page} of {result.meta.last_page}</span><div className="flex gap-2"><Button size="compact" variant="outline" disabled={page<=1} onClick={()=>setFilter("page",String(page-1))}>Previous</Button><Button size="compact" variant="outline" disabled={page>=result.meta.last_page} onClick={()=>setFilter("page",String(page+1))}>Next</Button></div></div></>}<DeviceAccessModal open={open} onClose={()=>setOpen(false)} onSaved={async()=>reload()} assignment={editing}/></div>;
}
