/* eslint-disable react-hooks/set-state-in-effect */
import {useEffect,useState} from "react";
import {revisionService} from "../../services/revision.service";
import type {ResourceRevision,RevisionDetail} from "../../types/revision";

export default function RevisionHistoryPanel({resourceId,resourceType="device"}:{resourceId:string;resourceType?:string}){
 const[items,setItems]=useState<ResourceRevision[]>([]);const[detail,setDetail]=useState<RevisionDetail|null>(null);const[page,setPage]=useState(1);const[last,setLast]=useState(1);const[loading,setLoading]=useState(true);
 useEffect(()=>{setLoading(true);revisionService.list(resourceType,resourceId,page).then(r=>{setItems(r.data);setLast(r.last_page)}).finally(()=>setLoading(false))},[resourceId,resourceType,page]);
 if(loading)return <p aria-live="polite">Loading revision history…</p>;
 return <div className="grid gap-4 lg:grid-cols-2"><section aria-label="Revision history"><h2 className="text-lg font-semibold">Revision History</h2><p className="mb-3 text-sm text-[var(--ds-text-muted)]">Accepted configuration changes; live state is excluded.</p><ol className="space-y-2">{items.map(revision=><li key={revision.id}><button type="button" onClick={()=>revisionService.detail(resourceType,resourceId,revision.id).then(setDetail)} className="w-full rounded-md border border-[var(--ds-border)] p-3 text-left"><span className="font-medium">Revision {revision.revisionNumber}</span>{revision.isCurrent&&<span className="ml-2 rounded px-2 text-xs">Current</span>}<span className="block text-sm">{revision.changeSummary}</span><span className="block text-xs text-[var(--ds-text-muted)]">{revision.createdBy?.name??"System baseline"} · {new Date(revision.createdAt).toLocaleString()}</span><span className="block text-xs">{revision.changedSections.join(", ")}</span></button></li>)}</ol>{last>1&&<nav aria-label="Revision pages" className="mt-3 flex gap-2"><button disabled={page===1} onClick={()=>setPage(value=>value-1)}>Previous</button><span>Page {page} of {last}</span><button disabled={page===last} onClick={()=>setPage(value=>value+1)}>Next</button></nav>}</section><section aria-label="Revision detail" className="rounded-md border border-[var(--ds-border)] p-4">{detail?<><h3 className="font-semibold">Revision {detail.revisionNumber}</h3><p className="text-sm">Contributor: {detail.createdBy?.name??"System baseline"}</p>{resourceType==="location"?<dl className="mt-2 space-y-2 text-sm"><div><dt className="text-xs text-[var(--ds-text-muted)]">Name</dt><dd>{String(detail.snapshot.metadata.name??"")}</dd></div><div><dt className="text-xs text-[var(--ds-text-muted)]">Description</dt><dd>{String(detail.snapshot.metadata.description??"No description")}</dd></div></dl>:<><p className="text-sm">Dashboard: {"dashboard" in detail.snapshot&&detail.snapshot.dashboard?`${detail.snapshot.dashboard.widgets.length} widgets`:"Not configured"}</p><p className="text-sm">Parameters: {"parameters" in detail.snapshot?detail.snapshot.parameters.length:0} definitions</p></>}</>:<p className="text-sm text-[var(--ds-text-muted)]">Choose a revision to inspect its safe configuration summary.</p>}</section></div>;
}
